### ISSUE TITLE
引入框架后android.content.res.Resources$NotFoundException 异常

### ISSUE THREAD

**Issue by androidCoderxiao** [JessYanCoding/AndroidAutoSize#100]
### Environment
- [x] Autosize Version: v1.0.6 
- [x] Target Android Version: Android 8.0 
- [x] Device Model: Nexus 6 
- [x] Device Resolution: 1080px * 1920px
- [x] Design Size On AndroidManifest: 360dp * 640dp

### Bug Description:
引入框架后
android.content.res.Resources$NotFoundException: File res/drawable/text_select_handle_middle_material.xml from drawable resource ID #0x1080835

报错是在Activity 的 dispatchTouchEvent 方法中抛出异常。 注释掉框架后又能恢复正常。

### Log:

android.content.res.Resources$NotFoundException: File res/drawable/text_select_handle_middle_material.xml from drawable resource ID #0x1080835

**Comment by JessYanCoding** [comment]
support v7 的版本

**Comment by androidCoderxiao** [comment]
com.android.support:appcompat-v7:27.1.1

**Comment by JessYanCoding** [comment]
升级到 28.0.0 试试

**Comment by androidCoderxiao** [comment]
还是不行 。。

**Comment by JessYanCoding** [comment]
试试框架 v0.6.0 版本

**Comment by androidCoderxiao** [comment]
这样还是不行，哎 v7包重复依赖的地方都排除过了,同事的环境编译出来也存在这个问题 。我再找找看是什么原因 。感谢Jess大神 !

**Comment by JessYanCoding** [comment]
因为报错中这个未找到的资源文件是 android 内部的，并且 v0.6.0 未加入 support v7 的版本你能运行，百分 80 是与 v7 相关的问题，你在找找把，不行就用 v0.6.0

**Comment by slma93** [comment]
我这边用v0.6.0也不行，去掉库的引用就没问题
