### ISSUE TITLE
什么时候支持androidx

### ISSUE THREAD

**Issue by ChaiJiangpeng** [JessYanCoding/AndroidAutoSize#101]
### Environment
- [x] Autosize Version: 
- [x] Target Android Version: 
- [x] Device Model: 
- [x] Device Resolution: 
- [x] Design Size On AndroidManifest: 

### Log:

```log


```

### Related Code:
```java
  

```

**Comment by JessYanCoding** [comment]
支持时，通知你

**Comment by ChaiJiangpeng** [comment]
ok，谢谢

**Comment by YuJunKui1995** [comment]
我说怎么没效果。。。

**Comment by YuJunKui1995** [comment]
mark  关注  适配了说下

**Comment by BrightVan** [comment]
这个库和Androidx不冲突啊。。。

**Comment by YuJunKui1995** [comment]
确实不冲突 之前可能配置有问题
