### ISSUE TITLE
如何实现页面修改同步

### ISSUE THREAD

**Issue by TomorrowDreamer** [JessYanCoding/AndroidAutoSize#102]
有两个Activity A和B, 都实现了CustomAdapt接口， A的主要功能是展示列表，B的主要功能是放大或者缩小A中列表的展示效果。我的逻辑是：
1.打开A页面，然后跳转到B页面，在B中AutosizeConfig 执行stop方法
2.我在B页面修改了getSizeInDp() 的返回值，并且执行restart方法
3.回到A页面时，列表的展示效果还是和之前相同。
【问题】如何才能实现修改同步，当我在B页面修改了getSizeInDp() 的返回值，A页面列表同步进行缩放。求教思路~
 @Override
    public boolean isBaseOnWidth() {
        return true;
    }

    @Override
    public float getSizeInDp() {
        return ApplicationBase.DP_VALUE;
    }

**Comment by TomorrowDreamer** [comment]
@JessYanCoding 可以分享下实现UI修改同步的思路嘛，3Q！

**Comment by JessYanCoding** [comment]
思路都错了，AutoSize#autoConvertDensity 使用这个 API 想什么时候修改就什么时候修改，全局的

**Comment by TomorrowDreamer** [comment]
@JessYanCoding  谢谢指教
