### ISSUE TITLE
DialogFragment 和 Dialog 显示异常

### ISSUE THREAD

**Issue by guanjunhello** [JessYanCoding/AndroidAutoSize#103]
你好，我查看了问题汇总的issues ，以及closed的issues，发现没有小伙伴跟我情况一样，所以新建一个issue，求助 Jess 大佬
现在 DialogFragment 和 Dialog 显示会经常出现显示异常，Dialog 是出现半透明背景，内容完全不显示，如图：
Dialog ：
![image](https://user-images.githubusercontent.com/25898277/49556672-df55d400-f93f-11e8-8a26-f3f9d1d19994.png)
DialogFragment ：
![image](https://user-images.githubusercontent.com/25898277/49556685-ebda2c80-f93f-11e8-8cf5-e8b1b8d52553.png)
DialogFragment ：
![image](https://user-images.githubusercontent.com/25898277/49556702-fc8aa280-f93f-11e8-8786-cca2c9ac31b0.png)

我在BaseActivity中使用AutoSizeConfig.getInstance().stop(this)之后，显示正常情况是这样子的
![image](https://user-images.githubusercontent.com/25898277/49556859-95212280-f940-11e8-92c3-9d5dc9ee9326.png)

**Comment by JessYanCoding** [comment]
https://github.com/JessYanCoding/AndroidAutoSize/issues/13#11

**Comment by JessYanCoding** [comment]
首先你搜索 issues 的步骤是对的，先查看问题汇总的 issues，在查看历史 Issues，但是有没有把所有与 Dialog、弹窗有关的 issues 中的解决方案都试过？因为哪怕相同问题但问题呈现的形式也有可能不一样，不一定非得是和你这个 bug 的呈现形式描述的一模一样的 issues 才能解决你的问题，Dialog 这类 issues 我回答过不下 3 个解决方案
