### ISSUE TITLE
屏幕旋转后RecyclerView item异常

### ISSUE THREAD

**Issue by Mitaxing** [JessYanCoding/AndroidAutoSize#105]
### Environment
- [x] Autosize Version: 1.1.0
- [x] Target Android Version: 27
- [x] Device Model: 小米4
- [x] Device Resolution: 1280*720
- [x] Design Size On AndroidManifest: 411dp*823dp

### Bug Description:
屏幕旋转后RecyclerView部分item大小显示异常，已经参照了其他issues中的解决方法，在onBindViewHolder中添加AutoSize.autoConvertDensity(context, 411, true);仍然有此问题。

### Screenshot
![qq 20181211142010](https://user-images.githubusercontent.com/29652136/49782374-07cf3b00-fd51-11e8-9b7b-aef0661152d5.png)

**Comment by JessYanCoding** [comment]
如果在 onBindViewHolder 中调用 AutoSize.autoConvertDensity 依然不起作用，那就说明某处代码，导在某一时刻，导致 density 失效或者异常，如果找不到，这个影响 density 的地方，依然存在上述问题，你只有考虑取消这个页面的适配，今日头条屏幕适配方案的原理比较简单，无非就是在修改 density，但由于系统或其他未知原因可能导致修改的 density 失效，现在已知的解决方案就是在布局显示之前将 density 纠正为正确的值，如果这个解决方案都不能解决你的问题，那就只有考虑取消适配了，RecyclerView 的 issues 我收到过多个，此方案解决不了问题你是第一个

**Comment by wanggq654321** [comment]
请问这个问题解决了吗？ 我也遇到同样的问题呢

**Comment by zhongwls** [comment]
我也遇到同样的问题，万能解决方案试了也不行，我的是横屏的应用，然后锁屏了，之后打开发现recyclerview的item显示缩小了

**Comment by zhongwls** [comment]
并不是所有的手机都有问题。

**Comment by JessYanCoding** [comment]
可能是 recyclerview 复用之前的 View 导致的，最好在  onBindHodlder  中使用 AutoSize.autoConvertDensityOfGlobal(activity) 设置 Density 后，再手动刷新这个 Item View 的所有 UI 内容
