### ISSUE TITLE
升级到1.1.1版本后出现横屏不适配问题

### ISSUE THREAD

**Issue by liulilei** [JessYanCoding/AndroidAutoSize#107]
### Environment
- [x] Autosize Version: 
- [x] Target Android Version: android 8.0
- [x] Device Model: 华为mate10 小米5
- [x] Device Resolution: 720 * 1280  1080*2160
- [x] Design Size On AndroidManifest:  360dp * 640dp

实现了 CustomAdapt 也设置了

override fun isBaseOnWidth(): Boolean {
        return true
    }

    override fun getSizeInDp(): Float {
        return 640f
    }
华为mate10 设置 ：
override fun isBaseOnWidth(): Boolean {
        return false
    }
正常  
但是用oppoA57 6.0.1系统
配置如下  return true 正常  return  false 异常  和华为mate10 正好是反的
override fun isBaseOnWidth(): Boolean {
        return true
    }

**Comment by liulilei** [comment]
测试了1.1.0和1.0.6版本 和1.1.1碰到同样的问题 但是切换到1.0.5就正常

**Comment by JessYanCoding** [comment]
```java 
AutoSizeConfig.getInstance()
                //屏幕适配监听器
                .setOnAdaptListener(new onAdaptListener() {
                    @Override
                    public void onAdaptBefore(Object target, Activity activity) {
                        //使用以下代码, 可支持 Android 的分屏或缩放模式, 但前提是在分屏或缩放模式下当用户改变您 App 的窗口大小时
                        //系统会重绘当前的页面, 经测试在某些机型, 某些情况下系统不会重绘当前页面, ScreenUtils.getScreenSize(activity) 的参数一定要不要传 Application!!!
                        AutoSizeConfig.getInstance().setScreenWidth(ScreenUtils.getScreenSize(activity)[0]);
                        AutoSizeConfig.getInstance().setScreenHeight(ScreenUtils.getScreenSize(activity)[1]);
                    }

                    @Override
                    public void onAdaptAfter(Object target, Activity activity) {
                        
                    }
                });
```

**Comment by JessYanCoding** [comment]
上面代码不行，就上图，Bug 描述不清晰无法解决 issues

**Comment by liulilei** [comment]
> 上面代码不行，就上图，Bug 描述不清晰无法解决 issues

谢谢解答，我先去试下  如果还是不行，我写一个demo 然后截图上传

**Comment by JessYanCoding** [comment]
好的👌

**Comment by liulilei** [comment]
新建一个demo测试 显示没问题   我也很纳闷  为什么自己项目里面就会有问题  不知道作者 能否提示哪些地方会造成这方面的错误  针对横屏

**Comment by JessYanCoding** [comment]
我上面说了不适配每个人理解不一样，你不上图无法清晰的理解的你问题

**Comment by MyMrXu** [comment]
我也出现了横屏不适配的问题
MI6手机
我使用以下代码解决了这个问题
AutoSizeConfig.getInstance().onAdaptListener = object : onAdaptListener {
            override fun onAdaptBefore(target: Any, activity: Activity) {
                //使用以下代码, 可支持 Android 的分屏或缩放模式, 但前提是在分屏或缩放模式下当用户改变您 App 的窗口大小时
                //系统会重绘当前的页面, 经测试在某些机型, 某些情况下系统不会重绘当前页面, ScreenUtils.getScreenSize(activity) 的参数一定要不要传 Application!!!
                if (activity.requestedOrientation == ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE) {
                    AutoSizeConfig.getInstance().screenWidth = ScreenUtils.getScreenSize(activity)[1]
                    AutoSizeConfig.getInstance().screenHeight = ScreenUtils.getScreenSize(activity)[0]
                } else {
                    AutoSizeConfig.getInstance().screenWidth = ScreenUtils.getScreenSize(activity)[0]
                    AutoSizeConfig.getInstance().screenHeight = ScreenUtils.getScreenSize(activity)[1]
                }
            }

            override fun onAdaptAfter(target: Any, activity: Activity) {

            }
        }

**Comment by MyMrXu** [comment]
我也出现了横屏不适配的问题
MI6手机
我使用以下代码解决了这个问题
`AutoSizeConfig.getInstance().onAdaptListener = object : onAdaptListener {
            override fun onAdaptBefore(target: Any, activity: Activity) {
                //使用以下代码, 可支持 Android 的分屏或缩放模式, 但前提是在分屏或缩放模式下当用户改变您 App 的窗口大小时
                //系统会重绘当前的页面, 经测试在某些机型, 某些情况下系统不会重绘当前页面, ScreenUtils.getScreenSize(activity) 的参数一定要不要传 Application!!!
                if (activity.requestedOrientation == ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE) {
                    AutoSizeConfig.getInstance().screenWidth = ScreenUtils.getScreenSize(activity)[1]
                    AutoSizeConfig.getInstance().screenHeight = ScreenUtils.getScreenSize(activity)[0]
                } else {
                    AutoSizeConfig.getInstance().screenWidth = ScreenUtils.getScreenSize(activity)[0]
                    AutoSizeConfig.getInstance().screenHeight = ScreenUtils.getScreenSize(activity)[1]
                }
            }

            override fun onAdaptAfter(target: Any, activity: Activity) {

            }
        }`

**Comment by MyMrXu** [comment]
我也出现了横屏不适配的问题
MI6手机
我使用以下代码解决了这个问题
```
AutoSizeConfig.getInstance().onAdaptListener = object : onAdaptListener {
            override fun onAdaptBefore(target: Any, activity: Activity) {
                //使用以下代码, 可支持 Android 的分屏或缩放模式, 但前提是在分屏或缩放模式下当用户改变您 App 的窗口大小时
                //系统会重绘当前的页面, 经测试在某些机型, 某些情况下系统不会重绘当前页面, ScreenUtils.getScreenSize(activity) 的参数一定要不要传 Application!!!
                if (activity.requestedOrientation == ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE) {
                    AutoSizeConfig.getInstance().screenWidth = ScreenUtils.getScreenSize(activity)[1]
                    AutoSizeConfig.getInstance().screenHeight = ScreenUtils.getScreenSize(activity)[0]
                } else {
                    AutoSizeConfig.getInstance().screenWidth = ScreenUtils.getScreenSize(activity)[0]
                    AutoSizeConfig.getInstance().screenHeight = ScreenUtils.getScreenSize(activity)[1]
                }
            }

            override fun onAdaptAfter(target: Any, activity: Activity) {

            }
        }
```

**Comment by liulilei** [comment]
@MyMrXu 这个是在application里面全局配置的吗？

**Comment by wolfking0608** [comment]
如果我一半的页面横屏,一半的页面竖屏,这种情况我该如何处理

**Comment by wolfking0608** [comment]
> > @MyMrXu 这个是在application里面全局配置的吗？
> 
> 是的，横屏的时候，把宽和高对换一下就好了

怎么对换下,有具体方法吗

**Comment by DuShuYuan** [comment]
> 


        AutoSizeConfig.getInstance().onAdaptListener = object : onAdaptListener {
            override fun onAdaptBefore(target: Any, activity: Activity) {
                //使用以下代码, 可支持 Android 的分屏或缩放模式, 但前提是在分屏或缩放模式下当用户改变您 App 的窗口大小时
                //系统会重绘当前的页面, 经测试在某些机型, 某些情况下系统不会重绘当前页面, ScreenUtils.getScreenSize(activity) 的参数一定要不要传 Application!!!
                if (activity.resources.configuration.orientation == Configuration.ORIENTATION_LANDSCAPE) {
                    AutoSizeConfig.getInstance().screenWidth = ScreenUtils.getScreenSize(activity)[1]
                    AutoSizeConfig.getInstance().screenHeight = ScreenUtils.getScreenSize(activity)[0]
                } else {
                    AutoSizeConfig.getInstance().screenWidth = ScreenUtils.getScreenSize(activity)[0]
                    AutoSizeConfig.getInstance().screenHeight = ScreenUtils.getScreenSize(activity)[1]
                }
            }

            override fun onAdaptAfter(target: Any, activity: Activity) {

            }
        }

**Comment by DuShuYuan** [comment]
> > > @MyMrXu 这个是在application里面全局配置的吗？
> > 
> > 
> > 是的，横屏的时候，把宽和高对换一下就好了
> 
> 怎么对换下,有具体方法吗

`
        AutoSizeConfig.getInstance().onAdaptListener = object : onAdaptListener {
            override fun onAdaptBefore(target: Any, activity: Activity) {
                //使用以下代码, 可支持 Android 的分屏或缩放模式, 但前提是在分屏或缩放模式下当用户改变您 App 的窗口大小时
                //系统会重绘当前的页面, 经测试在某些机型, 某些情况下系统不会重绘当前页面, ScreenUtils.getScreenSize(activity) 的参数一定要不要传 Application!!!
                if (activity.resources.configuration.orientation == Configuration.ORIENTATION_LANDSCAPE) {
                    AutoSizeConfig.getInstance().screenWidth = ScreenUtils.getScreenSize(activity)[1]
                    AutoSizeConfig.getInstance().screenHeight = ScreenUtils.getScreenSize(activity)[0]
                } else {
                    AutoSizeConfig.getInstance().screenWidth = ScreenUtils.getScreenSize(activity)[0]
                    AutoSizeConfig.getInstance().screenHeight = ScreenUtils.getScreenSize(activity)[1]
                }
            }

            override fun onAdaptAfter(target: Any, activity: Activity) {

            }
        }`

**Comment by DuShuYuan** [comment]
> > > @MyMrXu 这个是在application里面全局配置的吗？
> > 
> > 
> > 是的，横屏的时候，把宽和高对换一下就好了
> 
> 怎么对换下,有具体方法吗

上面方法无效，activity.requestedOrientation一直是 -1 ，我的方法：
```

        AutoSizeConfig.getInstance().onAdaptListener = object : onAdaptListener {
            override fun onAdaptBefore(target: Any, activity: Activity) {
                //使用以下代码, 可支持 Android 的分屏或缩放模式, 但前提是在分屏或缩放模式下当用户改变您 App 的窗口大小时
                //系统会重绘当前的页面, 经测试在某些机型, 某些情况下系统不会重绘当前页面, ScreenUtils.getScreenSize(activity) 的参数一定要不要传 Application!!!
                if (activity.resources.configuration.orientation == Configuration.ORIENTATION_LANDSCAPE) {
                    AutoSizeConfig.getInstance().screenWidth = ScreenUtils.getScreenSize(activity)[1]
                    AutoSizeConfig.getInstance().screenHeight = ScreenUtils.getScreenSize(activity)[0]
                } else {
                    AutoSizeConfig.getInstance().screenWidth = ScreenUtils.getScreenSize(activity)[0]
                    AutoSizeConfig.getInstance().screenHeight = ScreenUtils.getScreenSize(activity)[1]
                }
            }

            override fun onAdaptAfter(target: Any, activity: Activity) {

            }
        }

```

**Comment by huangjinhu6** [comment]
unsubscribe



在 2021-12-10 16:57:45，"DOPO" ***@***.***> 写道：

    AutoSizeConfig.getInstance().onAdaptListener = object : onAdaptListener {

        override fun onAdaptBefore(target: Any, activity: Activity) {

            //使用以下代码, 可支持 Android 的分屏或缩放模式, 但前提是在分屏或缩放模式下当用户改变您 App 的窗口大小时

            //系统会重绘当前的页面, 经测试在某些机型, 某些情况下系统不会重绘当前页面, ScreenUtils.getScreenSize(activity) 的参数一定要不要传 Application!!!

            if (activity.resources.configuration.orientation == Configuration.ORIENTATION_LANDSCAPE) {

                AutoSizeConfig.getInstance().screenWidth = ScreenUtils.getScreenSize(activity)[1]

                AutoSizeConfig.getInstance().screenHeight = ScreenUtils.getScreenSize(activity)[0]

            } else {

                AutoSizeConfig.getInstance().screenWidth = ScreenUtils.getScreenSize(activity)[0]

                AutoSizeConfig.getInstance().screenHeight = ScreenUtils.getScreenSize(activity)[1]

            }

        }



        override fun onAdaptAfter(target: Any, activity: Activity) {



        }

    }



—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
