### ISSUE TITLE
activity弹出的alertdilog会被放大，而且变成非居中的，靠右侧显示

### ISSUE THREAD

**Issue by fantasy0034** [JessYanCoding/AndroidAutoSize#108]
### Environment
- [x] Autosize Version: 
- [x] Target Android Version: 
- [x] Device Model: 
- [x] Device Resolution: 
- [x] Design Size On AndroidManifest: 

### Log:

```log


```

### Related Code:
```java
  

```

**Comment by JessYanCoding** [comment]
https://github.com/JessYanCoding/AndroidAutoSize/issues/1
