### ISSUE TITLE
8.0fragment适配有问题

### ISSUE THREAD

**Issue by yc654084303** [JessYanCoding/AndroidAutoSize#110]
8.0版本的模拟器测试的：4个fragment菜单，有个webview，第一次进入加载没问题，切换fragment，尤其是点击那个webview fragment，整个页面都乱拉，要切换到activity，然后在点击后有好啦....感觉在切换fragment的时候没有计算。。。。。。 
![image](https://user-images.githubusercontent.com/7903548/50393186-5936eb80-078f-11e9-966a-3ff5cd5908f6.png)
![image](https://user-images.githubusercontent.com/7903548/50393257-dbbfab00-078f-11e9-95f1-7ec1424ddaf5.png)

**Comment by liulilei** [comment]
显示的时候在调一下AutoSize.autoConvertDensityBaseOnWidth  我是这么解决的

**Comment by wmjwmj828** [comment]
@yc654084303 我也有反馈过这个问题   #69 
群主是说要在fragment onResume的时候调用AutoSize.autoConvertDensity，不过我后面好像还有碰到，时间原因就不再验证了

**Comment by JessYanCoding** [comment]
https://github.com/JessYanCoding/AndroidAutoSize/issues/5 https://github.com/JessYanCoding/AndroidAutoSize/issues/13#11
