### ISSUE TITLE
webview显示不完整的情况

### ISSUE THREAD

**Issue by xiaotianzhen** [JessYanCoding/AndroidAutoSize#111]
# #
![cbc2412fdb563472f652fcac4467892](https://user-images.githubusercontent.com/21015465/50436273-05a7d780-0920-11e9-8192-8aa97d332637.png)

**Comment by xiaotianzhen** [comment]
OPPO A77和部分机型，  scrollview 嵌套webview，会出现webview显示不完整的情况

**Comment by JessYanCoding** [comment]
https://github.com/JessYanCoding/AndroidAutoSize/issues/5 https://github.com/JessYanCoding/AndroidAutoSize/issues/13#11
