### ISSUE TITLE
有两个问题

### ISSUE THREAD

**Issue by fmy86305969** [JessYanCoding/AndroidAutoSize#113]
第一个问题：我做的是pad应用 应用是强制横屏全屏 设计图是2048*1536，比例我置.setBaseOnWidth(false)以高度基准,使用副单位，然后界面布局我高度设置1536mm，实际效果高度并没有充满屏幕。后来切换为autosize:1.0.5版本会后再加上.setUseDeviceSize(true)解决。但是autosize:1.1.1版本还是有间隙，我看了源码，ScreenUtils类中有getRawScreenSize和getScreenSize两个方法，前者获取原始的屏幕尺寸，后者是当前的屏幕尺寸，期望有个属性可以设置是否使用屏幕原始的屏幕尺寸为基准。
暂时解决方法我在初始化时重新给mScreenHeight赋值。

第二个问题：就是不能兼容ScrollView 我设置ScrollView 子view高度为3000mm ，但实际子view只有屏幕高度那么高，无法上下拖动。期望效果：能突破屏幕宽高限制 完成ScrollView 中视图也能等比例缩放，上下或左右滑动。
暂时解决方案：取消当前activity适配。

如有更好解决方案麻烦告知下，谢谢。

**Comment by JessYanCoding** [comment]
第一个问题参考这个 https://github.com/JessYanCoding/AndroidAutoSize/issues/116
第二个问题今日头条方案只是修改 density 实现屏幕适配，和具体 View 并没有任何关联
