### ISSUE TITLE
【BUG】全局使用副单位在代码中修改字体变得非常大

### ISSUE THREAD

**Issue by FynnJason** [JessYanCoding/AndroidAutoSize#115]
### Environment
- [x] Autosize Version: 1.1.1
- [x] Target Android Version:
- [x] Device Model: 
- [x] Device Resolution: 
- [x] Design Size On AndroidManifest: 

### Bug Description:
整个项目是使用副单位，在代码中动态使用AutoSizeUtils去修改TextView的大小，会导致字体非常大！例如在xml中我的textview设置为48pt很正常，那么我在代码中设置textview大小textview.setTextSize(AutoSizeUtils.pt2px(getActivity(), 48)); 字体就非常非常大，不知道什么原因。

application中初始化为
AutoSizeConfig.getInstance()
                .getUnitsManager()
                .setSupportDP(false)
                .setSupportSP(false)
                .setSupportSubunits(Subunits.PT);

### Log:

```log

1
```

### Related Code:
```java


```

**Comment by FynnJason** [comment]
经多次测试，注释掉.setSupportSP(false)，也就是还原对sp支持，然后在代码中继续使用pt，textview.setTextSize(AutoSizeUtils.pt2px(getActivity(), 48)); 字体大小就不会变化，很奇怪。

**Comment by FynnJason** [comment]
然而这样将出现系统自带的组件字体变小（Toast），当然这无可厚非，因为没有屏蔽对sp的支持，上面出现的问题应该是一个bug，希望大佬能看一下。

**Comment by JessYanCoding** [comment]
我这里复现不了，都是正常的，你自己断点看看 DisplayMetrics#xdpi 的值是不是正确的，如果不是正确值，考虑可能 DisplayMetrics#xdpi  没被正确设置，或者在你的环境中 DisplayMetrics#xdpi  被恢复了初始状态，这样即可 https://github.com/JessYanCoding/AndroidAutoSize/issues/13#11

**Comment by jeffy5** [comment]
@FynnJason 我也遇到了同样的问题，我猜测是 `setTextSize` 默认使用的是 `sp` 单位，而 `AutoSizeUtils.pt2px` 转换的结果是 `px`。

最后我在 `setTextSize` 时标明使用 `TypedValue.COMPLEX_UNIT_PX` 就显示正常了。

```kotlin
tvTitle.setTextSize(TypedValue.COMPLEX_UNIT_PX,
    AutoSizeUtils.pt2px(context, 24f).toFloat())
```

**Comment by shaobin0604** [comment]
> @FynnJason 我也遇到了同样的问题，我猜测是 `setTextSize` 默认使用的是 `sp` 单位，而 `AutoSizeUtils.pt2px` 转换的结果是 `px`。
> 
> 最后我在 `setTextSize` 时标明使用 `TypedValue.COMPLEX_UNIT_PX` 就显示正常了。
> 
> ```kotlin
> tvTitle.setTextSize(TypedValue.COMPLEX_UNIT_PX,
>     AutoSizeUtils.pt2px(context, 24f).toFloat())
> ```

直接用 `vTitle.setTextSize(TypedValue.COMPLEX_UNIT_PT, 24f)` 是不是就可以了
