### ISSUE TITLE
横屏 虚拟键问题

### ISSUE THREAD

**Issue by liaohuyu** [JessYanCoding/AndroidAutoSize#116]
我的A页面没有隐藏虚拟键，B页面是全屏显示，进入后会自动隐藏虚拟键。那么A跳B后，B页面取到的是适配值要小一个虚拟键的高度。这个有解决办法么

**Comment by liaohuyu** [comment]
AutoSizeConfig.getInstance().setScreenWidth(ScreenUtils.getRawScreenSize(this)[0])，这个可以选择么？这个方法在application里面使用是无效的 。 application.registerComponentCallbacks(new ComponentCallbacks() {
            @Override
            public void onConfigurationChanged(Configuration newConfig) {
                if (newConfig != null) {
                    if (newConfig.fontScale > 0) {
                        mInitScaledDensity =
                                Resources.getSystem().getDisplayMetrics().scaledDensity;
                        LogUtils.d("initScaledDensity = " + mInitScaledDensity + " on ConfigurationChanged");
                    }
                    isVertical = newConfig.orientation == Configuration.ORIENTATION_PORTRAIT;
                    int[] screenSize = ScreenUtils.getScreenSize(application);
                    mScreenWidth = screenSize[0];
                    mScreenHeight = screenSize[1];
                }
            }

            @Override
            public void onLowMemory() {

            }
        });可能是在这里改变了。

**Comment by JessYanCoding** [comment]
```java
setOnAdaptListener(new onAdaptListener() {
                    @Override
                    public void onAdaptBefore(Object target, Activity activity) {
                        //ScreenUtils.getScreenSize(activity) 的参数一定要不要传 Application!!!
//                        AutoSizeConfig.getInstance().setScreenWidth(ScreenUtils.getScreenSize(activity)[0]);
//                        AutoSizeConfig.getInstance().setScreenHeight(ScreenUtils.getScreenSize(activity)[1]);
                        LogUtils.d(String.format(Locale.ENGLISH, "%s onAdaptBefore!", target.getClass().getName()));
                    }
```

每次屏幕适配前，这个监听器都会调用，并且会把当前页面的 target 属性就是当前页面的引用 (Activity 或 Fragment)，你根据不同的页面设置不同的屏幕尺寸，想怎么变就怎么变，根本就不需要我修改任何代码就可以实现比这个复杂几倍的需求
