### ISSUE TITLE
getResource#getDimensionPixelSize的值还有原先的，怎么破

### ISSUE THREAD

**Issue by xiaoxiaScut** [JessYanCoding/AndroidAutoSize#117]
### Environment
- [x] Autosize Version: 
- [x] Target Android Version: 
- [x] Device Model: 
- [x] Device Resolution: 
- [x] Design Size On AndroidManifest: 

### Log:

```log


```

### Related Code:
```java
  

```

**Comment by JessYanCoding** [comment]
我这里不能复现，完全正常，考虑是你的系统或者环境问题，打断点看下 density 是否是正确的值，不是正确的值，试试这个方案 https://github.com/JessYanCoding/AndroidAutoSize/issues/13#11 ，如果还是原始的值将这个原始的值传入 AutoSizeUtils#dp2px 即可转变成 px，副单位的话就使用 AutoSizeUtils 中对应的方法
