### ISSUE TITLE
适配webview

### ISSUE THREAD

**Issue by Gseve** [JessYanCoding/AndroidAutoSize#119]
### Environment
- [x] Autosize Version: 
- [x] Target Android Version: 
- [x] Device Model: 
- [x] Device Resolution: 
- [x] Design Size On AndroidManifest: 

### Log:

```log


```

### Related Code:
```java
  

```

**Comment by JessYanCoding** [comment]
https://github.com/JessYanCoding/AndroidAutoSize/issues/5 https://github.com/JessYanCoding/AndroidAutoSize/issues/13#11
