### ISSUE TITLE
华为荣耀Magic2不适配。AndroidAutoSize会在屏幕顶部空出一块黑色区域，导致剩下的可操作区域小于指定的屏幕宽度

### ISSUE THREAD

**Issue by ChunmingWu** [JessYanCoding/AndroidAutoSize#121]
### Environment
- [x] Autosize Version: 
- [x] Target Android Version: 
- [x] Device Model: 
- [x] Device Resolution: 
- [x] Design Size On AndroidManifest: 

### Log:

```log


```

### Related Code:
```java
  

```

**Comment by Vicent9920** [comment]
### Environment
- [x] Autosize Version: 1.1.2
- [x] Target Android Version: 9.0
- [x] Device Model: 小米8
- [x] Device Resolution: 
- [x] Design Size On AndroidManifest: 


### Bug Description:



### Log:

```log


```


### Screenshot



### Related Code:
```
  <meta-data

  android:name="android.max_aspect"

  android:value="2.1" />

```


### Others:

网上提示是刘海屏的配置，配置了宽高比依然有问题。宽高比设置16/9 = 1.778在小米8有接近一公分的黑块，设置三星S8屏幕的宽高比18.5/9 = 2.056没有黑块了，但是有报错：
![_20190109135446](https://user-images.githubusercontent.com/17283445/50879658-a6b18a80-1416-11e9-9c02-bb966b88021c.jpg)

**Comment by ChunmingWu** [comment]
magic2是真正意义上的全面屏，前边描述有点不对，不只是顶部，在底部也留了黑块。所以这个框架是不是还无法适配全面屏手机呢

**Comment by Vicent9920** [comment]
我解决了这个异常，

> 在Android 7.0以上Google默认支持了分屏模式，即Manifest文件中配置Activity的android:resizeableActivity默认属性为true，在这种情况下并不需要配置Maximum Aspect Ratio即可自动适配全面屏。

解决以后如果遇到下面这个异常，可以参考这个里链接：[Android 9.0异常解决方案](https://blog.csdn.net/shineflowers/article/details/85045117)
`Detected problems with API compatibility(visit g.co/dev/appcompat for more info`

**Comment by ChunmingWu** [comment]
我按照楼上Vicent9920所说的，在Manifest文件中配置Activity的android:resizeableActivity默认属性为true，Magic2成功实现了全屏，并且尺寸无误。谢谢Vicent9920童鞋提供的解决方法。
