### ISSUE TITLE
适配Tip

### ISSUE THREAD

**Issue by BrightVan** [JessYanCoding/AndroidAutoSize#122]
1、由于横屏和分屏的问题，建议横屏情况下，选取小的作为宽度，试过，效果还不错。否则，横屏后，显示的效果会被放大很多（因为长的变成width了）
```
AutoSizeConfig.getInstance().setOnAdaptListener(new onAdaptListener() {
            @Override
            public void onAdaptBefore(Object target, Activity activity) {
                int[] screenSize = ScreenUtils.getScreenSize(activity);
                int width, height;
                int orientation = activity.getResources().getConfiguration().orientation;
                boolean isInMultiWindow = false;
                if (Build.VERSION.SDK_INT >= 24) {
                    isInMultiWindow = activity.isInMultiWindowMode();
                }
                //分屏模式下获取的orientation是看横纵大小比的! 如果横向大于纵向返回就是 
                //横屏，反之就是竖屏。和你手机真实的横竖情况无关。官方文档说了分屏模式会忽略一些配置 
               //信息，但没想到是这么处理的。
                if (isInMultiWindow || orientation != Configuration.ORIENTATION_LANDSCAPE) {
                    width = screenSize[0];
                    height = screenSize[1];
                } else {
                    if (screenSize[0] < screenSize[1]) {
                        width = screenSize[0];
                        height = screenSize[1];
                    } else {
                        width = screenSize[1];
                        height = screenSize[0];
                    }
                }
                AutoSizeConfig.getInstance().setScreenWidth(width);
                AutoSizeConfig.getInstance().setScreenHeight(height);
            }

            @Override
            public void onAdaptAfter(Object target, Activity activity) {

            }
        })
```
2、多进程的情况下，下面的代码要写在AutoSizeConfig.getInstance().xxx之前，如果你需要自定义些什么的话。Demo里写在之后，会导致奔溃。
```
AutoSize.initCompatMultiProcess(this);
```
3、建议作者精简下代码，比如那个string.xml可以删了，autoSizeCompat有很多重复代码，LogUtils命个其他名字（很多项目都会有这个），留一个方法就行了。我说库稍微有点大，不会打我吧。自己原来也实现过，这两天再三考虑后迁移到这个库，主要为了兼容性把，毕竟有些设备没有（比如MIUI的那部分处理），很多问题也处理不到。所以就依赖于社区的力量了。
4、个人觉得，README，开始那么长的一串截图没什么必要，直接说事比较好。

**Comment by JessYanCoding** [comment]
感谢兄弟提的意见，很有意义

关于库的大小，AndroidAutoSize 最初的版本是没这么大的，但是随着用户增长，各式各样的需求不断的提出来，所以框架不断的在扩展迭代，增加了很多功能来满足所有人的需求，所以这也是你上面所提到的社区的力量让框架不断的完善和强大，几乎能满足所有人各式各样的需求，但也无可避免的会增加一些也许你用不到的功能，这也在所难免，很多地方刚开始写死其他代码没这么多，但是后面为了增加扩展性和自由度这代码就会增加几倍

AutoSizeCompat 这里解释下，AutoSizeCompat 是把 AutoSize 中的某些方法的第一个参数从 Activity 改为 Resources，为了兼容一些特殊的问题，并不是重复的代码 ...

你说的其他问题，我会在后面的更新中逐个改善

**Comment by JessYanCoding** [comment]
你第一个横屏下以较小的一方的修改时行不通的，使用这个方案在横屏时宽度上会有间隔，因为实际宽度是大于你所设置的最小宽度，无法填充满屏幕，你可以试试，

**Comment by BrightVan** [comment]
间隔？我是试过的，没看出什么问题。关键是我不设置小的，那效果掺不忍睹啊。目前这样写，看着还行啊。其实，要不是很多界面都加了侧滑返回，导致Windows背景是透明的，我就都强制竖屏了。不是打游戏看视频，谁会横屏用手机。但targetAPi>26后，强制竖屏+Windows背景透明就会崩溃，系统不允许。为了升级targetApi，才适配了下横屏的。

**Comment by JessYanCoding** [comment]
可能页面布局不一样，我就使用你的代码，在 Demo 中的第一个页面测试了，会有很大的间隔
