### ISSUE TITLE
转屏适配问题(版本 1.1.2)

### ISSUE THREAD

**Issue by wanggq654321** [JessYanCoding/AndroidAutoSize#123]
接入版本 1.1.2 后，以宽度适配，测试的布局如下：
<LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:orientation="vertical">

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:gravity="center_vertical"
            android:orientation="horizontal">

            <TextView
                android:layout_width="540mm"
                android:layout_height="400mm"
                android:background="@color/colorAccent"
                android:gravity="center"
                android:text="W-540mm"
                android:textColor="#fff"
                android:textSize="16dp" />

            <TextView
                android:layout_width="540mm"
                android:layout_height="400mm"
                android:background="#0d0"
                android:gravity="center"
                android:text="W-540mm"
                android:textColor="#fff"
                android:textSize="39dp" />
        </LinearLayout>

        <Button
            android:layout_width="1080mm"
            android:layout_height="144mm"
            android:background="#fd0"
            android:onClick="goCustomAdaptActivity"
            android:text="CustomAdapt"
            android:textColor="#0d0"
            android:textSize="16sp" />

        <TextView
            android:layout_width="1080mm"
            android:layout_height="300mm"
            android:background="#d00"
            android:gravity="center"
            android:text="W-1080mm(total:1080mm)"
            android:textColor="#fff"
            android:textSize="16sp" />

        <LinearLayout
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:gravity="center_vertical"
            android:orientation="horizontal">

            <TextView
                android:layout_width="750mm"
                android:layout_height="300mm"
                android:background="@color/colorPrimary"
                android:gravity="center"
                android:text="W-750mm"
                android:textColor="#fff"
                android:textSize="14sp" />

            <TextView
                android:layout_width="2mm"
                android:layout_height="300mm" />

            <TextView
                android:layout_width="328mm"
                android:layout_height="300mm"
                android:background="#d0a"
                android:gravity="center"
                android:text="W-328mm"
                android:textColor="#fff"
                android:textSize="19sp" />
        </LinearLayout>

        <LinearLayout
            android:layout_width="wrap_content"
            android:layout_height="400mm"
            android:orientation="horizontal">

            <TextView
                android:layout_width="360mm"
                android:layout_height="match_parent"
                android:background="#aef"
                android:gravity="center"
                android:text="W-360mm"
                android:textColor="#fff"
                android:textSize="16sp" />

            <TextView
                android:layout_width="270mm"
                android:layout_height="match_parent"
                android:background="#acf"
                android:gravity="center"
                android:text="W-270mm"
                android:textColor="#fff"
                android:textSize="16sp" />

            <TextView
                android:layout_width="450mm"
                android:layout_height="match_parent"
                android:background="#fcf"
                android:gravity="center"
                android:text="W-450mm"
                android:textColor="#fff"
                android:textSize="16sp" />
        </LinearLayout>
    </LinearLayout>

，然后新建AutoSizeActivity，
        <activity
            android:name="com.yxt.toolkits.activity.AutoSizeActivity"
            android:screenOrientation="sensor"
            android:configChanges="orientation|screenSize"
            ></activity>

转屏后，没有按照宽度进行适配

**Comment by wanggq654321** [comment]
<activity
            android:name="com.yxt.toolkits.activity.AutoSizeActivity"
            android:screenOrientation="sensor"
            android:configChanges="orientation|screenSize"
            ></activity> 

-

**Comment by wanggq654321** [comment]
<activity
            android:name="com.yxt.toolkits.activity.AutoSizeActivity"
            android:screenOrientation="sensor"
            android:configChanges="orientation|screenSize"
            ></activity>

**Comment by wanggq654321** [comment]
<activity
            android:name="com.yxt.toolkits.activity.AutoSizeActivity"
            android:screenOrientation="sensor"
            android:configChanges="orientation|screenSize"
            ></activity>

**Comment by wanggq654321** [comment]
<activity
            android:name="com.yxt.toolkits.activity.AutoSizeActivity"
            android:screenOrientation="sensor"
            android:configChanges="orientation|screenSize"
            ></activity>

**Comment by wanggq654321** [comment]
Activity 配置加入如下：
 android:screenOrientation="sensor"
            android:configChanges="orientation|screenSize"

**Comment by wanggq654321** [comment]
![qq 20190110172103](https://user-images.githubusercontent.com/34908932/50958701-4b59c800-14fc-11e9-8c93-925235f47cc8.jpg)

**Comment by wanggq654321** [comment]
public static void autoConvertDensity(Activity activity, float sizeInDp, boolean isBaseOnWidth) {
        Preconditions.checkNotNull(activity, "activity == null");

        boolean isVertical = activity.getResources().getConfiguration().orientation == Configuration.ORIENTATION_PORTRAIT;

        if (isVertical != AutoSizeConfig.getInstance().isVertical()) {
            AutoSizeConfig.getInstance().setVertical(isVertical);
            int[] screenSize = ScreenUtils.getScreenSize(activity.getApplicationContext());
            AutoSizeConfig.getInstance().setScreenWidth(screenSize[0]);
            AutoSizeConfig.getInstance().setScreenHeight(screenSize[1]);
        }

        int screenSize = isBaseOnWidth ? AutoSizeConfig.getInstance().getScreenWidth()
                : AutoSizeConfig.getInstance().getScreenHeight();
        String key = sizeInDp + "|" + isBaseOnWidth + "|"
                + AutoSizeConfig.getInstance().isUseDeviceSize() + "|"
                + AutoSizeConfig.getInstance().getInitScaledDensity() + "|"
                + screenSize;

        DisplayMetricsInfo displayMetricsInfo = mCache.get(key);

        float targetDensity = 0;
        int targetDensityDpi = 0;
        float targetScaledDensity = 0;
        float targetXdpi = 0;

        if (displayMetricsInfo == null) {
            if (isBaseOnWidth) {
                targetDensity = AutoSizeConfig.getInstance().getScreenWidth() * 1.0f / sizeInDp;
            } else {
                targetDensity = AutoSizeConfig.getInstance().getScreenHeight() * 1.0f / sizeInDp;
            }
            targetScaledDensity = targetDensity * (AutoSizeConfig.getInstance().
                    getInitScaledDensity() * 1.0f / AutoSizeConfig.getInstance().getInitDensity());
            targetDensityDpi = (int) (targetDensity * 160);

            if (isBaseOnWidth) {
                targetXdpi = AutoSizeConfig.getInstance().getScreenWidth() * 1.0f / sizeInDp;
            } else {
                targetXdpi = AutoSizeConfig.getInstance().getScreenHeight() * 1.0f / sizeInDp;
            }
            mCache.put(key, new DisplayMetricsInfo(targetDensity, targetDensityDpi, targetScaledDensity, targetXdpi));
        } else {
            targetDensity = displayMetricsInfo.getDensity();
            targetDensityDpi = displayMetricsInfo.getDensityDpi();
            targetScaledDensity = displayMetricsInfo.getScaledDensity();
            targetXdpi = displayMetricsInfo.getXdpi();
        }

        setDensity(activity, targetDensity, targetDensityDpi, targetScaledDensity, targetXdpi);

        LogUtils.d(String.format(Locale.ENGLISH, "The %s has been adapted! \n%s Info: isBaseOnWidth = %s, %s = %f, targetDensity = %f, targetScaledDensity = %f, targetDensityDpi = %d, targetXdpi = %f"
                , activity.getClass().getName(), activity.getClass().getSimpleName(), isBaseOnWidth, isBaseOnWidth ? "designWidthInDp"
                        : "designHeightInDp", sizeInDp, targetDensity, targetScaledDensity, targetDensityDpi, targetXdpi));
    }

**Comment by wanggq654321** [comment]
1.1.2 版本：
  public static void autoConvertDensity(Activity activity, float sizeInDp, boolean isBaseOnWidth) {
        Preconditions.checkNotNull(activity, "activity == null");

        float subunitsDesignSize = isBaseOnWidth ? AutoSizeConfig.getInstance().getUnitsManager().getDesignWidth()
                : AutoSizeConfig.getInstance().getUnitsManager().getDesignHeight();
        subunitsDesignSize = subunitsDesignSize > 0 ? subunitsDesignSize : sizeInDp;

        int screenSize = isBaseOnWidth ? AutoSizeConfig.getInstance().getScreenWidth()
                : AutoSizeConfig.getInstance().getScreenHeight();
        String key = sizeInDp + "|" + subunitsDesignSize + "|" + isBaseOnWidth + "|"
                + AutoSizeConfig.getInstance().isUseDeviceSize() + "|"
                + AutoSizeConfig.getInstance().getInitScaledDensity() + "|"
                + screenSize;

        DisplayMetricsInfo displayMetricsInfo = mCache.get(key);

        float targetDensity = 0;
        int targetDensityDpi = 0;
        float targetScaledDensity = 0;
        float targetXdpi = 0;

        if (displayMetricsInfo == null) {
            if (isBaseOnWidth) {
                targetDensity = AutoSizeConfig.getInstance().getScreenWidth() * 1.0f / sizeInDp;
            } else {
                targetDensity = AutoSizeConfig.getInstance().getScreenHeight() * 1.0f / sizeInDp;
            }
            targetScaledDensity = targetDensity * (AutoSizeConfig.getInstance().
                    getInitScaledDensity() * 1.0f / AutoSizeConfig.getInstance().getInitDensity());
            targetDensityDpi = (int) (targetDensity * 160);

            if (isBaseOnWidth) {
                targetXdpi = AutoSizeConfig.getInstance().getScreenWidth() * 1.0f / subunitsDesignSize;
            } else {
                targetXdpi = AutoSizeConfig.getInstance().getScreenHeight() * 1.0f / subunitsDesignSize;
            }

            mCache.put(key, new DisplayMetricsInfo(targetDensity, targetDensityDpi, targetScaledDensity, targetXdpi));
        } else {
            targetDensity = displayMetricsInfo.getDensity();
            targetDensityDpi = displayMetricsInfo.getDensityDpi();
            targetScaledDensity = displayMetricsInfo.getScaledDensity();
            targetXdpi = displayMetricsInfo.getXdpi();
        }

        setDensity(activity, targetDensity, targetDensityDpi, targetScaledDensity, targetXdpi);

        LogUtils.d(String.format(Locale.ENGLISH, "The %s has been adapted! \n%s Info: isBaseOnWidth = %s, %s = %f, %s = %f, targetDensity = %f, targetScaledDensity = %f, targetDensityDpi = %d, targetXdpi = %f"
                , activity.getClass().getName(), activity.getClass().getSimpleName(), isBaseOnWidth, isBaseOnWidth ? "designWidthInDp"
                        : "designHeightInDp", sizeInDp, isBaseOnWidth ? "designWidthInSubunits" : "designHeightInSubunits", subunitsDesignSize
                , targetDensity, targetScaledDensity, targetDensityDpi, targetXdpi));
    }

**Comment by wanggq654321** [comment]
以上是 对比历史版本，最下面的是新版，看代码是把 屏幕的方向判断给去去掉了，作者能帮看下的吗？

**Comment by JessYanCoding** [comment]
你的意思是上面旧版的代码没问题吗，我取消是为了兼容其他更复杂的画中画、分屏等模式

如果是这个代码引起的，下面的代码应该能解决问题

```java
AutoSizeConfig.getInstance()
                //屏幕适配监听器
                .setOnAdaptListener(new onAdaptListener() {
                    @Override
                    public void onAdaptBefore(Object target, Activity activity) {
                        //使用以下代码, 可支持 Android 的分屏或缩放模式, 但前提是在分屏或缩放模式下当用户改变您 App 的窗口大小时
                        //系统会重绘当前的页面, 经测试在某些机型, 某些情况下系统不会重绘当前页面, ScreenUtils.getScreenSize(activity) 的参数一定要不要传 Application!!!
                        AutoSizeConfig.getInstance().setScreenWidth(ScreenUtils.getScreenSize(activity)[0]);
                        AutoSizeConfig.getInstance().setScreenHeight(ScreenUtils.getScreenSize(activity)[1]);
                    }

                    @Override
                    public void onAdaptAfter(Object target, Activity activity) {
                        
                    }
                });
```

**Comment by wanggq654321** [comment]
你的Demo里 
AutoSizeActivity 的 AndroidManifest.xml 配置加入如下：
android:screenOrientation="sensor"
android:configChanges="orientation|screenSize"

这样能够考虑全面点

**Comment by JessYanCoding** [comment]
android:configChanges="orientation|screenSize"  你的问题就是因为加了这个代码才导致的，加了这个代码之后当前 Activity 不会创建，布局也不会重绘，所以之前的竖屏布局会完全保留下来，竖屏布局在横屏下显示当然会有问题，你要想加上面的代码，那你就需要自己在屏幕切换时重绘布局

**Comment by JessYanCoding** [comment]
不是考虑不到位的问题，上面已经解释了，你操作的这个代码，对于框架的核心原理，根本就不支持，除非你能在切换的时候自己重绘页面

**Comment by littlehuisme** [comment]
@wanggq654321 大哥，有解决不重走生命周期时切换横竖屏的适配问题吗？求教~

**Comment by daixiansen** [comment]
> @wanggq654321 大哥，有解决不重走生命周期时切换横竖屏的适配问题吗？求教~

我这也遇到了这个问题
