### ISSUE TITLE
你好！我用POPUPWINDOW(BASEPOPUP）弹窗时底部有原色区域块！求解决！

### ISSUE THREAD

**Issue by lly7690** [JessYanCoding/AndroidAutoSize#128]
### Environment
- [x] Autosize Version: 1.1.2
- [x] Target Android Version:ANDROID 4.4.2
- [x] Device Model: 华强北工模
- [x] Device Resolution: 1280*800
- [x] Design Size On AndroidManifest: 1280 800

### Bug Description:

弹出POPUPWINDOW时底部有原色区域块

### Log:

```log


```

### Screenshot

![image](https://user-images.githubusercontent.com/17976067/51580760-a201d180-1f00-11e9-8bcd-3e3cd8bdf2bf.png)

### Related Code:
```java
  就引入依赖    在manifest里加入参数

```

**Comment by JessYanCoding** [comment]
你这图片能不能清晰点，完全看不清布局情况...
