### ISSUE TITLE
能否提供全局的关闭适配的方法？

### ISSUE THREAD

**Issue by MirkoWu** [JessYanCoding/AndroidAutoSize#130]
现在的只能使用 实现CancelAdapter接口 来取消适配，能否提供一个全局的动态取消适配的方法。
比如我可以在配置界面动态设置全局的 开启和关闭适配效果，当界面重新创建或者打开新界面就能看到效果。

**Comment by JessYanCoding** [comment]
https://github.com/JessYanCoding/AndroidAutoSize/blob/master/demo/src/main/java/me/jessyan/autosize/demo/MainActivity.java#L66

**Comment by MirkoWu** [comment]
好的，那如果在Application#onCreate 中调用 AutoSizeConfig.getInstance().stop(this); 是不是就相当于没有进行适配，因为我有些逻辑是要在启动前判断 是否需要适配。

**Comment by JessYanCoding** [comment]
对，你看方法上面的注释把，写的很明白，调用这个方法后新创建的页面都不会适配，Application#onCreate 在 App 启动时调用，所以 App 的所有页面都不会适配，想重启就调用 restart

**Comment by MirkoWu** [comment]
ok,谢谢
