### ISSUE TITLE
您好，我想要适配三星tab s4 2560x1600分辨率    只适配横屏怎么设置呀   

### ISSUE THREAD

**Issue by kris-liutao** [JessYanCoding/AndroidAutoSize#132]
### Environment
- [x] Autosize Version: 
- [x] Target Android Version: 
- [x] Device Model: 
- [x] Device Resolution: 
- [x] Design Size On AndroidManifest: 

### Log:

```log


```

### Related Code:
```java
  

```

**Comment by JessYanCoding** [comment]
看文档
