### ISSUE TITLE
小米note pro适配失败

### ISSUE THREAD

**Issue by interfans** [JessYanCoding/AndroidAutoSize#133]
### Environment
- [x] Autosize Version: v1.1.2
- [x] Target Android Version:  Android 7.0
- [x] Device Model:  小米note pro miui9.2.3.0稳定版
- [x] Device Resolution: 1440*2560
- [x] Design Size On AndroidManifest: 330dp*640dp

我使用的是这个项目中提供的demo，使用1.1.2版本适配失败，而1.1.1版本正常
![image](https://user-images.githubusercontent.com/31506972/53776455-1765b680-3f31-11e9-8df3-f39ea2203487.png)

调试发现density没变:
v1.1.2调试截图
![image](https://user-images.githubusercontent.com/31506972/53776569-60b60600-3f31-11e9-9e6b-d007d4123227.png)
Resourse中这个值是正常的
![image](https://user-images.githubusercontent.com/31506972/53776760-fa7db300-3f31-11e9-9c6d-8cdf9c0448db.png)
v1.1.1调试截图正常
![image](https://user-images.githubusercontent.com/31506972/53776610-7e836b00-3f31-11e9-9e7b-313d7c57b4a7.png)

**Comment by wanlixiao** [comment]
@JessYanCoding  大佬帮忙看看吧

**Comment by JessYanCoding** [comment]
https://github.com/JessYanCoding/AndroidAutoSize/issues/13#11

**Comment by wanlixiao** [comment]
我添加了这个，没有效果
![image](https://user-images.githubusercontent.com/31506972/53855406-66cae600-4008-11e9-84ed-592561d71f5c.png)

**Comment by JessYanCoding** [comment]
那你用 v1.1.1吧，上面这个解决方案是最终的解决方案，不行就没办法了

**Comment by yxyaxng** [comment]
遇到同样的问题，小米4s也会出现适配不了，android7.0，一样的系统

**Comment by itgoyo** [comment]
小米手机适配确实`v1.1.1`版本兼容性比较好，但是不能使用`AutoSizeCompat.autoConvertDensity`
```
 @Override
    public Resources getResources() {
        //需要升级到 v1.1.2 及以上版本才能使用 AutoSizeCompat
        AutoSizeCompat.autoConvertDensityOfGlobal((super.getResources());//如果没有自定义需求用这个方法
        AutoSizeCompat.autoConvertDensity((super.getResources(), 667, false);//如果有自定义需求就用这个方法
        return super.getResources();
    }
```
如果在Fragment中也使用`AndroidAutoSize`,在`NoScrollListView`下面从其他页面跳回来，会出现高度被截取一半的情况

**Comment by JessYanCoding** [comment]
```java
 private static void setDensity(Activity activity, float density, int densityDpi, float scaledDensity, float xdpi) {
        DisplayMetrics activityDisplayMetrics = activity.getResources().getDisplayMetrics();
        setDensity(activityDisplayMetrics, density, densityDpi, scaledDensity, xdpi);
        DisplayMetrics appDisplayMetrics = AutoSizeConfig.getInstance().getApplication().getResources().getDisplayMetrics();
        setDensity(appDisplayMetrics, density, densityDpi, scaledDensity, xdpi);
      
        //兼容 MIUI
        DisplayMetrics activityDisplayMetricsOnMIUI = getMetricsOnMiui(activity.getResources());
        DisplayMetrics appDisplayMetricsOnMIUI = getMetricsOnMiui(AutoSizeConfig.getInstance().getApplication().getResources());

        if (activityDisplayMetricsOnMIUI != null) {
            setDensity(activityDisplayMetricsOnMIUI, density, densityDpi, scaledDensity, xdpi);
        } 
        if (appDisplayMetricsOnMIUI != null) {
            setDensity(appDisplayMetricsOnMIUI, density, densityDpi, scaledDensity, xdpi);
        }
    }
```
在 v1.1.2 之前，不管  activityDisplayMetricsOnMIUI 和 appDisplayMetricsOnMIUI 是否为 null，都会给 activityDisplayMetrics  和 appDisplayMetrics 设置 density，在 v1.1.2 后就改成，如果 activityDisplayMetricsOnMIUI 和 appDisplayMetricsOnMIUI 不为 null ，就不给 activityDisplayMetrics  和 appDisplayMetrics 设置 density，有可能是这个问题，可以试试把 v1.1.2 版本中的 setDensity 方法替换成上面的代码

**Comment by JessYanCoding** [comment]
https://github.com/JessYanCoding/AndroidAutoSize/commit/c1a891e4e19a2a2db7b1347852fd3eaed8ba3423
