### ISSUE TITLE
横屏切换问题

### ISSUE THREAD

**Issue by caocaocao** [JessYanCoding/AndroidAutoSize#134]
这段代码有问题，在onConfigurationChanged不应对mScreenWidth、mScreenHeight重新赋值！！！

**Comment by caocaocao** [comment]
![54173369-91131c80-44bc-11e9-9263-1d72df852a3f](https://user-images.githubusercontent.com/11387592/54173575-7a20fa00-44bd-11e9-8379-edb07a3a4502.png)

这段代码有问题，在onConfigurationChanged不应对mScreenWidth、mScreenHeight重新赋值！！！

**Comment by JessYanCoding** [comment]
你觉得不应该赋值，在 [这里](https://github.com/JessYanCoding/AndroidAutoSize/blob/master/demo/src/main/java/me/jessyan/autosize/demo/BaseApplication.java#L73) 修改即可，你认为不能赋值是站在你的需求上，但如果我真的不赋值有会有其他新的问题，影响另外一部分人，所以我设置了一个监听器，在适配生效之前你想修改，屏幕尺寸还是设计图尺寸，都随便你

**Comment by caocaocao** [comment]
我现在就是用的监听器。
但是我还是坚持自己观点，在这里赋值会在切换横屏的时候，给screenWidth设置为手机实际的高度，给screenHeight设置为实际实际的宽度，我认为这种情况这不是一般的情况，输入特殊需求。而screenWidth、screenHeight保持不变才是通用的场景，不应该因为横竖屏就把实际数值给修改了，这导致横屏时的计算结果跟竖屏时的计算结果不一致。比如：1dp不应因为换横屏了，计算出来的大小就不一样了

**Comment by JessYanCoding** [comment]
你对 screenWidth 的理解，有你的道理，我不反对，但我对 screenWidth 的理解，是确实是会随着屏幕的旋转而改变的，所以为什么 SmallestWidth 屏幕适配方案，叫 SmallestWidth (最小宽度) 而不是叫 Width 屏幕适配方案，因为 SmallestWidth 屏幕适配方案，他会忽略掉屏幕的旋转，而始终使用屏幕高度和宽度中较小的值作为宽度，这就和你上面的理念相同，而 Width 就不一样了，他会随着屏幕的旋转而改变，这就是为什么系统参数 DisplayMetrics.widthPixels 在屏幕旋转时获取的屏幕宽度也会改变的原因，上面的赋值代码，我并没有刻意将屏幕的高宽调换，只是同样使用了工具类获取了系统的屏幕参数 DisplayMetrics.widthPixels 更新类框架中保存的值，这是系统告诉我的参数，我并没有做任何更改，所以我觉得我的设计理念没有什么问题

**Comment by caocaocao** [comment]
横竖屏切换后，只触发了onConfigurationChanged，但是并没有触发onActivityCreated，onActivityStarted，所以你代码里的autoConvertDensity代码并没有执行，density还是原来的值（用之前screenWidth计算得到的），我觉得这个”能适配大部分一般需求的使用者“的主要原因。

**Comment by JessYanCoding** [comment]
没有，你可以试试 Demo，屏幕旋转 onActivityCreated 是调用了的，所以屏幕旋转为横屏，布局横向拉伸沾满整个高度，如果 onActivityCreated 没有调用，根本就不会横向拉伸

这才是普通用户需求，你这个真的是特殊需求，现在也没必要纠结这个了，每个人的思想和需求不一样，没必要争个对错，我监听器已经提供出来了，你想要什么需求都可以自行解决

我这框架遇到的 issues 太多了，整理的屏幕适配需求太多了，大数据能告诉我什么需求是普通需求，什么是特殊需求，所以自己心里有个评判就好了，不讨论了

**Comment by caocaocao** [comment]
你建一个空的demo加个打印试下就清楚了。
并且通过onConfigurationChanged来判断screenWidth的变化也是不严谨的，因为如果没有配置            android:configChanges="keyboardHidden|orientation|screenSize"
，是不会走onConfigurationChanged，只会重新onCreate，这时screenWidth也已经改变了。
我并不是为了争个什么，对了来说也没什么好处，只是看到你做的这个有这么多人再用，自己遇到的问题希望他人能避免

**Comment by JessYanCoding** [comment]
写这个代码的时候，我是用断点测试过的，肯定是会走 onActivityCreated 的

你下面说的问题，所以我提供了监听器，来解决更多复杂以及未知的问题

**Comment by caocaocao** [comment]
估计你的测试代码里有fragment吧

**Comment by JessYanCoding** [comment]
... 和 fragment 有关系吗，有 fragment 的场景，和无 fragment 的场景都测试过，都没有问题

**Comment by caocaocao** [comment]
没关系，我刚试了下，都不会走onActivityCreated。就是一个最简单的空工程，加几行打印就出来了。
![image](https://user-images.githubusercontent.com/11387592/54258013-3d780000-459c-11e9-928c-51cf8b143571.png)
![image](https://user-images.githubusercontent.com/11387592/54258033-4ff23980-459c-11e9-8079-68078cb645c3.png)

**Comment by JessYanCoding** [comment]
![image](https://user-images.githubusercontent.com/15711968/54258270-153cd100-459d-11e9-9d69-2e4595e49620.png)

兄弟，你加了 configChanges 怎么可能调用 onActivityCreated...

因为加了这个 Activity 都不会重建，醉了

**Comment by JessYanCoding** [comment]
Activity 不重建 UI 布局根本就不会重绘，不重绘，布局还是不会改变，还是屏幕旋转之前的样子

**Comment by caocaocao** [comment]
看来是理解问题：我把你的意思理解成只要screenWidth变化，对应的适配就需要修改，所以我觉得不合理。
另外加了configChanges，虽然Activity不重建 UI 布局，但是会重新布局和重绘制。

**Comment by JessYanCoding** [comment]
布局的适配效果是否修改，主动权还是在是否重绘上，框架只是修改 density，density 修改了，布局如果不重绘，那适配效果还是不会变化

另外刚测试了下加了 configChanges，Activity 不重建，确实不会重绘当前布局

**Comment by caocaocao** [comment]
实际的横竖屏应用场景，一般activity都会设置configChanges（很少有切换横屏就重新创建activity的，体验不好），这时切换到横屏，通常会在activity的onConfigurationChanged中加载另外一套横屏的布局（比如：股票曲线图、视频全屏），这时候肯定会重新布局；切换到竖屏时，在重新加载竖屏的布局。这种场景应该说是比较常见的。

**Comment by JessYanCoding** [comment]
... 兄弟你说的是自己主动切换并刷新布局啊，我以为你说的是加了 configChanges 后 Activity 会自己重绘之前的布局 ...

这个需求你想怎么操作都行，该提供的扩展方法都提供出来了

**Comment by gg051202** [comment]
> 实际的横竖屏应用场景，一般activity都会设置configChanges（很少有切换横屏就重新创建activity的，体验不好），这时切换到横屏，通常会在activity的onConfigurationChanged中加载另外一套横屏的布局（比如：股票曲线图、视频全屏），这时候肯定会重新布局；切换到竖屏时，在重新加载竖屏的布局。这种场景应该说是比较常见的。

所以请教一下，应该怎么改？我现在碰到了和你一样的问题，一模一样的情况

**Comment by gg051202** [comment]
> ... 兄弟你说的是自己主动切换并刷新布局啊，我以为你说的是加了 configChanges 后 Activity 会自己重绘之前的布局 ...
> 
> 这个需求你想怎么操作都行，该提供的扩展方法都提供出来了

大佬，他说的这种情况应该怎么修改？

**Comment by gg051202** [comment]
> > ... 兄弟你说的是自己主动切换并刷新布局啊，我以为你说的是加了 configChanges 后 Activity 会自己重绘之前的布局 ...
> > 这个需求你想怎么操作都行，该提供的扩展方法都提供出来了
> 
> 大佬，他说的这种情况应该怎么修改？
![image](https://user-images.githubusercontent.com/11501809/60804038-28f4ee80-a1af-11e9-9d80-a4a07691da7f.png)
已找到解决方法，贴上来，将来可能会有人看到 😸

**Comment by caocaocao** [comment]
@gg051202 初始化时记录screenWidth，然后onAdaptBefore中重设屏幕宽度就可以了。
![image](https://user-images.githubusercontent.com/11387592/60955465-7a2deb00-a333-11e9-8185-dcb6c34c2957.png)

**Comment by caocaocao** [comment]
@gg051202 使用上述代码的理由是：这个库中是从applyAdapt->autoConvertDensity->setDensity触发修改density等相关值的，在applyAdapt调用之前会调用onAdaptBefore，所以在onAdaptBefore中给了我们重设screenWidth的机会。
![image](https://user-images.githubusercontent.com/11387592/60958557-232b1480-a339-11e9-84d6-90408650f480.png)

**Comment by xilost** [comment]
@caocaocao 不太理解，onAdaptBefore并没有执行啊。

**Comment by caocaocao** [comment]
这里onAdaptBefore没有执行没有影响，因为虽然onConfigurationChanged对mScreenWidth、mScreenHeight重新赋值了，但是这里并没有去执行applyAdapt，因此并没有修改density的值。
导致density的修改的唯一路径就是从applyAdapt开始，我们只要保证在applyAdapt调用时的所用的mScreenWidth、mScreenHeight值正确就行了，所以在onAdaptBefore设置。

**Comment by ysy1993** [comment]
```java
   @Override
    public void onConfigurationChanged(@NonNull Configuration newConfig) {
        super.onConfigurationChanged(newConfig);
        if (getResources().getConfiguration().orientation == Configuration.ORIENTATION_LANDSCAPE) {  //横屏
            AutoSizeConfig.getInstance().setScreenWidth(getScreenHeight(getContext()));
     
        } else if (getResources().getConfiguration().orientation == Configuration.ORIENTATION_PORTRAIT) {  //竖屏
            AutoSizeConfig.getInstance().setScreenWidth(getScreenWidth(getContext()));
      
        }
    }
```
