### ISSUE TITLE
适配框架在Adapter中出现异常

### ISSUE THREAD

**Issue by itgoyo** [JessYanCoding/AndroidAutoSize#135]
### Environment
- [x] Autosize Version: 1.1.2
- [x] Target Android Version: Android:6.0
- [x] Device Model: Huawei JDN_W09
- [x] Device Resolution: 1080px * 1920px
- [x] Design Size On AndroidManifest: 750pt * 1344pt

### Bug Description:
写好`adapter`的item预览正常，但是在写入Adapter里面之后页面改变了，就是使用相同的`item` xml在activity中预览的时候正常，但是真正在Adapter使用的时候就异常了。

### Screenshot
`应该item布局`
![](https://raw.githubusercontent.com/itgoyo/PicGoRes/master/img/TIM%E5%9B%BE%E7%89%8720190314110945.jpg)

`实际item布局`

![](https://raw.githubusercontent.com/itgoyo/PicGoRes/master/img/TIM%E5%9B%BE%E7%89%8720190314111000.jpg)

### Related Code:
```java
  AutoSizeConfig.getInstance().getUnitsManager().setSupportSubunits(Subunits.PT);
        AutoSizeConfig.getInstance().setExcludeFontScale(true);

```

**Comment by JessYanCoding** [comment]
https://github.com/JessYanCoding/AndroidAutoSize/issues/59
https://github.com/JessYanCoding/AndroidAutoSize/issues/13#11

**Comment by itgoyo** [comment]
好的谢谢，我把字体放大两倍看起来效果好些了。

**Comment by lolkt** [comment]
import com.tencent.smtt.sdk.WebView; 
修改为import android.webkit.WebView;
使用`  @Override
    public void setOverScrollMode(int mode) {
        super.setOverScrollMode(mode);
        AutoSize.autoConvertDensityOfGlobal((Activity) getContext());
    }` 才有效果
