### ISSUE TITLE
在使用主单位时setExcludeFontScale没效果

### ISSUE THREAD

**Issue by Android-xiaole** [JessYanCoding/AndroidAutoSize#136]
### Environment
- [x] Autosize Version: 
- [x] Target Android Version: 
- [x] Device Model: 
- [x] Device Resolution: 
- [x] Design Size On AndroidManifest: 

### Log:

```log

2019-03-15 10:26:00.891 25465-25465/? D/AndroidAutoSize: designWidthInDp = 375, designHeightInDp = 667, screenWidth = 1080, screenHeight = 1920
2019-03-15 10:26:00.892 25465-25465/? D/AndroidAutoSize: initDensity = 3.0, initScaledDensity = 3.8999999
```

### Related Code:
```java
  
 AutoSizeConfig.getInstance()

                //是否让框架支持自定义 Fragment 的适配参数, 由于这个需求是比较少见的, 所以须要使用者手动开启
                //如果没有这个需求建议不开启
                .setCustomFragment(true)

                //是否屏蔽系统字体大小对 AndroidAutoSize 的影响, 如果为 true, App 内的字体的大小将不会跟随系统设置中字体大小的改变
                //如果为 false, 则会跟随系统设置中字体大小的改变, 默认为 false
                .setExcludeFontScale(true)
```

### Others:
在使用dp单位时，无论设置true还是false字体大小都不会随系统设置变化
在使用sp单位时，无论设置true还是false字体大小都会随着系统设置变化

**Comment by Android-xiaole** [comment]
补充：
Autosize Version:v1.1.2
Target Android Version:22
Device Model:Mi A1
Device Resolution:1080*1920
Design Size On AndroidManifest: 375*667

**Comment by JessYanCoding** [comment]
setExcludeFontScale 这个方法只是针对使用 sp 的情况，使用 dp，app 字体不跟随改变系统改变这不是很正常吗，常识把...

使用 sp，这个我是测试过多次了，你可以自己打断点，看是否是其他什么情况导致了，这个属性的失效，比如说多进程

**Comment by qq437125754** [comment]
Fragment里面好像有延时，要等很久刷新数据后字体才会变小。
webview好像无效，字体还是大的
