### ISSUE TITLE
在使用SpannableString  类的时候字体大小该怎么设置

### ISSUE THREAD

**Issue by liang979zhang** [JessYanCoding/AndroidAutoSize#139]
### Environment
- [x] Autosize Version: 
- [x] Target Android Version: 
- [x] Device Model: 
- [x] Device Resolution: 
- [x] Design Size On AndroidManifest: 

### Log:

```log


```

### Related Code:
```java
  

```

**Comment by JessYanCoding** [comment]
https://github.com/JessYanCoding/AndroidAutoSize/blob/master/autosize/src/main/java/me/jessyan/autosize/utils/AutoSizeUtils.java
