### ISSUE TITLE
好像适配之后有些出入

### ISSUE THREAD

**Issue by junchenChow** [JessYanCoding/AndroidAutoSize#14]
### Environment
- [x] Autosize Version:  v0.7.0
- [x] Target Android Version: targetSdkVersion : 27
- [x] Device Model: HuaWei & Samsung
- [x] Device Resolution: 720-1440 & 1440-2560
- [x] Design Size On AndroidManifest: 375dp* 667dp

### Log:

```log
HuaWei
08-22 16:31:45.598 D/AndroidAutoSize: designWidthInDp = 375, designHeightInDp = 667, screenWidth = 720, screenHeight = 1440
08-22 16:31:45.599 D/AndroidAutoSize: initDensity = 2.0, initScaledDensity = 2.0

Samsung
08-22 16:30:50.367 D/AndroidAutoSize: designWidthInDp = 375, designHeightInDp = 667, screenWidth = 1440, screenHeight = 2560
08-22 16:30:50.368 D/AndroidAutoSize: initDensity = 4.0, initScaledDensity = 4.0
```

### Screenshot

![homepage](https://user-images.githubusercontent.com/13553319/44452688-c2fc8880-a629-11e8-82bb-da69f0fb6601.png)

### Related Code:
```java
  <meta-data
            android:name="design_width_in_dp"
            android:value="375" />
        <meta-data
            android:name="design_height_in_dp"
            android:value="667" />

```

### Others:
只填写了清单文件的meta value ，最终出来的效果好像还是有点差别， 截图右边是华为分辨率小的，布局底部空出了一大块

**Comment by JessYanCoding** [comment]
https://github.com/JessYanCoding/AndroidAutoSize/issues/8

**Comment by junchenChow** [comment]
谢谢 看懂了
