### ISSUE TITLE
RecyclerView适配失败

### ISSUE THREAD

**Issue by MarcusKu** [JessYanCoding/AndroidAutoSize#140]
### Environment
- [x] Autosize Version: 
- [x] Target Android Version: 
- [x] Device Model: 
- [x] Device Resolution: 
- [x] Design Size On AndroidManifest: 

### Log:

```log


```

### Related Code:
```java
  

```

**Comment by MarcusKu** [comment]
RecyclerView适配失败

**Comment by JessYanCoding** [comment]
这个问题我回答过多次，在 issues 里面自己找找相同的问题
