### ISSUE TITLE
 app:layout_auto_baseheight="width" AutoLayout 中的这个属性有对应的吗?

### ISSUE THREAD

**Issue by HelloDearWorld** [JessYanCoding/AndroidAutoSize#142]
### Environment
- [x] Autosize Version: 
- [x] Target Android Version: 
- [x] Device Model: 
- [x] Device Resolution: 
- [x] Design Size On AndroidManifest: 

### Log:

```log


```

### Related Code:
```java
  

```

**Comment by JessYanCoding** [comment]
没，因为这个库只能以宽或者高为基准，所以不需要这个属性，默认支持这个功能
