### ISSUE TITLE
react-native中的界面会偶现变形

### ISSUE THREAD

**Issue by linguokun1** [JessYanCoding/AndroidAutoSize#143]
试过cancelAdapter没作用

**Comment by JessYanCoding** [comment]
https://github.com/JessYanCoding/AndroidAutoSize/issues/13#11

**Comment by linguokun1** [comment]
@JessYanCoding 我的这个问题只会在小米手机上出现 好像是react-native在小米手机上会被修改后的DisplayMetrics#density影响

**Comment by JessYanCoding** [comment]
试试副单位

**Comment by linguokun1** [comment]
@JessYanCoding 副单位都是物理单位 不靠谱吧

**Comment by JessYanCoding** [comment]
@linguokun1 靠不靠谱，你先用了再说，即然我敢开发这个单位，那当然是经过优化过后的产物

**Comment by termite262** [comment]
升级QQ
