### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by BrightVan** [JessYanCoding/AndroidAutoSize#144]
建议加个全局控制是否生效的开关。现在越来越多的手机都是大屏了，屏幕也比较长，一般按照宽度适配，会导致有大量留白，界面UI元素也会显示的比较小，加一个开关，可以自行判断并在某些硬件上不启用autoSize，用系统自带的缩放就挺好。

**Comment by JessYanCoding** [comment]
... 这种问题我已经回答第二遍了，框架有这个 API

**Comment by BrightVan** [comment]
1、application里取不到Activity context，不方便在Application#onCreate全局配置
2、AutoSizeConfig.getInstance().stop(this)无效（mi9 MIUI开发版最新，autoSize1.1.2）。难道是巧了，开不开启，看起来效果一样。

**Comment by JessYanCoding** [comment]
1.取消框架效果，有两步，停止框架后续的操作和解除当前的适配效果，解除当前的适配效果必须要使用 Activity，你可以像 MVPArms 一样，用一个全局的方式拿到当前的 Activity，但是 Activity 是必须要传的

2.发现没有效果，就打下断点，看下是 mActivityLifecycleCallbacks 没有被注销，还是当前的 density 没被修改回来
