### ISSUE TITLE
fresco框架加载图片时，图片显示异常

### ISSUE THREAD

**Issue by xingyao1015** [JessYanCoding/AndroidAutoSize#145]
在适配后：
![1](https://user-images.githubusercontent.com/22767918/55313980-be3f6300-549b-11e9-8a09-927392afc823.png)
![2](https://user-images.githubusercontent.com/22767918/55313990-c1d2ea00-549b-11e9-8a7a-54212e344e8b.png)
![3](https://user-images.githubusercontent.com/22767918/55314001-c4cdda80-549b-11e9-843c-6df26b0ec8ca.png)
适配前：
![6](https://user-images.githubusercontent.com/22767918/55314014-ce574280-549b-11e9-878d-96af0892c497.png)
![Uploading 4.png…]()
![Uploading 5.png…]()

**Comment by JessYanCoding** [comment]
你指，图片显示有长条？貌似和框架没什么关系把

**Comment by xingyao1015** [comment]
这个应该就是不兼容的问题啊，我在不用框架适配的时候，就显示正常的啊

**Comment by xingyao1015** [comment]
这两张是上传失败的图片，都是在适配前的展示都是正常的

![4](https://user-images.githubusercontent.com/22767918/55467712-7142c480-5634-11e9-97fe-e9f116bcfd98.png)
![5](https://user-images.githubusercontent.com/22767918/55467725-79026900-5634-11e9-89b0-fded7a5501df.png)

**Comment by JessYanCoding** [comment]
你停止框架 AutoSizeConfig#stop() ，然后在 Activity onCreate 中自己调用 AutoSize #autoConvertDensityOfGlobal 试试

**Comment by JessYanCoding** [comment]
试试不用框架，自行修改 density，不行改 densityDpi，看看

**Comment by cocowobo** [comment]
使用fresco的时候,如果设置了圆角.
 app:roundedCornerRadius="6dp"
那么当图片的宽高不够铺满 view的宽高的时候,
如果你设置的            app:placeholderImageScaleType="你设置的"
不是能够放大图片的参数的话,就会出现上面的朋友出现的问题.
原因是roundedCornerRadius时必然将图片铺满view进行切割圆角的.图片大小不够.就会拉伸异常
推荐设置
      app:placeholderImageScaleType="centerCrop"
来初步解决此问题.centerCrop是放大图片.保留宽高比,让最小的边也充满view.另一条边超出则切割

**Comment by TokenYc** [comment]
有位老兄解决了这个问题,[方法](https://github.com/JessYanCoding/AndroidAutoSize/issues/209)
