### ISSUE TITLE
设计图与布局预览

### ISSUE THREAD

**Issue by liang979zhang** [JessYanCoding/AndroidAutoSize#146]
按照文档中的方法创建了一个模拟器,但是设计图上标注的尺寸是
![image](https://user-images.githubusercontent.com/16227667/55331392-c6ac9380-54c5-11e9-8867-deff47c4ff8d.png)  540*960 单位是db  ,但是我在预览的时候发现,预览的布局是360*640的,那么在设计图上直接取的单位尺寸就没法直接填写,这个怎么搞啊

**Comment by JessYanCoding** [comment]
说明你没创建对，按公式算出的参数，预览就不会有错误

**Comment by ZhanRu** [comment]
> 说明你没创建对，按公式算出的参数，预览就不会有错误

请教公式问题，例如IN单位，教程上的公式是：sqrt(800^2+1280^2)，图片中结果是2202.9，而我实际在Java中运行：Math.sqrt(800^2+1280^2)，结果是39.59。请问2202.9是怎么计算出来的？

**Comment by ZhanRu** [comment]
我用计算器自己手算就是对的，不知道为什么Java运行结果不对...

**Comment by ZhanRu** [comment]
@JessYanCoding 请问预览是要实时启动虚拟机吗？我建了虚拟机后在预览的选择设备的那里看不到我新建的模拟器

**Comment by JessYanCoding** [comment]
只要参数算对了，就没问题
