### ISSUE TITLE
怎么支持px

### ISSUE THREAD

**Issue by wangbang79408854** [JessYanCoding/AndroidAutoSize#147]
### Environment
- [x] Autosize Version: 
- [x] Target Android Version: 
- [x] Device Model: 
- [x] Device Resolution: 
- [x] Design Size On AndroidManifest: 

### Log:

```log


```

### Related Code:
```java
  

```

**Comment by JessYanCoding** [comment]
今日头条方案不支持 px，自己看这个 [原理文章](https://www.jianshu.com/p/55e0fca23b4f)
