### ISSUE TITLE
AutoSizeConfig.getInstance().setCustomFragment(true); 对fragment无效

### ISSUE THREAD

**Issue by chengmenghuiAndroid** [JessYanCoding/AndroidAutoSize#148]
### Environment
- [x] Autosize Version: 
- [x] Target Android Version: 
- [x] Device Model: 
- [x] Device Resolution: 
- [x] Design Size On AndroidManifest: 

### Log:

```log


```

### Related Code:
```java
  

```

**Comment by zhentouman** [comment]
AutoSizeConfig.getInstance().setCustomFragment(true); 对androidx.fragment.app.Fragment无效

**Comment by JessYanCoding** [comment]
描述太少
