### ISSUE TITLE
关于库中类的命名问题。

### ISSUE THREAD

**Issue by Zeng-Ke** [JessYanCoding/AndroidAutoSize#149]
因为库中有一个LogUtils的工具类。而刚好我的项目中也有一个LogUtils的类。所以在开发中，经常一不小心就引用了该库的类。但这不是我想要的，所以能否给该库一些无关类或者不必要暴露的类加上特定前缀，以免影响实际生产环境。

**Comment by JessYanCoding** [comment]
可以，后期考虑改个名字

**Comment by gg051202** [comment]
可以fork一个，自己改一下

**Comment by liyujiang-gzu** [comment]
@JessYanCoding  建议为不需要对外公开的类加上`@RestrictTo(RestrictTo.Scope.LIBRARY)`注解，最好能将其定义为包权限级别而不是`public`，可以有效利用IDE提示进行限制。

**Comment by JessYanCoding** [comment]
@liyujiang-gzu 了解
