### ISSUE TITLE
导航栏出错

### ISSUE THREAD

**Issue by Joey199508** [JessYanCoding/AndroidAutoSize#150]
### Environment
- Autosize Version: v1.1.2 
- Target Android Version: like: Android 8.0
- Device Model: Nexus 6P（模拟器） 和 sumsumg s7
- Device Resolution: like: 都是1440px * 2560px
- Design Size On AndroidManifest: like: 都是360dp * 640dp 

### Bug Description:

使用github第三方库NavigationTabBar 按宽适配Nexus 6P 导航栏宽度高度出错 sumsumg s7正常 
按高适配 s7宽度高度出错  Nexus 6P 正常  取消适配以后没问题 用的NavigationTabBar demo导入implementation 'me.jessyan:autosize:1.1.2' 截图测试别的代码都没改
https://github.com/Devlight/NavigationTabBar

### Log:
**以下AutoSizeConfig.getInstance().setBaseOnWidth(false); s7**
D/AndroidAutoSize: devlight.io.sample.HorizontalNtbActivity used the global configuration.
D/AndroidAutoSize: The devlight.io.sample.HorizontalNtbActivity has been adapted! 
    HorizontalNtbActivity Info: isBaseOnWidth = false, designHeightInDp = 640.000000, designHeightInSubunits = 640.000000, targetDensity = 3.850000, targetScaledDensity = 3.850000, targetDensityDpi = 616, targetXdpi = 3.850000
D/AndroidAutoSize: devlight.io.sample.HorizontalNtbActivity used the global configuration.
D/AndroidAutoSize: The devlight.io.sample.HorizontalNtbActivity has been adapted! 
    HorizontalNtbActivity Info: isBaseOnWidth = false, designHeightInDp = 640.000000, designHeightInSubunits = 640.000000, targetDensity = 3.850000, targetScaledDensity = 3.850000, targetDensityDpi = 616, targetXdpi = 3.850000
D/AndroidAutoSize: devlight.io.sample.HorizontalNtbActivity used the global configuration.
D/AndroidAutoSize: The devlight.io.sample.HorizontalNtbActivity has been adapted! 
    HorizontalNtbActivity Info: isBaseOnWidth = false, designHeightInDp = 640.000000, designHeightInSubunits = 640.000000, targetDensity = 3.850000, targetScaledDensity = 3.850000, targetDensityDpi = 616, targetXdpi = 3.850000
D/AndroidAutoSize: devlight.io.sample.HorizontalNtbActivity used the global configuration.
D/AndroidAutoSize: The devlight.io.sample.HorizontalNtbActivity has been adapted! 
    HorizontalNtbActivity Info: isBaseOnWidth = false, designHeightInDp = 640.000000, designHeightInSubunits = 640.000000, targetDensity = 3.850000, targetScaledDensity = 3.850000, targetDensityDpi = 616, targetXdpi = 3.850000

**以下AutoSizeConfig.getInstance().setBaseOnWidth(false);nexus 6p**
D/AndroidAutoSize: designWidthInDp = 360, designHeightInDp = 640, screenWidth = 1440, screenHeight = 2392
D/AndroidAutoSize: initDensity = 3.5, initScaledDensity = 3.5
D/AndroidAutoSize: devlight.io.sample.MainActivity used the global configuration.
D/AndroidAutoSize: The devlight.io.sample.MainActivity has been adapted! 
    MainActivity Info: isBaseOnWidth = true, designWidthInDp = 360.000000, designWidthInSubunits = 360.000000, targetDensity = 4.000000, targetScaledDensity = 4.000000, targetDensityDpi = 640, targetXdpi = 4.000000
D/AndroidAutoSize: devlight.io.sample.MainActivity used the global configuration.
D/AndroidAutoSize: The devlight.io.sample.MainActivity has been adapted! 
    MainActivity Info: isBaseOnWidth = true, designWidthInDp = 360.000000, designWidthInSubunits = 360.000000, targetDensity = 4.000000, targetScaledDensity = 4.000000, targetDensityDpi = 640, targetXdpi = 4.000000

D/AndroidAutoSize: devlight.io.sample.HorizontalNtbActivity used the global configuration.
D/AndroidAutoSize: The devlight.io.sample.HorizontalNtbActivity has been adapted! 
    HorizontalNtbActivity Info: isBaseOnWidth = false, designHeightInDp = 640.000000, designHeightInSubunits = 640.000000, targetDensity = 3.606250, targetScaledDensity = 3.606250, targetDensityDpi = 577, targetXdpi = 3.606250
D/AndroidAutoSize: devlight.io.sample.HorizontalNtbActivity used the global configuration.
D/AndroidAutoSize: The devlight.io.sample.HorizontalNtbActivity has been adapted! 
    HorizontalNtbActivity Info: isBaseOnWidth = false, designHeightInDp = 640.000000, designHeightInSubunits = 640.000000, targetDensity = 3.606250, targetScaledDensity = 3.606250, targetDensityDpi = 577, targetXdpi = 3.606250

**以下AutoSizeConfig.getInstance().setBaseOnWidth(true);nexus 6p**
D/AndroidAutoSize: designWidthInDp = 0, designHeightInDp = 0, screenWidth = 1440, screenHeight = 2392
    initDensity = 3.5, initScaledDensity = 3.5
D/AndroidAutoSize: devlight.io.sample.MainActivity used the global configuration.
D/AndroidAutoSize: The devlight.io.sample.MainActivity has been adapted! 
    MainActivity Info: isBaseOnWidth = true, designWidthInDp = 360.000000, designWidthInSubunits = 360.000000, targetDensity = 4.000000, targetScaledDensity = 4.000000, targetDensityDpi = 640, targetXdpi = 4.000000
D/AndroidAutoSize: devlight.io.sample.MainActivity used the global configuration.
D/AndroidAutoSize: The devlight.io.sample.MainActivity has been adapted! 
    MainActivity Info: isBaseOnWidth = true, designWidthInDp = 360.000000, designWidthInSubunits = 360.000000, targetDensity = 4.000000, targetScaledDensity = 4.000000, targetDensityDpi = 640, targetXdpi = 4.000000

D/AndroidAutoSize: devlight.io.sample.HorizontalNtbActivity used the global configuration.
D/AndroidAutoSize: The devlight.io.sample.HorizontalNtbActivity has been adapted! 
    HorizontalNtbActivity Info: isBaseOnWidth = true, designWidthInDp = 360.000000, designWidthInSubunits = 360.000000, targetDensity = 4.000000, targetScaledDensity = 4.000000, targetDensityDpi = 640, targetXdpi = 4.000000
D/AndroidAutoSize: devlight.io.sample.HorizontalNtbActivity used the global configuration.
D/AndroidAutoSize: The devlight.io.sample.HorizontalNtbActivity has been adapted! 

**以下AutoSizeConfig.getInstance().setBaseOnWidth(true);samsumg s7**
D/AndroidAutoSize: designWidthInDp = 360, designHeightInDp = 640, screenWidth = 1440, screenHeight = 2560
    initDensity = 4.0, initScaledDensity = 4.0
D/AndroidAutoSize: devlight.io.sample.MainActivity used the global configuration.
D/AndroidAutoSize: The devlight.io.sample.MainActivity has been adapted! 
    MainActivity Info: isBaseOnWidth = true, designWidthInDp = 360.000000, designWidthInSubunits = 360.000000, targetDensity = 4.000000, targetScaledDensity = 4.000000, targetDensityDpi = 640, targetXdpi = 4.000000
D/AndroidAutoSize: devlight.io.sample.MainActivity used the global configuration.
D/AndroidAutoSize: The devlight.io.sample.MainActivity has been adapted! 
    MainActivity Info: isBaseOnWidth = true, designWidthInDp = 360.000000, designWidthInSubunits = 360.000000, targetDensity = 4.000000, targetScaledDensity = 4.000000, targetDensityDpi = 640, targetXdpi = 4.000000
D/AndroidAutoSize: devlight.io.sample.HorizontalNtbActivity used the global configuration.
D/AndroidAutoSize: The devlight.io.sample.HorizontalNtbActivity has been adapted! 
    HorizontalNtbActivity Info: isBaseOnWidth = true, designWidthInDp = 360.000000, designWidthInSubunits = 360.000000, targetDensity = 4.000000, targetScaledDensity = 4.000000, targetDensityDpi = 640, targetXdpi = 4.000000
D/AndroidAutoSize: devlight.io.sample.HorizontalNtbActivity used the global configuration.
D/AndroidAutoSize: The devlight.io.sample.HorizontalNtbActivity has been adapted! 
    HorizontalNtbActivity Info: isBaseOnWidth = true, designWidthInDp = 360.000000, designWidthInSubunits = 360.000000, targetDensity = 4.000000, targetScaledDensity = 4.000000, targetDensityDpi = 640, targetXdpi = 4.000000

### Screenshot
AutoSizeConfig.getInstance().setBaseOnWidth(false); 在Samsung s7上效果 导航栏底部一丝白 和最右边都有白条 只是导航栏出问题 别的没问题 最右边都有白条可以理解 但是导航栏底部一丝不知道为什么
![20190411_113836](https://user-images.githubusercontent.com/27610354/55971220-05bdb000-5c4f-11e9-9349-2bb6aa34c69f.jpg)

AutoSizeConfig.getInstance().setBaseOnWidth(false); 在nexus 6p上效果 全部没问
![image](https://user-images.githubusercontent.com/27610354/55971491-985e4f00-5c4f-11e9-84ce-46b840c89c69.png)

 AutoSizeConfig.getInstance().setBaseOnWidth(true);在nexus 6p上效果 导航栏顶出 为什么按宽度适配宽度还顶出？
![image](https://user-images.githubusercontent.com/27610354/55972068-c09a7d80-5c50-11e9-9257-4d6f33b8436b.png)
AutoSizeConfig.getInstance().setBaseOnWidth(true);s7上效果 全部没问题 如图2 就不发了

### Related Code:
https://github.com/Devlight/NavigationTabBar

**Comment by JessYanCoding** [comment]
https://mp.weixin.qq.com/s/SDHL26XgIjjlK-RLd_SSCw

**Comment by JessYanCoding** [comment]
上面文章中的配图加上之前我 [原理文章](https://juejin.im/post/5b7a29736fb9a019d53e7ee2) 中的算法，你可以自己算下这些设备的 Density，如果 App 中取得的实际 Density 是正确的值，那就不是框架的问题，这个可能和他框架的布局有关，框架只有一个使命，那就是保证 Density 是正确的值

**Comment by Joey199508** [comment]
好吧 还有问一下原来写的 dp 转px函数是不是也要修改 如果用了auto四则
 public static int dip2px(Context context, float dpValue) {


        final float scale = context.getResources().getDisplayMetrics().density;
      //  Log.d("aaa1", "" + scale );
        return (int) (dpValue * scale + 0.5f) ;
    }


    public static int px2dip(Context context, float pxValue) {
        final float scale = context.getResources().getDisplayMetrics().density;
        return (int) (pxValue / scale + 0.5f);
    }

**Comment by Joey199508** [comment]
已经我还发现一个问题 就是如果有启动页面 加了autosize 启动界面结束之前 如果设备不是360*640dp <meta-data
            android:name="design_width_in_dp"
            android:value="360"/>
        <meta-data
            android:name="design_height_in_dp"
            android:value="640"/>
会出现启动页图片放大缩小（一次 如果是360*640dp的设备就不会 别的都会）的情况 我猜是autosize 就在这时改了density 也就是是在启动页结束之前改的 没法应用到启动页刚开始启动的情况 ：启动页如下设置
 <style name="Theme.Center" parent="AppTheme">
        <item name="android:windowFullscreen">true</item>
        <item name="windowNoTitle">true</item>
        <item name="android:windowBackground">@drawable/splash_icon</item>
    </style>

<activity
            android:name=".Main2Activity"
            android:theme="@style/Theme.Center">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>

**Comment by Joey199508** [comment]
三个我都找到解决方案了 dp2px 单位转换  AutoSizeUtils()类里 dp2px 不行会差一点
******************************
public static int dp2px(Context context, float value) {
        return (int) (TypedValue.applyDimension(TypedValue.COMPLEX_UNIT_DIP, value, context.getResources().getDisplayMetrics()) + 0.5f);
    }
************************************
要用隔壁andriodutilcode  dp2px才行 因为我的程序涉及到同一张图片剪裁成两段再拼接 所以出错一点点特别明显 感觉就是少乘一个density
************************************
 public static int dp2px(final float dpValue) {
        final float scale = Resources.getSystem().getDisplayMetrics().density;
        return (int) (dpValue * scale + 0.5f);
    }
*********************


然后第三方库那个问题在andriodutilcode 的以前版本的方案 解决良好  小白一个 刚学安卓一个月 也不知道为什么 反正用了好像没问题 
https://blog.csdn.net/jun5753/article/details/81353685?utm_source=blogxgwz5
******************************************
 public static void adaptScreen4VerticalSlide(final Activity activity,
                                                 final int designWidthInDp) {
        adaptScreen(activity, designWidthInDp, true);
    }

    /**
     * Adapt the screen for horizontal slide.
     *
     * @param designHeightInDp The size of design diagram's height, in dp,
     *                         e.g. the design diagram height is 1080px, in XXHDPI device,
     *                         the designHeightInDp = 1080 / 3.
     */
    public static void adaptScreen4HorizontalSlide(final Activity activity,
                                                   final int designHeightInDp) {
        adaptScreen(activity, designHeightInDp, false);
    }

    /**
     * Cancel adapt the screen.
     *
     * @param activity The activity.
     */
    public static void cancelAdaptScreen(final Activity activity) {
        final DisplayMetrics appDm = Utils.getApp().getResources().getDisplayMetrics();
        final DisplayMetrics activityDm = activity.getResources().getDisplayMetrics();
        activityDm.density = appDm.density;
        activityDm.scaledDensity = appDm.scaledDensity;
        activityDm.densityDpi = appDm.densityDpi;
    }
**********************************************************
然后开机图片那个问题 我的解决方案是不要居中图片 用ps加一个360*640比例底色 然后bitmap直接拉伸fill到全屏 就不会出现缩放 如果手机屏幕不是360*640 可能有些变形 但是也没办法

**Comment by JessYanCoding** [comment]
1. splash 的问题，可能是 autosize 为了优化启动速度，所以解析 manifest 用的是异步线程，导致 splash 启动时设计图尺寸没有读取到。在 splash setContentView 之前 AutoSizeConfig#setDesignWidthInDp 即可。

2. AutoSizeUtils 中的 dp2px 是使用的修改后的 density，而 andriodutilcode 使用的是修改前的 density，前者能使用适配的功能，后者则不能，也不是说这两个方法中的就一定有一个方法是错的，只是你的需求不一样，所以要选择的方法不一样。

3.你说的适配三方库问题，andriodutilcode  可以通过 cancelAdaptScreen 来解决，但你可能对 autosize 不熟悉，autosize 可以通过三种方式来解决

1.给这个三方库的页面设置一个正确设计图尺寸。
2.和 andriodutilcode 一样取消适配。
3.副单位

这个在之前的文章中，我都介绍过。

4. 你的 issues 写的很详细，但是感觉逻辑有一点错乱，让我看的有一点头痛，这个可以建议你优化下，问问题的逻辑思维好，也可以影响你的写作思维

**Comment by Joey199508** [comment]
好的 感谢指点  ！
“andriodutilcode 使用的是修改前的 density”，原来是这样。。。
目前我自己是用 andriodutilcode的 dp2px  然后再加  autosize 适配没什么问题。
冲突的话 目前我是autosize 取消有问题的适配   然后用andriodutilcode的   两个都挺灵活的 两个用起来也不冲突

最后还是感谢作者呀 让适配变得如此简单。

**Comment by JessYanCoding** [comment]
其实 [AutoSize](https://github.com/JessYanCoding/AndroidAutoSize/blob/master/autosize/src/main/java/me/jessyan/autosize/AutoSize.java) 类中就有和 andriodutilcode  类似的所有方法，也可以像工具类一样使用
