### ISSUE TITLE
isBaseOnWidth 以宽和以高度为基准，高度大小不一样，这个怎么解决

### ISSUE THREAD

**Issue by jpl123** [JessYanCoding/AndroidAutoSize#151]
@JessYanCoding 
![QQ截图20190416154150](https://user-images.githubusercontent.com/12421800/56191658-55411900-605f-11e9-9a07-0c6a09ed04cb.png)

isBaseOnWidth 以宽和以高度为基准，高度大小不一样，这样也就存在一个问题，默认以宽度为基准时，高度比以高度为基准时的要小(以高度为基准时高度正确）。这个怎么解决，是因为只能以一个基准引起的？

**Comment by JessYanCoding** [comment]
https://mp.weixin.qq.com/s/SDHL26XgIjjlK-RLd_SSCw  ，这问题回答过多次了，常见 issues 中也有，这本来就是 今日头条方案 的特性
