### ISSUE TITLE
一加5t手机9.0 Android9.0系统和8.0系统显示不一样，9.0系统显示不正常

### ISSUE THREAD

**Issue by moujunqiang** [JessYanCoding/AndroidAutoSize#153]
一加5t手机9.0 Android9.0系统和8.0系统显示不一样，9.0系统显示不正常，8.0系统的显示正常，同一个型号的手机

**Comment by JessYanCoding** [comment]
图

**Comment by moujunqiang** [comment]
![微信图片_20190424184850](https://user-images.githubusercontent.com/22389682/56654038-a4bbc080-66c1-11e9-9dc9-6d605a001995.jpg)

**Comment by JessYanCoding** [comment]
如果你指的是两个设备宽度一样，但高度有差别，这就是对的，这就是这个框架的特性，https://mp.weixin.qq.com/s/SDHL26XgIjjlK-RLd_SSCw

**Comment by moujunqiang** [comment]
两个设备是统一厂商统一型号的，只是Android系统一个是9.0 一个是8.0出现的这种问题

**Comment by JessYanCoding** [comment]
所以让你看文章，DPI 区别于 PPI 是软件上的概念，哪怕是设备屏幕一样，操作系统不一样，DPI 也可能不一样

**Comment by moujunqiang** [comment]
我这个是以高度为基准的，但是出现的高度确实不一样的

**Comment by JessYanCoding** [comment]
看下这篇 [文章](https://www.jianshu.com/p/55e0fca23b4f)，自己计算下 density 是否是正确的

**Comment by moujunqiang** [comment]
这个我计算验证了一下是正确的。而且我通过adb命令打印了一下两个手机的信息，dpi  分辨率 还有aotusize的日志显示都是一样的

**Comment by JessYanCoding** [comment]
density 正确，说明框架是完成了自己的所有操作的，那有可能是你布局的问题了

**Comment by protectedMan** [comment]
持续关注
