### ISSUE TITLE
系统设置--显示--显示大小（修改显示大小），造成我们适配失效

### ISSUE THREAD

**Issue by siliconvallley** [JessYanCoding/AndroidAutoSize#154]
### Environment
- [x] Autosize Version: 1.1.2
- [x] Target Android Version:26 
- [x] Device Model: 所有可以在设置中修改显示大小的手机
- [x] Device Resolution: 1080*1920
- [x] Design Size On AndroidManifest:360*640 

### Log:

```log


```

### Screenshot

系统设置--显示--修改显示大小截图
![IMG_0093](https://user-images.githubusercontent.com/18340690/56704963-b644ad00-6741-11e9-8153-c50004076175.JPG)
![Uploading IMG_0093.JPG…]()

修改显示大小之后的正常、异常情况对比
![IMG_0091](https://user-images.githubusercontent.com/18340690/56704968-b8a70700-6741-11e9-9d25-6495e24a625b.JPG)
![IMG_0092](https://user-images.githubusercontent.com/18340690/56704971-ba70ca80-6741-11e9-9e7f-c532f381175f.JPG)

### Related Code:
```java
  

```
### Others:
可以看下具体是什么问题嘛，老铁
@JessYanCoding

**Comment by JessYanCoding** [comment]
AutoSizeConfig.getInstance().setExcludeFontScale(true);

**Comment by JessYanCoding** [comment]
https://mp.weixin.qq.com/s/SDHL26XgIjjlK-RLd_SSCw

**Comment by siliconvallley** [comment]
老铁，第一张截图修改显示大小，不是修改字体大小，是全局修改手机中所有应用的显示尺寸，你可以在手机中试一下效果，dialog我没有固定高度（用的wrap_content），手机中默认的显示尺寸是没有问题的，只要修改为某些尺寸就会出现上述的问题。就像手机高度短了一截，然后把dialog下半部分遮住的感觉
AutoSizeConfig.getInstance().setExcludeFontScale(true);这个设置字体不受影响，我试了没有效果

**Comment by siliconvallley** [comment]
@JessYanCoding

**Comment by JessYanCoding** [comment]
我就是测试了 显示大小，发现即使修改显示大小，字体大小中的 scaledDensity 也会改变，所以才让你 setExcludeFontScale(true);，另外修改显示大小还会改变 density 和 densityDpi，所以所有 View 的大小都会改变，只要 setExcludeFontScale(true);，AndroidAutoSize 就能保证不管你怎么修改显示大小 scaledDensity、density、densityDpi 都不改变。

但是，dialog 你如果不固定的高度的话，AndroidAutoSize 是无效的，AndroidAutoSize 只对有设定了固定长度的 View 有效

**Comment by siliconvallley** [comment]
@JessYanCoding 谢了，老铁 
我的dialog就是不固定高度的，我试了下在inflater.inflate之前取消适配，show之后还原适配，可以解决这个问题，就是dialog没有适配了，哈哈，想想比看不到要稍微好点

**Comment by JessYanCoding** [comment]
之前回答过 dialog 的问题，也就三个方案，第一个就是上面你说的取消适配，第二个自定义 dialog 填写精确的 size，第三个就是使用副单位，这个看你自己，都可以解决这个问题

**Comment by lwc24** [comment]
@JessYanCoding 大佬 我这边更改显示大小与实际变化相反，显示大小为小时屏幕中ui显示变大了，显示为小时，屏幕中的UI变大了；这个有遇到吗？
