### ISSUE TITLE
适配显示问题

### ISSUE THREAD

**Issue by sceneren** [JessYanCoding/AndroidAutoSize#155]
### Environment
- [x] Autosize Version: 1.1.2
- [x] Target Android Version: 28
- [x] Device Model: 小米4C, pixel xl
- [x] Device Resolution:1080*1920,1440 * 2560
- [x] Design Size On AndroidManifest:414*736

### Bug Description:
适配显示问题
### Log:

![image](https://user-images.githubusercontent.com/6612998/56797146-9b0f9580-6846-11e9-943c-9c78cea58885.png)

### Screenshot

![image](https://user-images.githubusercontent.com/6612998/56796106-71ee0580-6844-11e9-9237-f42b2436b1a4.png)
![image](https://user-images.githubusercontent.com/6612998/56796138-7ca89a80-6844-11e9-8683-5c8b6263ffc3.png)
![image](https://user-images.githubusercontent.com/6612998/56796161-86ca9900-6844-11e9-93d6-f897a5ab0569.png)
![image](https://user-images.githubusercontent.com/6612998/56796249-ba0d2800-6844-11e9-84c1-9315c1a94163.png)
大概代码就是上面那些要实现的效果
![image](https://user-images.githubusercontent.com/6612998/56796281-cbeecb00-6844-11e9-8879-537edfe515bf.png)
然后在小米4c上的效果：
![image](https://user-images.githubusercontent.com/6612998/56796360-f6d91f00-6844-11e9-9be0-63ea6cd53600.png)
pixel xl效果：
![image](https://user-images.githubusercontent.com/6612998/56796455-2425cd00-6845-11e9-93e3-ec84043848c2.png)
按理说效果是宽度刚好填满 但是效果却不是这样的。已经超出了手机的宽度

**Comment by sceneren** [comment]
同[#113](https://github.com/JessYanCoding/AndroidAutoSize/issues/133)
目前暂时改为1.1.1 暂时解决

**Comment by JessYanCoding** [comment]
就小米有问题吧，pixel xl 貌似没问题

**Comment by sceneren** [comment]
华为手机也发现这个问题的

**Comment by DeveloperHu** [comment]
@JessYanCoding @sceneren 确实我的小米4c就是适配不了 用小米5x 一加6t都能适配 改变autiosize版本位1.1.1时能适配 先用1.1.1了 搞了我一下午 = =

**Comment by JessYanCoding** [comment]
@DeveloperHu 后面会解决
