### ISSUE TITLE
recyclerview 图片展示问题

### ISSUE THREAD

**Issue by litaoyuan** [JessYanCoding/AndroidAutoSize#156]
### Environment
- [x] Autosize Version: 
- [x] Target Android Version: 
- [x] Device Model: 
- [x] Device Resolution: 
- [x] Design Size On AndroidManifest: 

### Log:

```log


```

### Related Code:
```java
  

```

### Others:
在recyclerview 列表显示，有的图片展示问题，接入框架版本1.1.2

**Comment by litaoyuan** [comment]
![84BE9026531ED0DA60828E6F9A75A797](https://user-images.githubusercontent.com/16474407/57187827-7fcc1680-6f27-11e9-8aad-2c7634cf9c7b.jpg)

**Comment by litaoyuan** [comment]
在activity 里面也申明了
    @Override
    public Resources getResources() {
        //需要升级到 v1.1.2 及以上版本才能使用 AutoSizeCompat
        AutoSizeCompat.autoConvertDensityOfGlobal((super.getResources()));//如果没有自定义需求用这个方法
//        AutoSizeCompat.autoConvertDensity((super.getResources(), 667, false);//如果有自定义需求就用这个方法
        return super.getResources();
    }

**Comment by JessYanCoding** [comment]
哪里有问题，我看大小一致啊？

**Comment by litaoyuan** [comment]
本来圆角图片都是8dp 有的图片变形了，如果去掉适配就没有问题

**Comment by litaoyuan** [comment]
![图片](https://user-images.githubusercontent.com/16474407/57282734-3a067e00-70e0-11e9-89bc-509cb97579f0.jpg)
这个是正确图片

**Comment by JessYanCoding** [comment]
可能是修改 densityDpi 导致，你自己找个工具类，只修改 density，不修改 densityDpi

**Comment by litaoyuan** [comment]
对了，这个问题好像只出现在全面屏上，其他手机都好的

**Comment by litaoyuan** [comment]
![2](https://user-images.githubusercontent.com/16474407/57287563-60c9b200-70ea-11e9-8a42-d5fd86984a97.png)
![1](https://user-images.githubusercontent.com/16474407/57287565-61624880-70ea-11e9-9850-15bb8d0521c2.png)
取消了适配，图片还是有问题

**Comment by JessYanCoding** [comment]
上面说了可能是 densityDpi 修改的问题，按上面说的做

**Comment by litaoyuan** [comment]
![24E854A1D9B45DDEB58929DED41D50E0](https://user-images.githubusercontent.com/16474407/57292681-f9652f80-70f4-11e9-8aca-b2d8f39a8e0d.png)
![782A0DA9B57D3DF262AF322C0913CE5A](https://user-images.githubusercontent.com/16474407/57292683-f9fdc600-70f4-11e9-886f-b7dd003e1d60.png)
设置了大小还是变形的

**Comment by JessYanCoding** [comment]
。。。让你去掉 AndroidAutoSize，找一个今日头条的工具类，修改一下里面的代码，只让它修改 density，不修改 densityDpi，能明白我的意思吗。。。

**Comment by litaoyuan** [comment]
![8968D7CD-1CEF-4294-B11F-CE9EDF61F956](https://user-images.githubusercontent.com/16474407/57295715-b196d600-70fd-11e9-9f80-746a8a6a9457.png)
![C0902AEE-19AA-4EEA-92A7-3AC7FD112B56](https://user-images.githubusercontent.com/16474407/57295717-b22f6c80-70fd-11e9-8a92-a6b947f3cc24.png)
![Screenshot_20190507-192135](https://user-images.githubusercontent.com/16474407/57295718-b22f6c80-70fd-11e9-8e01-7e484670f5ab.jpg)
用了今日头条的适配，去掉了dpi 适配是成功的

**Comment by JessYanCoding** [comment]
和我的猜的差不多，但是没有修改 dpi，可能会影响到切图文件的的选择

**Comment by JessYanCoding** [comment]
继续修改 dpi，调整下 drawable 等切图文件应该也可以解决你的问题

**Comment by litaoyuan** [comment]
图片都是网络获取的,而且我本地图片只有xxh

**Comment by litaoyuan** [comment]
如果我把dpi 去掉，会产生什么效果呢

**Comment by litaoyuan** [comment]
有没有什么好的办法解决呢

**Comment by JessYanCoding** [comment]
要不是就不修改 dpi，要不就要调整下图片的大小了

**Comment by litaoyuan** [comment]
dpi只会影响到不同分辨率下的图片吧，其他不影响吧

**Comment by JessYanCoding** [comment]
那上面不是做了测试吗，去掉 dpi 就适配成功了
不然是什么问题？
