### ISSUE TITLE
集成Autosize状态栏问题

### ISSUE THREAD

**Issue by q1170541047** [JessYanCoding/AndroidAutoSize#157]
集成Autosize后状态栏与布局重叠，小米4没问题华为荣耀10有问题。

**Comment by JessYanCoding** [comment]
图？

**Comment by q1170541047** [comment]
集成Autosize之后immersionbar的解决重叠属性一直不生效，应该是immersionbar问题，已经曲线救国方式解决了

**Comment by JessYanCoding** [comment]
好的，貌似 immersionbar 提供了解决方案。
