### ISSUE TITLE
自己写的状态栏，代码里设置高度之后比不用适配的时候要稍微高一些

### ISSUE THREAD

**Issue by Tonygf** [JessYanCoding/AndroidAutoSize#158]
状态栏是我在布局里写的，高度实在创建的时候手动设置的。
        statusBar = topbarView.findViewById(R.id.statusBar);
        ViewGroup.LayoutParams params = statusBar.getLayoutParams();
        params.height = getStatusBarHeight(context);
        statusBar.setLayoutParams(params);
通过getStatusBarHeight方法，适配之前和适配之后获取的高度都是83，但是设置高度之后，适配之前和原来的高度是一样的，适配之后的高度就要比原来的要高一些。

适配之前：
![image](https://user-images.githubusercontent.com/17547942/57291583-501d3a00-70f2-11e9-95fb-8b6b52ed8b76.png)

适配之后：
![image](https://user-images.githubusercontent.com/17547942/57291619-5d3a2900-70f2-11e9-8779-2f6bc352edef.png)

**Comment by JessYanCoding** [comment]
修改了 density 会影响，也会影响状态栏高度的获取，me.jessyan.autosize.utils.ScreenUtils#getStatusBarHeight 这个方法能获取 density 修改之前的原始高度
