### ISSUE TITLE
适配后字体变得好大啊

### ISSUE THREAD

**Issue by 643063150** [JessYanCoding/AndroidAutoSize#159]
### Environment
- [x] Autosize Version: 1.12
- [x] Target Android Version: 28
- [x] Device Model:三星n9500 
- [x] Device Resolution: 2960*1440
- [x] Design Size On AndroidManifest: 375*667

### Bug Description:

使用框架后字体变大很大，不过ui倒是喜欢这个效果

### Log:

```log


```

### Related Code:
```java
  

```

**Comment by JessYanCoding** [comment]
补全上面的问题模板

**Comment by LJFDBXJ** [comment]
@JessYanCoding  救救我，救救我
