### ISSUE TITLE
添加了不起作用

### ISSUE THREAD

**Issue by peiniwan** [JessYanCoding/AndroidAutoSize#16]
### Environment
- [x] Autosize Version: v0.7.0
- [x] Target Android Version: Android 8.0 
- [x] Device Model:小米note3，三星s7 edge
- [x] Device Resolution:1080px * 1920px
- [x] Design Size On AndroidManifest: 360dp * 640dp

### Bug Description:
添加了不起作用,不同手机打印的日志一样，布局的view宽度是相同的，实际在屏幕上显示的不一样

### Log:
![qq 20180822204556](https://user-images.githubusercontent.com/13749946/44465056-04ebf580-a64f-11e8-90c7-0deacd277668.png)
![qq 20180822205546](https://user-images.githubusercontent.com/13749946/44465060-06b5b900-a64f-11e8-8906-d2371319544f.png)

### Screenshot

![qq 20180822204949](https://user-images.githubusercontent.com/13749946/44465082-1a611f80-a64f-11e8-9d95-5172c7988455.png)
![qq 20180822204934](https://user-images.githubusercontent.com/13749946/44465086-1cc37980-a64f-11e8-9427-966fbcefb82d.png)

### 显示效果
三星s7 edge
![qq 20180822205641](https://user-images.githubusercontent.com/13749946/44465115-3795ee00-a64f-11e8-90e3-b37d67181ec2.jpg)
小米note3
![_20180822205507](https://user-images.githubusercontent.com/13749946/44465134-41b7ec80-a64f-11e8-9127-eb8ddf3cc9e1.png)

**Comment by JessYanCoding** [comment]
请问下面宽度没有覆盖屏幕的是小米手机吗，系统是miui哪个版本

**Comment by peiniwan** [comment]
是的，小米note3，版本是miui9 8.3.1开发版

**Comment by JessYanCoding** [comment]
https://github.com/JessYanCoding/AndroidAutoSize/commit/8bf46cbab4b3503f958b0c2e356847bd75bcfcfe   我修复了问题，你本地依赖下 autosize 看看修复了这个问题没
