### ISSUE TITLE
小米4s android7.0出现适配问题

### ISSUE THREAD

**Issue by ttdazi** [JessYanCoding/AndroidAutoSize#163]
### Bug Description:  同样100dp的textview。
在小米4s上宽度占的比例是  300...1080...0.2777778
在其他手机宽度占比例: 450...1080...0.41666666.
其他手机是: vivo x20plus，诺基亚7plus。正常。比例是0.416.
自定义AutoUtils:采用头条宽度适配。以上比例都是适配正常。

猜测原因。由于做了特殊的小米适配造成的。

### Log:
isBaseOnWidth = true, designWidthInDp = 240.000000, designWidthInSubunits = 240.000000, targetDensity = 4.500000, targetScaledDensity = 4.500000, targetDensityDpi = 720, targetXdpi = 4.500000
vivo x20plus 如图：
![image](https://user-images.githubusercontent.com/18202927/57854667-64acb100-781b-11e9-99f8-fdcf4dcf664c.png)
小米4是如图：
![image](https://user-images.githubusercontent.com/18202927/57854764-9cb3f400-781b-11e9-864d-8e2dc8a33257.png)

```

**Comment by JessYanCoding** [comment]
用v1.1.1

**Comment by ttdazi** [comment]
用的是 V1.1.2,出现的问题，

**Comment by JessYanCoding** [comment]
```java
 private static void setDensity(Activity activity, float density, int densityDpi, float scaledDensity, float xdpi) {
        DisplayMetrics activityDisplayMetrics = activity.getResources().getDisplayMetrics();
        setDensity(activityDisplayMetrics, density, densityDpi, scaledDensity, xdpi);
        DisplayMetrics appDisplayMetrics = AutoSizeConfig.getInstance().getApplication().getResources().getDisplayMetrics();
        setDensity(appDisplayMetrics, density, densityDpi, scaledDensity, xdpi);
      
        //兼容 MIUI
        DisplayMetrics activityDisplayMetricsOnMIUI = getMetricsOnMiui(activity.getResources());
        DisplayMetrics appDisplayMetricsOnMIUI = getMetricsOnMiui(AutoSizeConfig.getInstance().getApplication().getResources());

        if (activityDisplayMetricsOnMIUI != null) {
            setDensity(activityDisplayMetricsOnMIUI, density, densityDpi, scaledDensity, xdpi);
        } 
        if (appDisplayMetricsOnMIUI != null) {
            setDensity(appDisplayMetricsOnMIUI, density, densityDpi, scaledDensity, xdpi);
        }
    }
```
在 v1.1.2 之前，不管  activityDisplayMetricsOnMIUI 和 appDisplayMetricsOnMIUI 是否为 null，都会给 activityDisplayMetrics  和 appDisplayMetrics 设置 density，在 v1.1.2 后就改成，如果 activityDisplayMetricsOnMIUI 和 appDisplayMetricsOnMIUI 不为 null ，就不给 activityDisplayMetrics  和 appDisplayMetrics 设置 density，有可能是这个问题，可以试试把 v1.1.2 版本中的 setDensity 方法替换成上面的代码

**Comment by ttdazi** [comment]
ok，就是这个地方的问题，v1.1.2版本有问题，修改完以上可以的，麻烦找时间更一下这个问题，

**Comment by ttdazi** [comment]
> ```java
>  private static void setDensity(Activity activity, float density, int densityDpi, float scaledDensity, float xdpi) {
>         DisplayMetrics activityDisplayMetrics = activity.getResources().getDisplayMetrics();
>         setDensity(activityDisplayMetrics, density, densityDpi, scaledDensity, xdpi);
>         DisplayMetrics appDisplayMetrics = AutoSizeConfig.getInstance().getApplication().getResources().getDisplayMetrics();
>         setDensity(appDisplayMetrics, density, densityDpi, scaledDensity, xdpi);
>       
>         //兼容 MIUI
>         DisplayMetrics activityDisplayMetricsOnMIUI = getMetricsOnMiui(activity.getResources());
>         DisplayMetrics appDisplayMetricsOnMIUI = getMetricsOnMiui(AutoSizeConfig.getInstance().getApplication().getResources());
> 
>         if (activityDisplayMetricsOnMIUI != null) {
>             setDensity(activityDisplayMetricsOnMIUI, density, densityDpi, scaledDensity, xdpi);
>         } 
>         if (appDisplayMetricsOnMIUI != null) {
>             setDensity(appDisplayMetricsOnMIUI, density, densityDpi, scaledDensity, xdpi);
>         }
>     }
> ```
> 
> 在 v1.1.2 之前，不管 activityDisplayMetricsOnMIUI 和 appDisplayMetricsOnMIUI 是否为 null，都会给 activityDisplayMetrics 和 appDisplayMetrics 设置 density，在 v1.1.2 后就改成，如果 activityDisplayMetricsOnMIUI 和 appDisplayMetricsOnMIUI 不为 null ，就不给 activityDisplayMetrics 和 appDisplayMetrics 设置 density，有可能是这个问题，可以试试把 v1.1.2 版本中的 setDensity 方法替换成上面的代码

ok，就是这个地方的问题，v1.1.2版本有问题，修改完以上可以的，麻烦找时间更一下这个问题，
