### ISSUE TITLE
两个不同方向的Activity切换时Fragment的适配问题

### ISSUE THREAD

**Issue by jackBear168** [JessYanCoding/AndroidAutoSize#164]
从一个横向的Activity（半屏显示一个Fragment）进入一个垂直方向的Activity后，再回退回来时，Fragment的字体、控件、间距都会变大了。

**Comment by zwc456baby** [comment]
有同样的问题。

**Comment by zwc456baby** [comment]
请问有解决吗

**Comment by zwc456baby** [comment]
首先设置:版本 1.1.2 
在承载Fragment的 activity，重写 Activity 的 getResources 方法，似乎就可以了，目前测试暂时没有复现

```
    override fun getResources(): Resources {
        //尝试解决屏幕横竖屏切换时适配失效的问题
        //如果没有自定义需求用这个方法
        AutoSizeCompat.autoConvertDensityOfGlobal((super.getResources()))
        return super.getResources()
    }
```

具体可以[点击这里查看Release](https://github.com/JessYanCoding/AndroidAutoSize/releases/tag/v1.1.2)

**Comment by jackBear168** [comment]
> 首先设置:版本 1.1.2
> 在承载Fragment的 activity，重写 Activity 的 getResources 方法，似乎就可以了，目前测试暂时没有复现
> 
> ```
>     override fun getResources(): Resources {
>         //尝试解决屏幕横竖屏切换时适配失效的问题
>         //如果没有自定义需求用这个方法
>         AutoSizeCompat.autoConvertDensityOfGlobal((super.getResources()))
>         return super.getResources()
>     }
> ```
> 
> 具体可以[点击这里查看Release](https://github.com/JessYanCoding/AndroidAutoSize/releases/tag/v1.1.2)



> 请问有解决吗

之前只有忽略该Activity的适配

**Comment by zwc456baby** [comment]
> > 首先设置:版本 1.1.2
> > 在承载Fragment的 activity，重写 Activity 的 getResources 方法，似乎就可以了，目前测试暂时没有复现
> > ```
> >     override fun getResources(): Resources {
> >         //尝试解决屏幕横竖屏切换时适配失效的问题
> >         //如果没有自定义需求用这个方法
> >         AutoSizeCompat.autoConvertDensityOfGlobal((super.getResources()))
> >         return super.getResources()
> >     }
> > ```
> > 
> > 
> > 具体可以[点击这里查看Release](https://github.com/JessYanCoding/AndroidAutoSize/releases/tag/v1.1.2)
> 
> > 请问有解决吗
> 
> 之前只有忽略该Activity的适配

按照我说的应该是可以解决这个问题的。至少目前我没收到用户反馈了

**Comment by xilost** [comment]
@zwc456baby 这个没用，我的是一个列表，旋转后图片放大了。

**Comment by JessYanCoding** [comment]
如果在返回到 Fragment 时，Fragment 页面重建了，那就是 density 的值不是期望的值，在 Fragment 重建前，使用 AutoSize.autoConvertDensity  传入期望的值

**Comment by DreamFly01** [comment]
手机打开 自动旋转屏幕，app在手机横着的情况下启动，会出现适配失效 @JessYanCoding 
![41e0917dacaca9dbce45685d3da99f0](https://user-images.githubusercontent.com/18188608/68265895-5fbd1180-0088-11ea-9204-b1415dad1bd8.jpg)
![c4afafe56eb1b9e38c3ae6331ffd9ab](https://user-images.githubusercontent.com/18188608/68265896-5fbd1180-0088-11ea-8e2d-86c897937197.jpg)

**Comment by DreamFly01** [comment]
大佬，上面的方法 AutoSize.autoConvertDensity 传入期望的值在设置layout之前调用也没得啥子用

**Comment by DreamFly01** [comment]
大佬 解决勒，在启动页加入了android:screenOrientation="portrait"，但是在mainActivity没有加这个属性，所以进入到main的时候 虽然是竖屏的 ，但是宽高比已经变成了横屏的了，谢谢大佬提供适配方案，由衷的感谢！！
