### ISSUE TITLE
系统的复制粘贴，显示的特别小

### ISSUE THREAD

**Issue by wjj201411** [JessYanCoding/AndroidAutoSize#165]
![image](https://user-images.githubusercontent.com/9624595/58416738-259d1c00-80b5-11e9-8c11-6d3e2f71b523.png)

**Comment by 861493711** [comment]
EditText.setOnFocusChangeListener(new OnFocusChangeListener() {
            @Override
            public void onFocusChange(View v, boolean hasFocus) {
                if(hasFocus){
                    //取消适配
                }else{
                   //重新适配
                }
            }
        });
我是这样解决的

**Comment by ma343599083** [comment]
同问，求解决方式

**Comment by tomUp** [comment]
@JessYanCoding 遇到同样问题，有没更好的解决方式...

**Comment by tomUp** [comment]
目前已知可以监听到“复制/粘贴”弹窗调起的监听，然后取消适配
```
EditText editText = new EditText(this);
editText .setOnCreateContextMenuListener(new View.OnCreateContextMenuListener() {
    @Override
    public void onCreateContextMenu(ContextMenu menu, View v, ContextMenu.ContextMenuInfo menuInfo) {
        AutoSize.cancelAdapt(this);
     }
});
```

但是弹窗消失的监听好像没有，有没更优雅一点统一的解法 @JessYanCoding

**Comment by JessYanCoding** [comment]
使用副单位，可以屏蔽修改 density 对系统控件和三方库控件的影响
