### ISSUE TITLE
项目中添加依赖implementation 'me.jessyan:autosize:1.1.2'导致崩溃

### ISSUE THREAD

**Issue by wgng** [JessYanCoding/AndroidAutoSize#166]
仅在项目的gradle文件中添加依赖
dependencies {
implementation 'me.jessyan:autosize:1.1.2'
｝
不使用“autosize”包的任何信息，项目启动崩溃

**Comment by youarenowhere** [comment]
java.lang.NoClassDefFoundError: me.jessyan.autosize.FragmentLifecycleCallbacksImpl

**Comment by itsnicerdx** [comment]
> 仅在项目的gradle文件中添加依赖
> dependencies {
> implementation 'me.jessyan:autosize:1.1.2'
> ｝
> 不使用“autosize”包的任何信息，项目启动崩溃

你在AndroidManifest 添加了meta-data吗？

**Comment by JessYanCoding** [comment]
https://github.com/JessYanCoding/AndroidAutoSize/issues/32
