### ISSUE TITLE
适配小米8及屏幕翻转

### ISSUE THREAD

**Issue by mynamew** [JessYanCoding/AndroidAutoSize#17]
### Environment
- [x] Autosize Version: v0.7.0 
- [x] Target Android Version:Android 8.0
- [x] Device Model: 小米8
- [x] Device Resolution: 2248x1080像素
- [x] Design Size On AndroidManifest: 365 655

### Bug Description:
  1、适配是下方有一小块空白
  2、当屏幕翻转的时候，适配就不成功了
### Screenshot

![autosize1](https://user-images.githubusercontent.com/13727541/44500070-6052cd80-a6b9-11e8-9fb2-c147085c29e0.png)
![screenshot_2018-08-23-09-37-13-207_com jzk common](https://user-images.githubusercontent.com/13727541/44500080-68ab0880-a6b9-11e8-9edb-403b9bbca9fc.png)
### Related Code:
```java
```

**Comment by JessYanCoding** [comment]
第一个问题看这里 https://github.com/JessYanCoding/AndroidAutoSize/issues/8

第二个问题，那是肯定的，你之前屏幕宽度是 1080 像素，竖屏的时候，View 的尺寸刚好为 1080 像素，所以刚好覆盖屏幕，现在旋转屏幕宽度变为了  2248px，你布局里还写的 1080px，当然整个布局只占屏幕宽度的一半了，这还是基础把...你横屏的时候没有根据横屏的设计图重新布局，还指望框架帮你做这个，框架还没智能到这个程度
