### ISSUE TITLE
小米8适配问题

### ISSUE THREAD

**Issue by GooDong** [JessYanCoding/AndroidAutoSize#171]
### Environment
- [x] Autosize Version: 
- [x] Target Android Version: 
- [x] Device Model: 
- [x] Device Resolution: 
- [x] Design Size On AndroidManifest: 

### Bug Description:
![image](https://user-images.githubusercontent.com/16299902/59409977-2be80380-8dea-11e9-83c9-ca490eb58436.png)

底部导航栏 和 GrideView，明显变小了。其他界面元素正常。

### Log:
![image](https://user-images.githubusercontent.com/16299902/59410111-897c5000-8dea-11e9-881f-c9070204ba3e.png)

### Screenshot
![image](https://user-images.githubusercontent.com/16299902/59410020-520da380-8dea-11e9-8f21-5fc527e8eb96.png)

### Related Code:
```java

**Comment by GooDong** [comment]
找到问题了。
View tabView = LayoutInflater.from(mContext).inflate......

**Comment by xiaohuzi0113** [comment]
遇到同样的问题，在小米8青春版和魅蓝手机上网格布局都变形了……没有解决……
