### ISSUE TITLE
CustomAdapt无法设置单独Activity根据长度适配

### ISSUE THREAD

**Issue by imlilu** [JessYanCoding/AndroidAutoSize#173]
Environment
-Autosize Version: 1.1.2
- Target Android Version: 28
- Device Model: all
- Device Resolution: 1080px * 1920px 
- Design Size On AndroidManifest: 375dp * 812dp

设置implements CustomAdapt 后运行项目没有按照高度去适配，但是设置AutoSizeConfig.getInstance().setBaseOnWidth(false);就可以正常按照高度去适配了。

设置为implements CustomAdapt 
运行后的日志为
06-14 10:22:53.362 12358-12358/com.goski.logincomponent D/AndroidAutoSize: designWidthInDp = 375, designHeightInDp = 812, screenWidth = 1080, screenHeight = 1920
06-14 10:22:53.362 12358-12358/com.goski.logincomponent D/AndroidAutoSize: initDensity = 3.0, initScaledDensity = 3.0
06-14 10:22:58.272 12358-12358/com.goski.logincomponent D/AndroidAutoSize: com.goski.logincomponent.ui.activity.NickNameAvatarActivity implemented by me.jessyan.autosize.internal.CustomAdapt!
06-14 10:22:58.272 12358-12358/com.goski.logincomponent D/AndroidAutoSize: The com.goski.logincomponent.ui.activity.NickNameAvatarActivity has been adapted! 
    NickNameAvatarActivity Info: isBaseOnWidth = false, designHeightInDp = 812.000000, designHeightInSubunits = 812.000000, targetDensity = 2.272167, targetScaledDensity = 2.272167, targetDensityDpi = 363, targetXdpi = 2.272167
06-14 10:22:58.442 12358-12358/com.goski.logincomponent D/AndroidAutoSize: com.goski.logincomponent.ui.activity.NickNameAvatarActivity implemented by me.jessyan.autosize.internal.CustomAdapt!
06-14 10:22:58.442 12358-12358/com.goski.logincomponent D/AndroidAutoSize: The com.goski.logincomponent.ui.activity.NickNameAvatarActivity has been adapted! 
    NickNameAvatarActivity Info: isBaseOnWidth = false, designHeightInDp = 812.000000, designHeightInSubunits = 812.000000, targetDensity = 2.272167, targetScaledDensity = 2.272167, targetDensityDpi = 363, targetXdpi = 2.272167

去除CustomAdapt在application里添加  AutoSizeConfig.getInstance().setBaseOnWidth(false);
后运行的日志为
D/AndroidAutoSize: designWidthInDp = 375, designHeightInDp = 812, screenWidth = 1080, screenHeight = 1920
06-14 10:28:26.902 13268-13268/com.goski.logincomponent D/AndroidAutoSize: initDensity = 3.0, initScaledDensity = 3.0
06-14 10:28:31.842 13268-13268/com.goski.logincomponent D/AndroidAutoSize: com.goski.logincomponent.ui.activity.NickNameAvatarActivity used the global configuration.
06-14 10:28:31.842 13268-13268/com.goski.logincomponent D/AndroidAutoSize: The com.goski.logincomponent.ui.activity.NickNameAvatarActivity has been adapted! 
    NickNameAvatarActivity Info: isBaseOnWidth = false, designHeightInDp = 812.000000, designHeightInSubunits = 812.000000, targetDensity = 2.272167, targetScaledDensity = 2.272167, targetDensityDpi = 363, targetXdpi = 2.272167
06-14 10:28:32.082 13268-13268/com.goski.logincomponent D/AndroidAutoSize: com.goski.logincomponent.ui.activity.NickNameAvatarActivity used the global configuration.
06-14 10:28:32.082 13268-13268/com.goski.logincomponent D/AndroidAutoSize: The com.goski.logincomponent.ui.activity.NickNameAvatarActivity has been adapted! 
    NickNameAvatarActivity Info: isBaseOnWidth = false, designHeightInDp = 812.000000, designHeightInSubunits = 812.000000, targetDensity = 2.272167, targetScaledDensity = 2.272167, targetDensityDpi = 363, targetXdpi = 2.272167
![Uploading device-2019-06-14-103113.png…]()

**Comment by imlilu** [comment]
找到了原因，是因为添加了AutoSizeCompat.autoConvertDensityOfGlobal(super.getResources());这个方法导致的，为什么会引起这个问题不明……

**Comment by JessYanCoding** [comment]
AutoSizeCompat.autoConvertDensityOfGlobal 会覆盖自定义的配置使用全局的配置

**Comment by yuan852481783** [comment]
Fragment中 implements CustomAdapt  不管用  全局没有设置AutoSizeCompat.autoConvertDensityOfGlobal。应该怎么办
