### ISSUE TITLE
与Bugly的热更新冲突

### ISSUE THREAD

**Issue by wang-love-yu** [JessYanCoding/AndroidAutoSize#174]
今天在使用过程中，配置了bugly的热更新，使用发现原来能自动适配的布局失效了

**Comment by azxcffdgadf** [comment]
我也有同样的问题

**Comment by Gentleman-jun** [comment]
推测是热更新导致的和哪里的代码冲突了

**Comment by Jasonono** [comment]
我也遇到这个问题了

**Comment by JessYanCoding** [comment]
https://github.com/JessYanCoding/AndroidAutoSize/issues/13#11

**Comment by wang-love-yu** [comment]
作者已经回复过类似问题 https://github.com/JessYanCoding/AndroidAutoSize/issues/38
