### ISSUE TITLE
使用demo动态改变textsize好像无效的问题

### ISSUE THREAD

**Issue by zzm123456** [JessYanCoding/AndroidAutoSize#176]
### Environment
- [x] Autosize Version: v1.1.2 
- [x] Target Android Version:Android 8.0.0
- [x] Device Model: 华为Honor V8
- [x] Device Resolution: 2560px * 1440px
- [x] Design Size On AndroidManifest: 360dp * 640dp

### Screenshot
![a16d4a659b58ffedbeb59a1c219fdf3](https://user-images.githubusercontent.com/13730768/59592898-80112180-9123-11e9-8084-79a2abf5c395.jpg)
![95ce8f5a9c82217b38484072b03abba](https://user-images.githubusercontent.com/13730768/59592909-830c1200-9123-11e9-8395-0ce0547369f0.jpg)
![b73a13b606073819cdb321af1605bbe](https://user-images.githubusercontent.com/13730768/59593009-bbabeb80-9123-11e9-88ea-f8e1077d7f14.png)

### Log:
`me.jessyan.autosize.demo D/AndroidAutoSize: designWidthInDp = 0, designHeightInDp = 0, screenWidth = 1440, screenHeight = 2416
me.jessyan.autosize.demo D/AndroidAutoSize: initDensity = 3.5, initScaledDensity = 3.5
me.jessyan.autosize.demo D/AndroidAutoSize: me.jessyan.autosize.demo.MainActivity onAdaptBefore!
me.jessyan.autosize.demo D/AndroidAutoSize: me.jessyan.autosize.demo.MainActivity used the global configuration.
me.jessyan.autosize.demo D/AndroidAutoSize: The me.jessyan.autosize.demo.MainActivity has been adapted! 
    MainActivity Info: isBaseOnWidth = true, designWidthInDp = 360.000000, designWidthInSubunits = 360.000000, targetDensity = 4.000000, targetScaledDensity = 4.000000, targetDensityDpi = 640, targetXdpi = 4.000000
me.jessyan.autosize.demo D/AndroidAutoSize: me.jessyan.autosize.demo.MainActivity onAdaptAfter!
me.jessyan.autosize.demo D/AndroidAutoSize: me.jessyan.autosize.demo.MainActivity onAdaptBefore!
me.jessyan.autosize.demo D/AndroidAutoSize: me.jessyan.autosize.demo.MainActivity used the global configuration.
me.jessyan.autosize.demo D/AndroidAutoSize: The me.jessyan.autosize.demo.MainActivity has been adapted! 
    MainActivity Info: isBaseOnWidth = true, designWidthInDp = 360.000000, designWidthInSubunits = 360.000000, targetDensity = 4.000000, targetScaledDensity = 4.000000, targetDensityDpi = 640, targetXdpi = 4.000000
me.jessyan.autosize.demo D/AndroidAutoSize: me.jessyan.autosize.demo.MainActivity onAdaptAfter!`

图一是demo运行的效果
图二是我加入了一小段代码（图三），动态修改了一下button的Text的size，但是运行的效果好像反而更大了，按钮的xml的原来textSize是30sp。

**Comment by benjaminwan** [comment]
用带单位参数的方法
btn.setTextSize(TypedValue.COMPLEX_UNIT_SP, 10);

**Comment by zzm123456** [comment]
@benjaminwan 换上您说的方法就可以了 感谢回复

**Comment by JessYanCoding** [comment]
setTextSize 本来默认使用的就是 sp，你在参数里传的值还用工具类将 px 转成 sp，相当于乘以了两次 density ，字体不大才怪
