### ISSUE TITLE
切换多语言适配失效

### ISSUE THREAD

**Issue by peiniwan** [JessYanCoding/AndroidAutoSize#18]
### Environment
- [x] Autosize Version:: v0.7.0
- [x] Target Android Version:Android 8.0 -
- [x] Device Model: 一加3
- [x] Device Resolution: 1920*1080
- [x] Design Size On AndroidManifest: 360dp * 640dp

### Bug Description:

切换多语言，会导致适配失效，字体变小了，布局也变了

### Log:切换前后是一样的

```log
isBaseOnWidth = true, designWidthInDp = 360.000000, targetDensity = 3.000000, targetScaledDensity = 3.000000, targetDensityDpi = 480
```

### Screenshot

切换前
![qq 20180823111209](https://user-images.githubusercontent.com/13749946/44502720-6f3f7d00-a6c5-11e8-8eaa-6da2eb94c991.jpg)
![qq 20180823112130](https://user-images.githubusercontent.com/13749946/44503008-bb3ef180-a6c6-11e8-8eb3-b72e216de90a.jpg)

切换后
![qq 20180823111214](https://user-images.githubusercontent.com/13749946/44502725-72d30400-a6c5-11e8-87b0-2a7a487b02aa.jpg)
![qq 20180823112136](https://user-images.githubusercontent.com/13749946/44503017-c1cd6900-a6c6-11e8-96bb-1122b10a4a8e.jpg)

### Related Code:
```java切换多语言的代码
      public static void changeLanguageSetting(Locale locale, Activity activity) {
        changeAppLanguage(activity, locale, true);
        //开始新的activity同时移除之前所有的activity
        PreferenceStore.ofBoolean(CHANGE_LANGUAGE, false).set(true);
        Intent intent = new Intent(activity, MainPageActivity.class);
        intent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK | Intent.FLAG_ACTIVITY_CLEAR_TASK);
        activity.startActivity(intent);
    }

  /**
     * 更改应用语言
     *
     * @param context
     * @param locale      语言地区
     * @param persistence 是否持久化
     */
    public static Context changeAppLanguage(Context context, Locale locale,
                                            boolean persistence) {
        if (locale == null) {
            return context;
        }
        curLocale = locale;
        Log.i(TAG, "changeAppLanguage: local : " + locale.getLanguage());

        if (persistence) {
            saveLanguageSetting(context, locale);
        }
        CommonCountryManager.ins().changeCommonCountryLanguage(context, locale);

        Resources resources = context.getResources();
        DisplayMetrics metrics = resources.getDisplayMetrics();
        Configuration configuration = resources.getConfiguration();
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
            configuration.setLocale(locale);
        } else {
            configuration.locale = locale;
        }
        context = context.createConfigurationContext(configuration);
        resources.updateConfiguration(configuration, metrics);
        return context;

    }

```

**Comment by JessYanCoding** [comment]
你提的上一个 issues 我解决了，你试试本地依赖，看下这个 issues 是不是这个引起的
不行的话切换的语言后，调用下这个 AutoSize.autoConvertDensityOfGlobal(Activity)

**Comment by JessYanCoding** [comment]
changeAppLanguage() 之前后之后都调用一次 AutoSize.autoConvertDensityOfGlobal(Activity)

**Comment by peiniwan** [comment]
嗯，前后都添加了，但是没有作用，清了缓存就适配了，一切换语言，那个红色button就又不是全屏了

**Comment by JessYanCoding** [comment]
你说的缓存是什么缓存

**Comment by peiniwan** [comment]
应用程序的数据
![_20180823181039](https://user-images.githubusercontent.com/13749946/44519540-e265e500-a6ff-11e8-844c-9505550cbb17.png)

**Comment by JessYanCoding** [comment]
你看看测试下，其他设备是否有相同的问题

**Comment by peiniwan** [comment]
小米note3和一加3，别的手机没有发现问题，我的三星和红米是好的

**Comment by peiniwan** [comment]
我的手机比较少，可能我代码写的有问题吧，先关了吧
