### ISSUE TITLE
RecyclerView文字变小问题

### ISSUE THREAD

**Issue by chengzijian** [JessYanCoding/AndroidAutoSize#181]
一加5T手机 android9.0.  偶现
看图说话

![image](https://user-images.githubusercontent.com/6936576/60157033-686f2280-9820-11e9-842d-2b717aeda063.png)
![image](https://user-images.githubusercontent.com/6936576/60157500-783b3680-9821-11e9-814d-b735236e3a8b.png)
布局层次  activity->fragment->自定义view->RecyclerView

有遇到过的老铁麻烦贴个解决方案, 不胜感激.

**Comment by chinwetang** [comment]
我也遇到的一样的问题...百思不得其解

**Comment by chengzijian** [comment]
> 我也遇到的一样的问题...百思不得其解

有人说使用 AutoSizeCompat.autoConvertDensityOfGlobal(getContext().getResources()); 来重设下就行了. 我试了效果不理想, 你可以试试看

**Comment by JessYanCoding** [comment]
https://github.com/JessYanCoding/AndroidAutoSize/issues/59
