### ISSUE TITLE
加固以后好像失效了

### ISSUE THREAD

**Issue by q735510971** [JessYanCoding/AndroidAutoSize#183]
乐加固以后 会失效

**Comment by itsnicerdx** [comment]
是的，乐固加固后失效

**Comment by Jasonono** [comment]
我这乐固加固没有失效啊

**Comment by itsnicerdx** [comment]
你换个 dpi 差距大一点的屏幕。

**Comment by JessYanCoding** [comment]
群里有个兄弟，将乐加固升级到最新版本就可以了

**Comment by NateRobinson** [comment]
@JessYanCoding 我用的 `me.jessyan:autosize:1.1.2` 并且用的最新的加固固件加固出来在大部分机型上表现正常，目前发现 MI5 ,还有部分华为机型上的却还是会不行，导致整个页面都变形了
