### ISSUE TITLE
集成AutoSize后，有暴露类名的风险

### ISSUE THREAD

**Issue by Tiny1213** [JessYanCoding/AndroidAutoSize#185]
![image](https://user-images.githubusercontent.com/9071200/60256670-92017a00-9904-11e9-81c7-4acc2dc4df4f.png)
通过Android Studio的Logcat能看到其他应用的类名，建议默认关闭这个log。

**Comment by JessYanCoding** [comment]
setDebug(false) 你自己可以关闭，默认关闭，AutoSize 就打印不了初始化信息了
