### ISSUE TITLE
双屏异显适配问题

### ISSUE THREAD

**Issue by LjieQ** [JessYanCoding/AndroidAutoSize#188]
Environment
- [x] Autosize Version:   v1.1.1
- [x] Target Android Version:  Android 6.0.1
- [x] Device Model:  开发板3288，横屏
- [x] Device Resolution:  1366px * 768px 
- [x] Design Size On AndroidManifest: 

 Bug Description:
项目要开发一个收银屏，一块主板显示两个屏幕，分别显示不同的内容。主屏的分辨率和副屏分辨率是一样的，屏幕尺寸也是一样的，但是输出的density是不同的。主屏的density为160，副屏的density为227。目前主屏的适配是没问题，是按照1920*1080的设计图来做的，直接px/3后来直接设置dp，但是副屏的话就不能按照主屏的来设置dp了。我想请教下要如何转换，才能在副屏直接设置dp吗？

Screenshot
主屏信息截图：
![image](https://user-images.githubusercontent.com/34932454/60560170-660d4b00-9d81-11e9-8685-cc0928ae2e1e.png)

副屏信息截图：
![image](https://user-images.githubusercontent.com/34932454/60560160-5c83e300-9d81-11e9-9006-9fcb6b82b87c.png)

**Comment by zxc514257857** [comment]
哥们这个问题有解决吗，我也遇到了

**Comment by JessYanCoding** [comment]
副屏就按照主屏的方式来就可以了

**Comment by KeqingLI** [comment]
在Presentation中复写getResources，调用 AutoSizeCompat.autoConvertDensity，或导致Presentation被关闭，楼主怎么解决适配的
Presentation is being immediately dismissed because the display metrics have changed since it was created.

**Comment by JessYanCoding** [comment]
@KeqingLI Presentation 没研究过，报错意思是让你不要改变 DisplayMetrics 的某些信息，意味着 Presentation 可能不允许改变 DisplayMetrics 某些信息的行为，要求 DisplayMetrics 必须和创建时保持一致。

**Comment by gacmy** [comment]
对于副屏的界面 直接每个界面单独调用一个适配方法 改变这个界面的屏幕宽度 为副屏的宽度 设计稿固定的宽度 设置一下density 就是每个副屏的Fragment都需要调用这个方法:`fun screenFix(screenWidth:Int,context:Context?){
       
        var density = screenWidth/960f
        var dpi = 160*density
        context?.resources?.displayMetrics?.density = density
        context?.resources?.displayMetrics?.widthPixels = screenWidth
        context?.resources?.displayMetrics?.densityDpi = dpi.toInt()
        context?.resources?.displayMetrics?.scaledDensity = density
    }`
