### ISSUE TITLE
华为2340*1080无法适配有什么好的建议或解决问题的思路吗

### ISSUE THREAD

**Issue by kevinStrange** [JessYanCoding/AndroidAutoSize#190]
### Environment
- [x] Autosize Version: 
- [x] Target Android Version: 
- [x] Device Model: 
- [x] Device Resolution: 
- [x] Design Size On AndroidManifest: 

### Log:

```log


```

### Related Code:
```java
  

```

**Comment by theshdf** [comment]
> ### Environment
> * [x]  Autosize Version:
> * [x]  Target Android Version:
> * [x]  Device Model:
> * [x]  Device Resolution:
> * [x]  Design Size On AndroidManifest:
> 
> ### Bug Description:
> ### Log:
> ```
> 
> ```
> 
> ### Screenshot
> ### Related Code:
> ```java
>   
> ```
> 
> ### Others:

兄弟 你的这个适配解决了么
