### ISSUE TITLE
以高为基准的适配，刘海屏，凹凸屏不能充满屏幕

### ISSUE THREAD

**Issue by chenxi0203** [JessYanCoding/AndroidAutoSize#193]
![11](https://user-images.githubusercontent.com/20221278/61204563-15520680-a720-11e9-9d85-78a34aa3ce20.jpg)
![22](https://user-images.githubusercontent.com/20221278/61204573-20a53200-a720-11e9-8ac3-913cf6c3e4de.jpg)

2:  还有个问题咨询下：我如果在BaseActivity设置的布局id，在想要以高度适配的activity中实现CustomAdapt接口，如果继承base也会有问题，无法填充满屏幕，如果不继承就是OK的。
base：
 @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        preInit();
        //设置布局内容
        setContentView(getLayoutId());
｝

具体的某个activity：
public class TestActivity extends BaseActivity implements CustomAdapt{
    
    @Override
    public int getLayoutId() {
        return R.layout.activity_test;
    }

    @Override
    public boolean isBaseOnWidth() {
        return false;
    }
    @Override
    public float getSizeInDp() {
        return 640;
    }
}

**Comment by chenxi0203** [comment]
- Autosize Version:  1.1.2
- Target Android Version: Android 9.0 
- Device Model:  小米8
- Device Resolution: 1080px * 2248px
- Design Size On AndroidManifest: 360dp * 640dp

**Comment by LayneCui** [comment]
遇到了同样的问题

**Comment by JessYanCoding** [comment]
https://github.com/JessYanCoding/AndroidAutoSize/issues/194
