### ISSUE TITLE
使用了这个适配方案后是否可以采用绝对布局？

### ISSUE THREAD

**Issue by BzCoder** [JessYanCoding/AndroidAutoSize#196]
因为该方案统一了宽度DP，那么绝对布局是不是就不会出现不适配的问题了？虽然Google已经把绝对布局废了，单纯好奇。

**Comment by JessYanCoding** [comment]
这个布局没试过，不过框架原理是修改 density，和用什么布局无关，不管用什么布局都是等比例拉伸

**Comment by BzCoder** [comment]
嗯嗯，因为当时说绝对布局最大的问题就是不同手机屏幕宽度DP不一致被废弃了，现在通过你的框架DP保持统一了，就想绝对布局是不是可以复活了

**Comment by JessYanCoding** [comment]
这个你可以试试，这个框架和具体 View 布局关系不大，主要是改变 dp 的计算方式
