### ISSUE TITLE
AndroidAutoSize的奔溃日志监听在哪里关闭呢？

### ISSUE THREAD

**Issue by DevXue** [JessYanCoding/AndroidAutoSize#197]
### Environment
- [x] Autosize Version: 
- [x] Target Android Version: 
- [x] Device Model: 
- [x] Device Resolution: 
- [x] Design Size On AndroidManifest: 

### Log:

```log


```

### Related Code:
```java
  

```

### Others:
程序崩溃后有个崩溃信息日志页面（小虫子页面），这个页面怎么关闭呢？

**Comment by DevXue** [comment]
![sss](https://user-images.githubusercontent.com/9455329/61505016-01ecb700-aa10-11e9-9179-cafc3e2af04c.png)

**Comment by JessYanCoding** [comment]
这是 Demo 引入的一个框架 cat.ereza:customactivityoncrash:2.2.0，你不引入就可以了
