### ISSUE TITLE
横竖屏切换时出现的图片拉伸问题。

### ISSUE THREAD

**Issue by xilost** [JessYanCoding/AndroidAutoSize#198]
Environment
  Autosize Version: 1.1.2
  Target Android Version: Android 7.1.2
  Device Model: VIVO Y79
  Device Resolution: 1440*720
  Design Size On AndroidManifest:375*667

Bug Description:
 正常显示如下图：
 ![image](https://user-images.githubusercontent.com/5326618/61517455-dc74a300-aa39-11e9-8592-ace90cae5cb5.png)

 旋转屏幕后底部横向列表有些item被拉伸了：
 ![image](https://user-images.githubusercontent.com/5326618/61517535-0cbc4180-aa3a-11e9-91fb-915cd1ddefe6.png)

 再旋转回来也是同样的问题，高度也出现了错位：
![device-2019-07-19-152440](https://user-images.githubusercontent.com/5326618/61517910-eea31100-aa3a-11e9-92b3-3c4130595cc5.png)

代码中使用了下面的方法:
`@Override
  public Resources getResources() {
        AutoSizeCompat.autoConvertDensity(super.getResources(), 375, currentOrientation == PORTRAIT);
        return super.getResources();
    }`

非必现，列表来回滑动后可能会正常。

**Comment by JessYanCoding** [comment]
https://github.com/JessYanCoding/AndroidAutoSize/issues/59
