### ISSUE TITLE
设计图是px单位的咋办？

### ISSUE THREAD

**Issue by focus2846** [JessYanCoding/AndroidAutoSize#2]

**Comment by JessYanCoding** [comment]
兄 die，这个很基础，dp 换算公式了解一下，px / (Dpi/160) = dp，至于 DPI 这个是什么东西，建议百度下，使用框架之前先看下我的 [文章](https://www.jianshu.com/p/55e0fca23b4f) 了解下这个方案基本是什么原理，可以参考下这个 [网站](https://material.io/tools/devices/) 给予的一些机型信息

**Comment by yangzhenqi** [comment]
设计图没有像素密度这一说吧，而且不同设备dpi也是不一样的，只有px的设计图又如何在配置文件配置dp单位的值呢

**Comment by JessYanCoding** [comment]
你就以测试机为准，或者你直接将 px 除以2，或者除以3，对适配效果都是没影响的，文章中有分析原理
