### ISSUE TITLE
小米mix2s设置全面屏手势，不能很好适配。屏幕下方留有空间

### ISSUE THREAD

**Issue by ivenchan** [JessYanCoding/AndroidAutoSize#20]
- [x] Autosize Version: 0.7.0
- [x] Target Android Version: MIUI 9.6 (ANDOIRD 8.0)
- [x] Device Model:小米 MIX2S
- [x] Device Resolution: 2160px * 1080px
- [x] Design Size On AndroidManifest: demo

运行楼主提供demo，打开适配CustomAdaptActivity界面，并不能适配全面屏手势，下面一处留有空白间隙，如果不是全面屏手势，就没有问题。留有空白处刚好是虚拟按键高度。

![20180823134359](https://user-images.githubusercontent.com/4526535/44507214-437bc180-a6dc-11e8-8932-fe99029922aa.jpg)

**Comment by JessYanCoding** [comment]
框架日志

**Comment by JessYanCoding** [comment]
2160-(667*2.935532) = 202，屏幕高度被减去了 202 像素，测量下状态栏高度，和导航栏高度，看下 202 像素是怎么来的

**Comment by ivenchan** [comment]
调用楼主的方法：ScreenUtils.getHeightOfNavigationBar(context)  = 130
                             ScreenUtils.getStatusBarHeight()  =  72  
刚好是202像素

**Comment by ivenchan** [comment]
public int getScreenHeight() {
//        return isUseDeviceSize() ? mScreenHeight : mScreenHeight - ScreenUtils.getStatusBarHeight() - ScreenUtils.getHeightOfNavigationBar(getApplication());
        return isUseDeviceSize() ? mScreenHeight : mScreenHeight - ScreenUtils.getStatusBarHeight();
    }
把计算getHeightOfNavigationBar这个去掉就正常，估计要判断是否隐藏NavigationBar或者StatusBar来计算

**Comment by JessYanCoding** [comment]
这个方法，我这里测试是有导航栏，则返回导航栏的高度，无则返回 0，你能否帮我测试下你的机型能否找到可用的能测试导航栏是否存在，以及获取高度

**Comment by ivenchan** [comment]
小米的这个方法可以 Settings.Global.getInt(context.getContentResolver(), "force_fsg_nav_bar", 0) != 0
true为全面屏手势，false有就正常。

**Comment by ivenchan** [comment]
不存在刷新的问题，我手机一直是用全面屏的。去看了小米开发者官网，也没有这方面的API调用。

**Comment by JessYanCoding** [comment]
我意思是你是在这个页面打开并且适配完毕后，开的全面屏手势，还是最开始页面没打开就已经开启了全面屏手势

**Comment by ivenchan** [comment]
开始页面没打开就已经开启了全面屏手势，就是一直都是全面屏的。

**Comment by ivenchan** [comment]
可以先判断全屏手势是否开启，如果开启即没有导航栏，否则再判断是否有导航栏。

**Comment by JessYanCoding** [comment]
意思就是返回状态栏高度的方法是，全面屏就默认返回0

**Comment by ivenchan** [comment]
我只是测试小米是这样，其它手机不知道。有待验证。

**Comment by ivenchan** [comment]
https://www.v2ex.com/t/470543

**Comment by JessYanCoding** [comment]
@ivenchan 我测试了其他，手机都是返回 false，应该没问题

**Comment by JessYanCoding** [comment]
@ChaiJiangpeng 自己改一个正确的屏幕高度 AutoSizeConfig#setScreenHeight

**Comment by ChaiJiangpeng** [comment]
嗯，ScreenUtils.getScreenSize(Context context)在小米上不管是否开启全面屏，高度不变，一直都是减去导航栏的高度

**Comment by JessYanCoding** [comment]
@ChaiJiangpeng v1.0.6 已经优化了这个地方
