### ISSUE TITLE
创建 Preview 的问题

### ISSUE THREAD

**Issue by wangchunleioo** [JessYanCoding/AndroidAutoSize#200]
layout中使用mm作为单位，在创建预览的时候 按照公式 (sqrt(纵向分辨率^2+横向分辨率^2))/25.4 求出屏幕尺寸 请问为什么得出的结果不是86.73？如果设计图是540*960那么Screen又是多少呢？

**Comment by JessYanCoding** [comment]
43.3643143717，计算问题建议自己多试试，这个公式，大家用都没问题
