### ISSUE TITLE
自定义View适配后字体变大

### ISSUE THREAD

**Issue by Rachel-hsw** [JessYanCoding/AndroidAutoSize#201]
### Environment
- [x] Autosize Version:  1.1.2
- [x] Target Android Version:  Android 8.1
- [x] Device Model: 原生模拟器x86
- [x] Device Resolution: 1920*1080
- [x] Design Size On AndroidManifest: 1024*768

### Bug Description:

如图所示，第二张是正常设备截图。

### Log:

```log


```

### Screenshot

![image](https://user-images.githubusercontent.com/23740416/62277750-5b75cc80-b479-11e9-8ead-13ff55139786.png)

![image](https://user-images.githubusercontent.com/23740416/62276287-4cd9e600-b476-11e9-955a-7828b7dc3e45.png)

### Related Code:
```java
         TextView plus = new TextView(getContext());
         plus.setTextColor(getContext().getColor(R.color.gray11));
         plus.setTextSize(AutoSizeUtils.sp2px(getContext(),20));

```

**Comment by Rachel-hsw** [comment]
后来我发现，代码直接改为`         TextView plus = new TextView(getContext());
         plus.setTextColor(getContext().getColor(R.color.gray11));
         plus.setTextSize(20);`就是不去适配，字体会正常。不明白原因。是不是作者有提到，但是我没看到

**Comment by JessYanCoding** [comment]
看看xml中写20sp，和用代码 AutoSizeUtils.sp2px(getContext(),20) 得到的效果是否一样，一样就说明 density 的计算是没问题的，你自己调整下字体大小就行

**Comment by Rachel-hsw** [comment]
> 看看xml中写20sp，和用代码AutoSizeUtils.sp2px（getContext（），20）得到的效果是否一样，一样就说明density的计算是没问题的，你自己调整下字体大小就行

xml中写20sp和plus.setTextSize(20);的效果是一样的。和AutoSizeUtils.sp2px（getContext（），20）不一样。第一列就是xml 20sp

**Comment by Rachel-hsw** [comment]
> 看看xml中写20sp，和用代码 AutoSizeUtils.sp2px(getContext(),20) 得到的效果是否一样，一样就说明 density 的计算是没问题的，你自己调整下字体大小就行
下面是我的测试代码和结果截图。很明显当我使用new TextView这种方式时，字体显示是有问题的。作为一只小菜鸡，读源码比较困难，原理只是看了作者简书上的介绍，好奇为什么会出现这种现象。
`public class TestView extends LinearLayout {
    public TestView(Context context, @Nullable AttributeSet attrs) {
        super(context, attrs);
        setWillNotDraw(false);
        TextView textView = new TextView(getContext());
        textView.setTextSize(AutoSizeUtils.sp2px(getContext(), 20));
        textView.setTextColor(Color.RED);
        textView.setText("红色：+ 0.56");
        addView(textView);
    }

    @Override
    protected void onDraw(Canvas canvas) {
        super.onDraw(canvas);
        Paint mPaint = new Paint();
        mPaint.setAntiAlias(true);
        mPaint.setDither(true);
        mPaint.setColor(Color.GREEN);
        mPaint.setStyle(Paint.Style.FILL);
        mPaint.setTextSize(AutoSizeUtils.sp2px(getContext(), 20));
        //当前温度
        Rect textRect = new Rect();
        String tip = "绿色：+ 0.56";
        mPaint.getTextBounds(tip, 0, tip.length(), textRect);
        canvas.drawText(tip, 0, textRect.height(), mPaint);
    }
}`
![image](https://user-images.githubusercontent.com/23740416/62452965-d570c300-b7a3-11e9-9b46-ff548481d7fd.png)

**Comment by cocwong** [comment]
TextView的setTextSize(float size)方法的默认单位就是SP，所以不用再转成px

**Comment by Rachel-hsw** [comment]
> TextView的setTextSize（float size）方法的默认单位就是SP，所以不用再转成px

哦哦好，那Paint的setTextSize的默认单位不是SP？我怎么知道她的默认单位是什么

**Comment by cocwong** [comment]
> > TextView的setTextSize（float size）方法的默认单位就是SP，所以不用再转成px
> 
> 哦哦好，那Paint的setTextSize的默认单位不是SP？我怎么知道她的默认单位是什么

Paint的单位是pixel

**Comment by JessYanCoding** [comment]
这位兄弟说的是对的，setTextSize 的默认单位就是 SP
![image](https://user-images.githubusercontent.com/15711968/63071830-72292280-bf53-11e9-9983-d6eff0ca2dcb.png)
