### ISSUE TITLE
自定义keyboard显示异常

### ISSUE THREAD

**Issue by HelloJerryC** [JessYanCoding/AndroidAutoSize#202]
#72 # Environment
- [x] Autosize Version: v1.1.2

### Bug Description:
我使用了自定义的键盘，然后键盘里的布局宽度计算使用的是百分比的方式，使用了这个适配方案之后，宽度错乱了，键盘的显示溢出，并且可点击范围跟实际显示的范围显示不到一起去了。

### Screenshot
![image](https://user-images.githubusercontent.com/39262378/62694083-3e577580-ba06-11e9-808c-81c47465cf3f.png)

**Comment by JessYanCoding** [comment]
可能是你自己布局的问题，框架制作了一件事就是修改 density，和可点击范围没有什么关系，只要设计图和你布局的实际值一直就没什么问题。

**Comment by HelloJerryC** [comment]
也许吧，不知道是不是有人用自定义键盘设置成功的例子，自定义键盘的布局比较特殊，我不是用dp去衡量而是用百分比去设置的，后面没办法，只好把那个设置了自定义键盘的界面不修改density

**Comment by JessYanCoding** [comment]
你都用百分比了，最好还是让那个页面取消掉适配
