### ISSUE TITLE
建议添加字体大小修改呀

### ISSUE THREAD

**Issue by zeroplucky** [JessYanCoding/AndroidAutoSize#203]
### Environment
- [x] Autosize Version: 
- [x] Target Android Version: 
- [x] Device Model: 
- [x] Device Resolution: 
- [x] Design Size On AndroidManifest: 

### Log:

```log


```

### Related Code:
```java
  

```

**Comment by JessYanCoding** [comment]
字体大小你自己通过 sp 控制啊，这不需要框架实现 吧

**Comment by zeroplucky** [comment]
@JessYanCoding 
   /**
     * 最初的 {@link DisplayMetrics#scaledDensity}
     */
    private float mInitScaledDensity;
  
  我的意思是，在应用内动态设置应用的字体大小。就是添加一个额外的功能。

**Comment by EvanZch** [comment]
同求，使用框架后，没办法实现应用内动态更改字体大小

**Comment by EvanZch** [comment]
> @JessYanCoding
> /**
> * 最初的 {@link DisplayMetrics#scaledDensity}
> */
> private float mInitScaledDensity;
> 
> 我的意思是，在应用内动态设置应用的字体大小。就是添加一个额外的功能。

你好，这个问题你处理了吗？

**Comment by zombiu** [comment]
> > @JessYanCoding
> > /**
> > 
> > * 最初的 {@link DisplayMetrics#scaledDensity}
> >   */
> >   private float mInitScaledDensity;
> > 
> > 我的意思是，在应用内动态设置应用的字体大小。就是添加一个额外的功能。
> 
> 你好，这个问题你处理了吗？

动态修改字体确实不知道怎么解决这个问题！

**Comment by JessYanCoding** [comment]
https://github.com/JessYanCoding/AndroidAutoSize/blob/master/autosize/src/main/java/me/jessyan/autosize/AutoSize.java#L176

scale 就是字体放大的倍数，更改这个就可以了

**Comment by gys0000** [comment]
同求，在代码中动态改变时，AutoSizeUtils这个类设置的，和资源文件中设置的字体大小结果不一样。

**Comment by gys0000** [comment]
这个直接在代码中动态的填入你想设置的sp数值就OK了，比如你想设置的字体大小为10sp，那么tvContent.setTextSize(10)。就OK了。。。。。我想你的问题可能是这个，，，

**Comment by JessYanCoding** [comment]
https://github.com/JessYanCoding/AndroidAutoSize/commit/4fefc9cd27eff0919d8a1b6d83ceb0d0059bb194
