### ISSUE TITLE
折叠屏适配

### ISSUE THREAD

**Issue by SjAndy88** [JessYanCoding/AndroidAutoSize#204]
三星折叠屏适配，有在模拟器上实现折叠的文档
[三星折叠屏适配.zip](https://github.com/JessYanCoding/AndroidAutoSize/files/3500857/default.zip)

**Comment by SjAndy88** [comment]
自己试了下，感觉效果不太好

**Comment by JessYanCoding** [comment]
这个框架和你是全面屏还是折叠屏，用什么布局，用什么 View 都没什么关系，本质只是更改 density，只要 density 更改正确，怎么显示就是你布局自己的事情
