### ISSUE TITLE
华为某款全面屏适手机配有问题

### ISSUE THREAD

**Issue by 798146512** [JessYanCoding/AndroidAutoSize#205]
![微信图片_20190815172253](https://user-images.githubusercontent.com/22190566/63085956-648a9180-bf81-11e9-8488-da0f19625d7b.jpg)
![微信图片_20190815172257](https://user-images.githubusercontent.com/22190566/63085959-66545500-bf81-11e9-8f1c-8afec4a44b4d.jpg)

**Comment by 798146512** [comment]
应该是底部的那个按键栏占了空间

**Comment by 798146512** [comment]
第一张图是全面屏，底部带按键栏的，第二张图是正常的图

**Comment by JessYanCoding** [comment]
setScreenHeight  设置一个去掉导航栏的屏幕高度，或者自己在布局上作出跳转
