### ISSUE TITLE
华为Mate8 有虚拟导航按键适配不成功

### ISSUE THREAD

**Issue by simplepeng** [JessYanCoding/AndroidAutoSize#207]
### Environment
- [x] Autosize Version: 1.1.2
- [x] Target Android Version: Android 6.0 
- [x] Device Model: HuaWei NXT-AL10
- [x] Device Resolution: 1080px * 1920px 
- [x] Design Size On AndroidManifest: 375*647

### Log:

```log
08-15 20:39:57.216 10147-10147/com.youloft.rhythm D/AndroidAutoSize: designWidthInDp = 375, designHeightInDp = 647, screenWidth = 1080, screenHeight = 1920
08-15 20:39:57.216 10147-10147/com.youloft.rhythm D/AndroidAutoSize: initDensity = 3.0, initScaledDensity = 3.0

```

### Screenshot
![image](https://user-images.githubusercontent.com/12198830/63095008-a8d75b00-bf9c-11e9-8e44-38718e68b9ba.png)
![image](https://user-images.githubusercontent.com/12198830/63095020-b55bb380-bf9c-11e9-96ef-e5b59c4c53bd.png)

### Related Code:
```java
  AutoSizeConfig.getInstance().setAutoAdaptStrategy { target, activity ->
            AutoSizeConfig.getInstance().screenWidth = ScreenUtils.getScreenSize(activity)[0]
            AutoSizeConfig.getInstance().screenHeight = ScreenUtils.getScreenSize(activity)[1]
        }

```

### Others:
如题：华为Mate8 有虚拟导航按键适配不成功，一加3同样有虚拟导航键，用了上面的代码适配成功了，看了文章里面的原理还是不清楚改怎么解决，麻烦作者帮忙看看，谢谢了。

**Comment by 798146512** [comment]
我这边也有一款带虚拟按键的适配不了

**Comment by sdgtwsf0115** [comment]
请问这个问题解决了吗

**Comment by simplepeng** [comment]
@sdgtwsf0115 没有

**Comment by JessYanCoding** [comment]
以高度为基准适配
