### ISSUE TITLE
建议新增API:stopCustomFragment

### ISSUE THREAD

**Issue by liangxianshen** [JessYanCoding/AndroidAutoSize#208]
因为对于一个老项目来说， 不可能针对所有Fragment都去开启适配，历史原因，测试起来比较费劲。所以就只能针对某些fragment进行开启。目前没有提供关闭fragment适配的api，我使用了反射将isCustomFragment置成了false

**Comment by mawenjie1234** [comment]
新增了CancelAdapt，可以使用这个。

**Comment by JessYanCoding** [comment]
CancelAdapt 一直都有
