### ISSUE TITLE
基于宽没有适配成功，日志没有适配成功的提示。

### ISSUE THREAD

**Issue by hanyulang** [JessYanCoding/AndroidAutoSize#21]
### Environment
- [x] Autosize Version: v0.7.0 
- [x] Target Android Version: Android 8.0
- [x] Device Model: 华为Mate9
- [x] Device Resolution: 1080px * 1920px 
- [x] Design Size On AndroidManifest:  360dp * 640dp

### Bug Description:
现在是基于宽适配，但是没有达到预期效果，日志好像没有显示适配成功的字眼。

### Log:

<img width="1155" alt="qq20180823-170940 2x" src="https://user-images.githubusercontent.com/13556989/44516315-594ab000-a6f7-11e8-9008-844265035dcb.png">
<img width="521" alt="qq20180823-170902 2x" src="https://user-images.githubusercontent.com/13556989/44516316-594ab000-a6f7-11e8-8119-113ccd905269.png">

**Comment by hanyulang** [comment]
断点调试后onActivityCreated执行了  而且这次起作用了，难道之前的现象是缓存或Freeline导致的？

**Comment by JessYanCoding** [comment]
... 这个就不排除了，证明框架照常运转了的，可能是其他影响了，你在调试下

**Comment by hanyulang** [comment]
好的 谢谢！
