### ISSUE TITLE
依赖库显示问题

### ISSUE THREAD

**Issue by creativityingenuity** [JessYanCoding/AndroidAutoSize#211]
用的easeui，依赖方式是引入lib,图片和文字都显示很小，查了iss也没看到好的解决方案，我看解决方案是这个界面使用副单位？  可是这个是依赖库的自定义view 里面的文字大小 图片都是库里面设置的。我试了下不起作用，请教下解决方式

**Comment by JessYanCoding** [comment]
副单位是让你自己的项目全部页面使用副单位，不是让三方库的页面使用副单位
