### ISSUE TITLE
对于Fragment的子Fragment会适配失效，不知道是什么原因

### ISSUE THREAD

**Issue by WangTao0127** [JessYanCoding/AndroidAutoSize#212]

**Comment by cocowobo** [comment]
我这边ok的,我的页面都是fragment嵌套fragment的

**Comment by WangTao0127** [comment]
将
`
@Override
    public Resources getResources() {
        //需要升级到 v1.1.2 及以上版本才能使用 AutoSizeCompat
        AutoSizeCompat.autoConvertDensityOfGlobal((super.getResources());//如果没有自定义需求用这个方法
        AutoSizeCompat.autoConvertDensity((super.getResources(), 667, false);//如果有自定义需求就用这个方法
        return super.getResources();
    }
`
修改为
`
    override fun getResources(): Resources {
        val res = super.getResources()
        AutoSizeCompat.autoConvertDensityOfGlobal(res)//如果没有自定义需求用这个方法
        AutoSizeCompat.autoConvertDensity(res, 360f, true);//如果有自定义需求就用这个方法
        return res
    }
`
