### ISSUE TITLE
小米8偶现所有界面变大

### ISSUE THREAD

**Issue by Florizt** [JessYanCoding/AndroidAutoSize#213]
![QQ图片20190902115029](https://user-images.githubusercontent.com/30947620/64089286-ef3c0080-cd77-11e9-8c6f-bb8b7255683b.jpg)
小米8一启动应用就这样了，所有界面都变得特别大，请问这是什么原因啊，急

**Comment by Florizt** [comment]
@JessYanCoding

**Comment by cocowobo** [comment]
你怕不是突然变成了高度适配了

**Comment by xiaowifi** [comment]
我设置全屏后 也是这样的，但是 当我那个activity 取消适配的时候，就没问题了，脑阔痛

**Comment by Florizt** [comment]
> 你怕不是突然变成了高度适配了

默认是宽度适配，怎么自动变成高度适配了，再说高度适配也不会变得这么大呀

**Comment by Florizt** [comment]
> 我设置全屏后 也是这样的，但是 当我那个activity 取消适配的时候，就没问题了，脑阔痛，哦哦，我用的主题是Theme.AppCompat.Light.NoActionBar

跟theme无关，目前我也找不出原因，反正就是偶先，一启动app就这样了，坐等群主修复把

**Comment by liweiGe** [comment]
> > 我设置全屏后 也是这样的，但是 当我那个activity 取消适配的时候，就没问题了，脑阔痛，哦哦，我用的主题是Theme.AppCompat.Light.NoActionBar
> 
> 跟theme无关，目前我也找不出原因，反正就是偶先，一启动app就这样了，坐等群主修复把

你那个是不是有横竖屏切换操作?

**Comment by JessYanCoding** [comment]
如果有横竖屏切换，可能是框架获取到的屏幕尺寸没对，
```java 
AutoSizeConfig.getInstance()
                //屏幕适配监听器
                .setOnAdaptListener(new onAdaptListener() {
                    @Override
                    public void onAdaptBefore(Object target, Activity activity) {
                        //使用以下代码, 可支持 Android 的分屏或缩放模式, 但前提是在分屏或缩放模式下当用户改变您 App 的窗口大小时
                        //系统会重绘当前的页面, 经测试在某些机型, 某些情况下系统不会重绘当前页面, ScreenUtils.getScreenSize(activity) 的参数一定要不要传 Application!!!
                        AutoSizeConfig.getInstance().setScreenWidth(ScreenUtils.getScreenSize(activity)[0]);
                        AutoSizeConfig.getInstance().setScreenHeight(ScreenUtils.getScreenSize(activity)[1]);
                    }

                    @Override
                    public void onAdaptAfter(Object target, Activity activity) {
                        
                    }
                });
```

**Comment by Florizt** [comment]
> 如果有横竖屏切换，可能是框架获取到的屏幕尺寸没对，
> 
> ```java
> AutoSizeConfig.getInstance()
>                 //屏幕适配监听器
>                 .setOnAdaptListener(new onAdaptListener() {
>                     @Override
>                     public void onAdaptBefore(Object target, Activity activity) {
>                         //使用以下代码, 可支持 Android 的分屏或缩放模式, 但前提是在分屏或缩放模式下当用户改变您 App 的窗口大小时
>                         //系统会重绘当前的页面, 经测试在某些机型, 某些情况下系统不会重绘当前页面, ScreenUtils.getScreenSize(activity) 的参数一定要不要传 Application!!!
>                         AutoSizeConfig.getInstance().setScreenWidth(ScreenUtils.getScreenSize(activity)[0]);
>                         AutoSizeConfig.getInstance().setScreenHeight(ScreenUtils.getScreenSize(activity)[1]);
>                     }
> 
>                     @Override
>                     public void onAdaptAfter(Object target, Activity activity) {
>                         
>                     }
>                 });
> ```

**Comment by Florizt** [comment]
> 如果有横竖屏切换，可能是框架获取到的屏幕尺寸没对，
> 
> ```java
> AutoSizeConfig.getInstance()
>                 //屏幕适配监听器
>                 .setOnAdaptListener(new onAdaptListener() {
>                     @Override
>                     public void onAdaptBefore(Object target, Activity activity) {
>                         //使用以下代码, 可支持 Android 的分屏或缩放模式, 但前提是在分屏或缩放模式下当用户改变您 App 的窗口大小时
>                         //系统会重绘当前的页面, 经测试在某些机型, 某些情况下系统不会重绘当前页面, ScreenUtils.getScreenSize(activity) 的参数一定要不要传 Application!!!
>                         AutoSizeConfig.getInstance().setScreenWidth(ScreenUtils.getScreenSize(activity)[0]);
>                         AutoSizeConfig.getInstance().setScreenHeight(ScreenUtils.getScreenSize(activity)[1]);
>                     }
> 
>                     @Override
>                     public void onAdaptAfter(Object target, Activity activity) {
>                         
>                     }
>                 });
> ```

没有切换横竖屏，项目只能竖屏
