### ISSUE TITLE
小米手机MM副单位兼容问题

### ISSUE THREAD

**Issue by wanggq654321** [JessYanCoding/AndroidAutoSize#215]
//    /**
//     * 给几大 {@link DisplayMetrics} 赋值
//     *
//     * @param activity      {@link Activity}
//     * @param density       {@link DisplayMetrics#density}
//     * @param densityDpi    {@link DisplayMetrics#densityDpi}
//     * @param scaledDensity {@link DisplayMetrics#scaledDensity}
//     * @param xdpi          {@link DisplayMetrics#xdpi}
//     */
//    private static void setDensity(Activity activity, float density, int densityDpi, float scaledDensity, float xdpi) {
//        //兼容 MIUI
//        DisplayMetrics activityDisplayMetricsOnMIUI = getMetricsOnMiui(activity.getResources());
//        DisplayMetrics appDisplayMetricsOnMIUI = getMetricsOnMiui(AutoSizeConfig.getInstance().getApplication().getResources());
//
//        if (activityDisplayMetricsOnMIUI != null) {
//            setDensity(activityDisplayMetricsOnMIUI, density, densityDpi, scaledDensity, xdpi);
//        } else {
//            DisplayMetrics activityDisplayMetrics = activity.getResources().getDisplayMetrics();
//            setDensity(activityDisplayMetrics, density, densityDpi, scaledDensity, xdpi);
//        }
//
//        if (appDisplayMetricsOnMIUI != null) {
//            setDensity(appDisplayMetricsOnMIUI, density, densityDpi, scaledDensity, xdpi);
//        } else {
//            DisplayMetrics appDisplayMetrics = AutoSizeConfig.getInstance().getApplication().getResources().getDisplayMetrics();
//            setDensity(appDisplayMetrics, density, densityDpi, scaledDensity, xdpi);
//        }
//    }

    /**
     * 给几大 {@link DisplayMetrics} 赋值
     *
     * @param activity      {@link Activity}
     * @param density       {@link DisplayMetrics#density}
     * @param densityDpi    {@link DisplayMetrics#densityDpi}
     * @param scaledDensity {@link DisplayMetrics#scaledDensity}
     * @param xdpi          {@link DisplayMetrics#xdpi}
     */
    private static void setDensity(Activity activity, float density, int densityDpi, float scaledDensity, float xdpi) {
        final DisplayMetrics activityDisplayMetrics = activity.getResources().getDisplayMetrics();
        final DisplayMetrics appDisplayMetrics = AutoSizeConfig.getInstance().getApplication().getResources().getDisplayMetrics();

        setDensity(activityDisplayMetrics, density, densityDpi, scaledDensity, xdpi);

        setDensity(appDisplayMetrics, density, densityDpi, scaledDensity, xdpi);

        //兼容 MIUI
        DisplayMetrics activityDisplayMetricsOnMIUI = getMetricsOnMiui(activity.getResources());
        DisplayMetrics appDisplayMetricsOnMIUI = getMetricsOnMiui(AutoSizeConfig.getInstance().getApplication().getResources());

        if (activityDisplayMetricsOnMIUI != null) {
            setDensity(activityDisplayMetricsOnMIUI, density, densityDpi, scaledDensity, xdpi);
        }

        if (appDisplayMetricsOnMIUI != null) {
            setDensity(appDisplayMetricsOnMIUI, density, densityDpi, scaledDensity, xdpi);
        }
    }

以上我注释的代码是新版1.1.2 版本代码，开放出来使用的代码是 1.1.0的代码，使用1.1.0代码在小米4c开起来ok，使用以上代码是好的，望作者知晓；

**Comment by wanggq654321** [comment]
请问这个代码还原成 1.1.0代码有什么问题么

**Comment by JessYanCoding** [comment]
https://github.com/JessYanCoding/AndroidAutoSize/issues/1

**Comment by JessYanCoding** [comment]
```java
 private static void setDensity(Activity activity, float density, int densityDpi, float scaledDensity, float xdpi) {
        //兼容 MIUI
        DisplayMetrics activityDisplayMetricsOnMIUI = getMetricsOnMiui(activity.getResources());
        DisplayMetrics appDisplayMetricsOnMIUI = getMetricsOnMiui(AutoSizeConfig.getInstance().getApplication().getResources());

        if (activityDisplayMetricsOnMIUI != null) {
            setDensity(activityDisplayMetricsOnMIUI, density, densityDpi, scaledDensity, xdpi);
        } 
        DisplayMetrics activityDisplayMetrics = activity.getResources().getDisplayMetrics();
        setDensity(activityDisplayMetrics, density, densityDpi, scaledDensity, xdpi);
        

        if (appDisplayMetricsOnMIUI != null) {
            setDensity(appDisplayMetricsOnMIUI, density, densityDpi, scaledDensity, xdpi);
        }
        DisplayMetrics appDisplayMetrics = AutoSizeConfig.getInstance().getApplication().getResources().getDisplayMetrics();
        setDensity(appDisplayMetrics, density, densityDpi, scaledDensity, xdpi);
        }
    }
```
把 if (activityDisplayMetricsOnMIUI != null)  和  if (appDisplayMetricsOnMIUI != null)  后面的 else 去掉，v1.1.0 是不管  activityDisplayMetricsOnMIUI 和 appDisplayMetricsOnMIUI 是否为 null，都会给 activityDisplayMetrics  和 appDisplayMetrics 设置 density，在 v1.1.2 后就改成，如果 activityDisplayMetricsOnMIUI 和 appDisplayMetricsOnMIUI 不为 null ，就不给 activityDisplayMetrics  和 appDisplayMetrics 设置 density，有可能是这个问题，你可以试一试

**Comment by JessYanCoding** [comment]
https://github.com/JessYanCoding/AndroidAutoSize/commit/c1a891e4e19a2a2db7b1347852fd3eaed8ba3423
