### ISSUE TITLE
每个Activity都被调整了两次

### ISSUE THREAD

**Issue by totoks** [JessYanCoding/AndroidAutoSize#217]
#117 # Environment

### Bug Description:
看Autosize的日志，每个Activity都被调整了两次，日志是这样的
WelcomeActivity has been adapted! 
WelcomeActivity has been adapted! 
每个Activity都显示了两次日志，具体源码还没有看，有没有遇到这个问题的同学分享交流一下。

### Screenshot
![image](https://user-images.githubusercontent.com/9283254/64327642-a6e24400-cffe-11e9-8c45-d563dd6664eb.png)

**Comment by JessYanCoding** [comment]
正常啊，onActivityCreated 和 onActivityStarted 都调用了一次，保证稳定性，框架并没有说每次 Activity 只调用一次适配
