### ISSUE TITLE
glide 图片居中问题

### ISSUE THREAD

**Issue by seefutureLee** [JessYanCoding/AndroidAutoSize#218]
glide 适配图片有问题   imageview设置的fitxy  但是展示出来过小的图片  就跑到左上角了

**Comment by mawenjie1234** [comment]
应该和fitxy没什么关系。

**Comment by mawenjie1234** [comment]
bitmap 创建需要传DisplayMetrics，你可以在你glide 的transform 里面写。
Bitmap bmpGrayscale = Bitmap.createBitmap(getContext().getResources().getDisplayMetrics(),
                width, height, config);

**Comment by seefutureLee** [comment]
👌

**Comment by zhuzhushang** [comment]
@mawenjie1234 我这是用glide的设置圆角才有这个问题，跟踪代码，是在transform方法中这行代码改变的density，
![image](https://user-images.githubusercontent.com/11988439/130425537-0897531d-5512-4b16-a3ae-565554b00549.png)
这行代码是Glide的，不知道用什么方法改
```
Bitmap bmpGrayscale = Bitmap.createBitmap(getContext().getResources().getDisplayMetrics(),
width, height, config);
 ```
glide代码：
```
    @NonNull
    public Bitmap get(int width, int height, Config config) {
        Bitmap result = this.getDirtyOrNull(width, height, config);
        if (result != null) {
            result.eraseColor(0);
        } else {
            result = Bitmap.createBitmap(width, height, config);
        }

        return result;
    }
```

**Comment by JessYanCoding** [comment]
你重新 createBitmap 个新的 bitmap，宽高和内容都 copy 一下 pool.get() 获取的这个 bitmap 就可以了，对 bitmap 的备份，网上教学内容很多

**Comment by zhuzhushang** [comment]
@JessYanCoding  因为我这边发现是在`transform`方法中调用了
`Bitmap result = pool.get(toTransform.getWidth(), toTransform.getHeight(), Bitmap.Config.ARGB_8888); `方法后改变了bitmap的density,但是宽高并没有变化，所以我这里直接调用了bitmap的setdensity方法
`result.setDensity(getResources().getDisplayMetrics().densityDpi);`
目前还没发现问题。

**Comment by MaryDQ** [comment]
兄弟，你这个方案现在没有效果啊
