### ISSUE TITLE
透明状态栏高度适配问题

### ISSUE THREAD

**Issue by wudifamo** [JessYanCoding/AndroidAutoSize#22]
### Environment
- [x] Autosize Version: 0.7.0
- [x] Target Android Version: 5.0
- [x] Device Model: simulator
- [x] Device Resolution: 1440*2560
- [x] Design Size On AndroidManifest: 360dp * 640dp -->

我自定义了一个titlebar,并且设置为全屏模式,正常情况下我会获取状态栏高度(除刘海屏外一般为25dp左右),然后设置titlebar的topPadding为状态栏高度以实现透明状态栏.
问题出在使用该框架后25dp会被放大,但是手机的状态栏还是25dp,导致titlebar上面padding的空间会变大,该如何解决?

![_20180823174603](https://user-images.githubusercontent.com/14868379/44518286-70d86780-a6fc-11e8-83bb-42f5b1e23c8c.png)

**Comment by JessYanCoding** [comment]
Resources.getSystem().getDisplayMetrics().density * dp = px 这个求出的是未经修改的像素

**Comment by wudifamo** [comment]
好吧解决了,系统提供的api状态栏高度取出来是转了dp后的值,我现在的处理是转回px再用您提供的公式重新计算高度
