### ISSUE TITLE
首页菜单，针对一个Fragment适配会导致其他的Fragment也跟着适配

### ISSUE THREAD

**Issue by zhoulongwu11** [JessYanCoding/AndroidAutoSize#220]
首页菜单，针对一个Fragment适配会导致其他的Fragment也跟着适配

**Comment by zhoulongwu11** [comment]
#13

**Comment by zhoulongwu11** [comment]
找到解决方案了，感觉这些问题在issues都能搜到- -.....

**Comment by zhoulongwu11** [comment]
@Override
    public Resources getResources() {
        //需要升级到 v1.1.2 及以上版本才能使用 AutoSizeCompat
        AutoSizeCompat.autoConvertDensityOfGlobal((super.getResources());//如果没有自定义需求用这个方法
        AutoSizeCompat.autoConvertDensity((super.getResources(), 667, false);//如果有自定义需求就用这个方法
        return super.getResources();
    }

**Comment by zhoulongwu11** [comment]
#13 适配失效问题用这个都可以解决 详情

**Comment by zhoulongwu11** [comment]
适配失效问题用这个都可以解决   #13 详情

**Comment by mawenjie1234** [comment]
老哥，可以close掉
