### ISSUE TITLE
sdk字体还是变大了

### ISSUE THREAD

**Issue by docwei2050** [JessYanCoding/AndroidAutoSize#221]
### Environment
- [x] Autosize Version:   1.1.2'
- [x] Target Android Version: Android 9.0
- [x] Device Model: 红米
- [x] Device Resolution:080px * 1920px
- [x] Design Size On AndroidManifest: 360dp * 640dp

### Bug Description:

   宿主主工程接入了这个框架，我们sdk没有接入，只是在基类Activity实现了CancelAdapt，但是Fragment里面的字体还是变大了。

### Log:

```log


```

### Related Code:
```java
  

```

**Comment by mawenjie1234** [comment]
是不是调用了setCustomFragment（true）了。使用这个后，fragment会自动缩放。这个其实是一个问题，应该每个activity都有自己的值才对。

**Comment by JessYanCoding** [comment]
@Override
    public Resources getResources() {
        AutoSizeCompat. cancelAdapt(super.getResources());
        return super.getResources();
    }
