### ISSUE TITLE
可以设置默认不自适应吗  想适配的时候在继承 CustomAdapt

### ISSUE THREAD

**Issue by cl2980457390** [JessYanCoding/AndroidAutoSize#222]
项目比较大 想默认不自适应，想适配时就继承CustomAdapt，通过多个版本迭代来实现适配，
不需要为每给Activity 设置CancelAdapt ，的设置有吗。

**Comment by JessYanCoding** [comment]
不开启 dp 的适配，在需要适配的页面使用副单位，就可以分阶段逐步完成迁移，不会影响之前使用 dp 的旧页面。https://github.com/JessYanCoding/AndroidAutoSize/tree/master/demo-subunits

**Comment by JessYanCoding** [comment]
https://github.com/JessYanCoding/AndroidAutoSize/blob/master/demo/src/main/java/me/jessyan/autosize/demo/BaseApplication.java#L119   如果只想使用 DP，不想使用副单位，也不想每个 Activity 
 实现 CancelAdapt，你可以使用 ExternalAdaptManager，将需要取消的 Activity 都传进去，虽然也需要一个个将类名传进去，但只需要在初始化时传，不需要去修改每个 Activity

density 的修改是全局的，只可能默认开启，框架提供的取消操作，也是在每个 Activity 绘制页面之前，将 density 还原为默认的，所以不只能通过上述的方式实现取消操作，推荐第一种方式，更稳定

**Comment by fanturbo** [comment]
@JessYanCoding @cl2980457390 修改默认的AutoAdaptStrategy应该就可以啊。

**Comment by JessYanCoding** [comment]
https://github.com/JessYanCoding/AndroidAutoSize/issues/233
