### ISSUE TITLE
横屏应用使用手机运行，锁屏之后再次打开recyclerview条目可见的正常，当把不可见的滑至可见整个条目变小

### ISSUE THREAD

**Issue by zhongwls** [JessYanCoding/AndroidAutoSize#223]
adapter中打印Density 都是一样的。没有变化。麻烦帮看看

**Comment by XiongHantian** [comment]
@zhongwls 请问你这个问题解决了吗，我在项目中也遇到了同样的问题

**Comment by JessYanCoding** [comment]
可能是 recyclerview 复用之前的 View 导致的，最好在  onBindHodlder  中使用 AutoSize.autoConvertDensityOfGlobal(activity) 设置 Density 后，再手动刷新这个 Item View 的所有 UI 内容
