### ISSUE TITLE
在ManiFest中配置设计尺寸可以是float值

### ISSUE THREAD

**Issue by mawenjie1234** [JessYanCoding/AndroidAutoSize#224]
- [x] Autosize Version: v1.1.2 
- [x] Design Size On AndroidManifest: 250dp * 444.4dp

项目同时有android何ios，1920*1080 像素怼xxhdpi 宽度250，高度就是444.4。因此应该用float类型才对。我看计算的时候，仍然用的float

**Comment by JessYanCoding** [comment]
用 math.round() 取整

**Comment by mawenjie1234** [comment]
我觉得不能直接取整，我看计算本身也是float值，就应该用float才对，是这个意思。我当然可以在用的时候写444取整。但是如果写444.4，应该才是合理的。

**Comment by JessYanCoding** [comment]
那你可以给我提 PR，我这测试没问题就给你合并

**Comment by mawenjie1234** [comment]
ok
