### ISSUE TITLE
iqoo pro手机换系统字体后，从后台切换到前台后偶现字体变的非常大

### ISSUE THREAD

**Issue by RiceRichhonour** [JessYanCoding/AndroidAutoSize#227]
![QQ截图20191012112741](https://user-images.githubusercontent.com/26269539/66694202-884d2800-ece3-11e9-8c77-d8fd670ff759.png)

**Comment by JessYanCoding** [comment]
https://github.com/JessYanCoding/AndroidAutoSize/issues/13#11  ，或者 AutoSizeConfig.getInstance().setExcludeFontScale(true);，或者使用 dp 或 副单位作为字体的单位
