### ISSUE TITLE
简易集成Tinker等情况下初始化失败。

### ISSUE THREAD

**Issue by YangKee** [JessYanCoding/AndroidAutoSize#229]
initCompatMultiProcess(Context context) 方法会提示找不到provider，所以导致初始化失败。
AutoSizeConfig的init(Context context)方法不是公开的，不方便自己手动初始化。
建议这个方法公开。

**Comment by JessYanCoding** [comment]
提示日志是什么

**Comment by 1756211858** [comment]
我也遇到了集成tinker之后，AndroidAutoSize无效了。

**Comment by changtuixiaopangdun** [comment]
我也遇到了这个问题

**Comment by JessYanCoding** [comment]
https://github.com/JessYanCoding/AndroidAutoSize/commit/0fdd9f83cd4dcf1abcde69d228d80a3e27acfb8f
