### ISSUE TITLE
UtilCode 中的一些解决之道，希望可以帮到你们

### ISSUE THREAD

**Issue by Blankj** [JessYanCoding/AndroidAutoSize#23]
## [屏幕适配问题汇总](https://github.com/Blankj/AndroidUtilCode/issues/597)

**Comment by JessYanCoding** [comment]
@Blankj 感谢柯基老师的分享，由于这个方案的低成本优势非常突出，但是范围不可控的劣势也同样突出，导致会出现很多问题，特别是在某些定制系统上，所以希望集大家的开源力量一起将这个方案不断完善

**Comment by JessYanCoding** [comment]
已汇总到 https://github.com/JessYanCoding/AndroidAutoSize/issues/13#5
