### ISSUE TITLE
关于自定义layout当中,自定义属性设置textsize,一直拿到的是px值,不论设置sp,还是pt,还是dp

### ISSUE THREAD

**Issue by 424385117** [JessYanCoding/AndroidAutoSize#230]
目前我的解决方案是:

> mTitle.setTextSize(TypedValue.COMPLEX_UNIT_PX,titleTextSize.toFloat())
设置textsize的时候指定px,但是不知道从框架层面上是否可以解决

**Comment by JessYanCoding** [comment]
系统会自己将你的值转换为 px，和框架无关

**Comment by 424385117** [comment]
> 系统会自己将你的值转换为 px，这和框架无关

自定义属性获取到的就是px值吗?以前没注意,都是直接settextSize
