### ISSUE TITLE
recyclerview的子布局没有被适配

### ISSUE THREAD

**Issue by lixiangkai1987** [JessYanCoding/AndroidAutoSize#231]
### Environment
- [x] Autosize Version: 
- [x] Target Android Version: 
- [x] Device Model: 
- [x] Device Resolution: 
- [x] Design Size On AndroidManifest: 

### Log:

```log


```

### Related Code:
```java
  

```

**Comment by JessYanCoding** [comment]
https://github.com/JessYanCoding/AndroidAutoSize/issues/59
