### ISSUE TITLE
关于获取手机状态栏的高度问题

### ISSUE THREAD

**Issue by ShineBao** [JessYanCoding/AndroidAutoSize#232]
获取到的高度与实际的的高度值显然不一致，导致需要手动适配状态栏时出现问题，该问题出现在刘海屏的手机上

**Comment by JessYanCoding** [comment]
项目运行时，通过不同的方法会拿到两种高度，一个是 density 更改后的状态栏高度，一个是 density 更改前的 density 高度

**Comment by yalarc** [comment]
(获取状态栏高度的两种方式贴出来了，开心不～～)
一个是 density 更改后的状态栏高度:
int resourceId = context.getResources().getIdentifier("status_bar_height", "dimen", "android");
statusBarHeight = context.getResources().getDimensionPixelSize(resourceId);
一个是 density 更改前的 density 高度:
Rect frame = new Rect();
getWindow().getDecorView().getWindowVisibleDisplayFrame(frame);
 statusBarHeight = frame.top;
