### ISSUE TITLE
我在顶层父类中 CancelAdapter，然后每个子类都根据具体情况来 CustemAdapter ， 结果CustemAdapter 不起作用，因为父类实现了CancelAdapter

### ISSUE THREAD

**Issue by yanglichuan** [JessYanCoding/AndroidAutoSize#233]
### Environment
- [x] Autosize Version: 
- [x] Target Android Version: 
- [x] Device Model: 
- [x] Device Resolution: 
- [x] Design Size On AndroidManifest: 

### Log:

```log


```

### Related Code:
```java
  

```

**Comment by JessYanCoding** [comment]
https://github.com/JessYanCoding/AndroidAutoSize/blob/master/autosize/src/main/java/me/jessyan/autosize/DefaultAutoAdaptStrategy.java#L61

框架是默认只要引入了项目，所有页面都需要屏幕适配的，只要实现了 CancelAdapt 永远不可能走到 CustomAdapt 的逻辑；

解决方案：
> 普通方式:
1.父类不要实现 CancelAdapter，让不想适配的子类实现 CancelAdapter
2.父类不要实现 CancelAdapter，将 **不需要适配** 的子类传入 [ExternalAdaptManager#addCancelAdaptOfActivity](https://github.com/JessYanCoding/AndroidAutoSize/blob/master/demo/src/main/java/me/jessyan/autosize/demo/BaseApplication.java#L119) 方法

> 高级方式:
1.父类实现 CancelAdapter，将 **需要适配** 的子类传入 [ExternalAdaptManager#addExternalAdaptInfoOfActivity](https://github.com/JessYanCoding/AndroidAutoSize/blob/master/demo/src/main/java/me/jessyan/autosize/demo/BaseApplication.java#L130) 方法

> 终极方式:
1.**AndroidAutoSize** 支持强大的自定义功能，你什么都不用改，只用自定义适配器，将你现在的适配逻辑实现到适配器中，框架就可以使用你的业务逻辑进行适配
   实现 AutoAdaptStrategy，并将这个 AutoAdaptStrategy 实现类注册给 [AndroidAutoSize](https://github.com/JessYanCoding/AndroidAutoSize/blob/master/demo/src/main/java/me/jessyan/autosize/demo/BaseApplication.java#L101)，实现类的逻辑完全复制 [DefaultAutoAdaptStrategy](https://github.com/JessYanCoding/AndroidAutoSize/blob/master/autosize/src/main/java/me/jessyan/autosize/DefaultAutoAdaptStrategy.java)，只用将 [61 行](https://github.com/JessYanCoding/AndroidAutoSize/blob/master/autosize/src/main/java/me/jessyan/autosize/DefaultAutoAdaptStrategy.java#L61) 改成

```java
if (target instanceof CancelAdapt && !target instanceof CustomAdapt) {
```

**Comment by JessYanCoding** [comment]
1. 当 **不需要适配** 的页面少于 **需要适配** 的页面就用 **普通方式**。
2.当 **不需要适配** 的页面大于 **需要适配** 的页面就用 **高级或终极方式**。
3.当然终极方式是最好的，因为这样你可以实现更多复杂的自定义业务逻辑

**Comment by yanglichuan** [comment]
谢谢大佬的详细解答
