### ISSUE TITLE
关于屏幕适配,因为autoSize,没有做任何特殊的操作, 首页是有Fragment , fragment中是Viewpager+tabLayout, 我在来回切换tabLayout的时候, 滑动下方RecyclerView, 就会造成卡顿, 我去掉了适配之后就正常了. 

### ISSUE THREAD

**Issue by snowhappy** [JessYanCoding/AndroidAutoSize#238]
### Environment
- [x] Autosize Version: 
- [x] Target Android Version: 
- [x] Device Model: 
- [x] Device Resolution: 
- [x] Design Size On AndroidManifest: 

### Log:

```log


```

### Related Code:
```java
  

```

**Comment by JessYanCoding** [comment]
框架开源一年，原理就一直没变过，仅仅只是修改 density，框架没有对 view 做任何性能损耗的操作，只是获取个 DIsplayMetrics 更改一个 density，如果更改一个 denisty 都会卡顿，那我确实也没什么办法。

**Comment by FoxTong** [comment]
好像rv滑动会用到displayMetrics计算

**Comment by JessYanCoding** [comment]
@FoxTong 不管用不用这个框架，项目中任何 DP 到 PX 的计算都会用到 displayMetrics
