### ISSUE TITLE
有没有jar包，项目需要放到系统源码编译，使用gradle引入不方便

### ISSUE THREAD

**Issue by huanyuan** [JessYanCoding/AndroidAutoSize#239]
### Environment
- [x] Autosize Version: 
- [x] Target Android Version: 
- [x] Device Model: 
- [x] Device Resolution: 
- [x] Design Size On AndroidManifest: 

### Log:

```log


```

### Related Code:
```java
  

```

**Comment by imyyq-star** [comment]
你通过Gradle先拿下来，随便打开这个库的某个文件，AS最顶部就能显示jar在哪个位置

**Comment by JessYanCoding** [comment]
自己打包
