### ISSUE TITLE
对于有刘海屏的手机 尺寸不对

### ISSUE THREAD

**Issue by Idumuzhou** [JessYanCoding/AndroidAutoSize#24]
### Screenshot

在刘海屏下面会显示成这样的效果
![device-2018-08-24-135831](https://user-images.githubusercontent.com/10207230/44567928-2102aa80-a7a7-11e8-90d7-6c308181acd9.png)

**Comment by JessYanCoding** [comment]
框架日志没有提供以及描述不清楚，这样的效果是什么意思？之前的效果是什么效果？期望的效果是什么效果？

**Comment by JessYanCoding** [comment]
https://github.com/JessYanCoding/AndroidAutoSize/issues/8
