### ISSUE TITLE
Unable to get provider me.jessyan.autosize.InitProvider: java.lang.NullPointerException: application == null

### ISSUE THREAD

**Issue by sfy666666** [JessYanCoding/AndroidAutoSize#240]
只添加了依赖和配置了设计尺寸，运行就报错，是哪里没有配置吗？

**Comment by JessYanCoding** [comment]
https://github.com/JessYanCoding/AndroidAutoSize/commit/5d3d71f5697e18234880e91d34252bdeb0732f9b

**Comment by sfy666666** [comment]
是最新的

**Comment by JessYanCoding** [comment]
https://github.com/JessYanCoding/AndroidAutoSize/releases/tag/v1.2.0

用 v1.2.0
