### ISSUE TITLE
BottomNavigationView缩小

### ISSUE THREAD

**Issue by RDSunhy** [JessYanCoding/AndroidAutoSize#241]
加入适配后 为什么BottomNavigationView底部导航栏就变成这样了？ 去掉适配就没问题

![image](https://user-images.githubusercontent.com/44076669/69513374-8cc35c80-0f82-11ea-9332-5cf76fe3f722.png)

**Comment by shapolang** [comment]
对啊，经常会有字体缩小啥的

**Comment by JessYanCoding** [comment]
填写的设计图尺寸和你布局时使用的设计图尺寸不匹配
