### ISSUE TITLE
recyclerview的item字体有时候变得很小很难看,有时候又正常

### ISSUE THREAD

**Issue by shapolang** [JessYanCoding/AndroidAutoSize#243]
### Environment
- [x] Autosize Version: 
- [x] Target Android Version: 
- [x] Device Model: 
- [x] Device Resolution: 
- [x] Design Size On AndroidManifest: 

### Log:

```log


```

### Related Code:
```java
  

```

**Comment by shapolang** [comment]
华为平板

**Comment by JessYanCoding** [comment]
https://github.com/JessYanCoding/AndroidAutoSize/issues/13#11

**Comment by SXJCLZH** [comment]
请问楼主解决了这个问题了吗？

**Comment by JessYanCoding** [comment]
可能是 recyclerview 复用之前的 View 导致的，最好在  onBindHodlder  中使用 AutoSize.autoConvertDensityOfGlobal(activity) 设置 Density 后，再手动刷新这个 Item View 的所有 UI 内容
