### ISSUE TITLE
activity+多个fragment关于屏幕旋转的问题，会导致布局错乱问题出现

### ISSUE THREAD

**Issue by yezi10086** [JessYanCoding/AndroidAutoSize#244]
### Environment
- [x] Autosize Version: 
- [x] Target Android Version: 
- [x] Device Model: 
- [x] Device Resolution: 
- [x] Design Size On AndroidManifest: 

### Log:

```log


```

### Related Code:
```java
  

```

**Comment by JessYanCoding** [comment]
https://github.com/JessYanCoding/AndroidAutoSize/blob/master/demo/src/main/java/me/jessyan/autosize/demo/CustomFragment1.java#L47
