### ISSUE TITLE
闪屏页logo没有适配效果

### ISSUE THREAD

**Issue by chenzhongyu** [JessYanCoding/AndroidAutoSize#246]
### Environment
- [x] Autosize Version: v1.1.2
- [x] Target Android Version: Android 9.0
- [x] Device Model:一加7 Pro
- [x] Device Resolution:1440px * 3120px
- [x] Design Size On AndroidManifest: 375dp * 667dp

### Bug Description:
在Launch Activity设置了theme，为了消除启动时的白屏/黑屏，theme见下面的Theme.AppStartLoadTranslucent，相关的logo布局见window_launch_background.xml，此处将使用theme显示的logo（定义为logo1）。然后activity启动完成后，在刚才logo1显示的位置，我需要显示一个相同大小的logo（定义为logo2），视觉上就是一个logo图片没有变化过。Logo2的width为wrap_content，height为wrap_content，距底40dp，水平居中，垂直距底。

logo图692px * 284px

没有适配前，Density = 3.5     DensityDpi = 560
适配后，Density = 3.84     DensityDpi = 614

但是现在我用了适配方案后，显示logo2的时候，比logo1会大一些，我认为是logo1没有适配，logo2进行了适配。我查看了历史issues，也没有找到解决办法，还请遇到类似问题的，给些建议

### Log:

```log


```

### Related Code:
```java
  <style name="Theme.AppStartLoadTranslucent" parent="Theme.AppCompat.Light.NoActionBar">
        <item name="android:windowBackground">@drawable/window_launch_background</item>
        <item name="colorPrimaryDark">@color/app_white</item>
        <item name="android:windowNoTitle">true</item>
        <item name="android:windowDrawsSystemBarBackgrounds">false</item> 
        <item name="android:windowFullscreen">true</item>
    </style>
```

```java
window_launch_background.xml

  <layer-list xmlns:android="http://schemas.android.com/apk/res/android"
    android:opacity="opaque">
    <item>
        <shape android:shape="rectangle">
            <solid android:color="@color/app_white" />
        </shape>
    </item>
    <item android:bottom="@dimen/ic_launcher_icon_bottom_margin">
        <bitmap
            android:gravity="center|bottom"
            android:src="@drawable/ic_launcher_icon" />
    </item>
</layer-list>

<dimen name="ic_launcher_icon_bottom_margin">40dp</dimen>
```

### Others:

**Comment by wtww96** [comment]
我也遇到了此问题,请问大佬解决了吗

**Comment by Harry66** [comment]
logo1都显示了 为什么要显示一样的logo2呢？不是重复显示吗？

**Comment by chenzhongyu** [comment]
> logo1都显示了 为什么要显示一样的logo2呢？不是重复显示吗？

我的logo1是为了消除启动时的白屏/黑屏，activity显示完成后，我需要显示广告（不是全屏广告），广告下面有一个部分空白，产品需要是要显示应用logo，和logo1完全一样

**Comment by JessYanCoding** [comment]
https://github.com/JessYanCoding/AndroidAutoSize/issues/13#11

在自定义Application 和 首个 Activity 都试试重写 getResources()

**Comment by lic2050** [comment]
这个解决了吗？我也遇到了这个问题，我现在的解决方法是启动页实现CancelAdapt取消适配

**Comment by majunm** [comment]
同上,取消启动页适配, 我用.9做的图片 只能做到不变形  我看有些手机分辨率超高 启动页表现的有点小气 好久好在没变形
 https://www.jianshu.com/p/a2ca4c4696a3
