### ISSUE TITLE
screenOrientation="landscape"的时候达不到所预期的效果，没有适配成功。

### ISSUE THREAD

**Issue by panyancen** [JessYanCoding/AndroidAutoSize#247]
### Environment
- [x] Autosize Version: 
- [x] Target Android Version: 
- [x] Device Model: 
- [x] Device Resolution: 
- [x] Design Size On AndroidManifest: 

### Log:

```log


```

### Related Code:
```java
  

```

**Comment by JessYanCoding** [comment]
https://github.com/JessYanCoding/AndroidAutoSize/issues/44
