### ISSUE TITLE
能否对Androidx做适配呢？v7包替换成x的包就可以了？

### ISSUE THREAD

**Issue by ukuleele** [JessYanCoding/AndroidAutoSize#250]
### Environment
- [x] Autosize Version: 
- [x] Target Android Version: 
- [x] Device Model: 
- [x] Device Resolution: 
- [x] Design Size On AndroidManifest: 

### Log:

```log


```

### Related Code:
```java
  

```

**Comment by JessYanCoding** [comment]
https://github.com/JessYanCoding/AndroidAutoSize/commit/fc595c8dfb52c5b9933dd38d821aac9d06812f9f
