### ISSUE TITLE
模拟器从横屏变成竖屏之后 适配就出现问题了...  宽高比例不对

### ISSUE THREAD

**Issue by l476175728** [JessYanCoding/AndroidAutoSize#251]
### Environment
- [x] Autosize Version: 
- [x] Target Android Version: 
- [x] Device Model: 
- [x] Device Resolution: 
- [x] Design Size On AndroidManifest: 

### Log:

```log


```

### Related Code:
```java
  

```

**Comment by JessYanCoding** [comment]
https://github.com/JessYanCoding/AndroidAutoSize/blob/master/demo/src/main/java/me/jessyan/autosize/demo/BaseApplication.java#L77
