### ISSUE TITLE
关于you must set design_height_in_dp in your AndroidManifest file，崩溃问题。

### ISSUE THREAD

**Issue by liaohuyu** [JessYanCoding/AndroidAutoSize#253]
![@{YFBZ((V`$MNLDJITHEYL1](https://user-images.githubusercontent.com/16892504/71430241-a08aeb80-2705-11ea-895c-187588586555.png)
![H2AC63T(Y1@CQUCNWRTJ5Y0](https://user-images.githubusercontent.com/16892504/71430242-a08aeb80-2705-11ea-9482-3cc65e3606d8.png)
![RYA4P 34WW@T7H}I8@05{(M](https://user-images.githubusercontent.com/16892504/71430243-a08aeb80-2705-11ea-8bde-9ebaf039e8a5.png)
，错误率很低，但偶尔还是会有这种，是机型兼容问题么？

有个初步的猜想，这里新开线程   是否考虑到了同步问题~
![_9BOK122GMUFM_5BJ64H` W](https://user-images.githubusercontent.com/16892504/71430267-c1ebd780-2705-11ea-9209-a764ebf7fd26.png)

**Comment by liaohuyu** [comment]
追加一个建议：这个值要是取不到最好给个默认值呢，或者初始化时可以传个默认值过去

**Comment by JessYanCoding** [comment]
https://github.com/JessYanCoding/AndroidAutoSize/commit/5dc75d1c22c40fc42f39d336cb6e93d5076c8613

建议使用者在低配设备上主动在 Application#onCreate 中调用 setDesignWidthInDp 替代以使用 AndroidManifest 配置设计图尺寸的方式
