### ISSUE TITLE
横竖屏切换出现页面尺寸被放大

### ISSUE THREAD

**Issue by JoinBelieve** [JessYanCoding/AndroidAutoSize#255]
### Environment
- [x] Autosize Version: 
- [x] Target Android Version: 
- [x] Device Model: 
- [x] Device Resolution: 
- [x] Design Size On AndroidManifest: 
Autosize Version: 1.1.2
Device Resolution: 1080px * 1920px
Design Size On AndroidManifest: 360dp * 640dp
设备1：
Target Android Version: Android 8.1
Device Model: 坚果Pro 2S
设备2：
Target Android Version: Android 10
Device Model: Pixel One

### Bug Description:

页面A中有三个Fragment，在Fragment1中点击按钮进入页面B（横屏），再从页面B返回到页面A时，页面被放大。在Pro2S这个设备倒是正常的。楼主有时间可以帮忙看看吗
代码：
1.三个Fragment得onCreateView中增加了AutoSize.autoConvertDensity(activity, 360f, true)
2.setOnAdaptListener(object : onAdaptListener {
                    override fun onAdaptBefore(target: Any?, activity: Activity?) {
                        AutoSizeConfig.getInstance().screenWidth = ScreenUtils.getScreenSize(activity)[0]
                        AutoSizeConfig.getInstance().screenHeight = ScreenUtils.getScreenSize(activity)[1]
                        LogUtils.d(String.format(Locale.ENGLISH, "%s onAdaptBefore!", target!!::class.java.name))
                    }

                    override fun onAdaptAfter(target: Any?, activity: Activity?) {
                        LogUtils.d(String.format(Locale.ENGLISH, "%s onAdaptAfter!", target!!::class.java.name))
                    }
                })
### Log:

```log
设备1（正常的）：
MainActivity Info: isBaseOnWidth = true, designWidthInDp = 360.000000, designWidthInSubunits = 360.000000, targetDensity = 3.000000, targetScaledDensity = 3.000000, targetDensityDpi = 480, targetXdpi = 3.000000
设备2（不正常的）：
MainActivity Info: isBaseOnWidth = true, designWidthInDp = 360.000000, designWidthInSubunits = 360.000000, targetDensity = 4.983333, targetScaledDensity = 4.983333, targetDensityDpi = 797, targetXdpi = 4.983333
```

### Related Code:
```java
  

```

**Comment by JessYanCoding** [comment]
https://github.com/JessYanCoding/AndroidAutoSize/issues/44

正常现象，你以宽为基准，只有布局宽度能正常平铺满屏幕，布局高度在不同屏幕上可能会超出屏幕或者低于屏幕，当你把设备转换为横屏，这时 1920px 变成了屏幕宽度，因为你是以宽为基准，所以框架会把布局宽度从 1080px  拉伸到 1920px，保证平铺满屏幕，高度也会以同样的比例进行拉伸，所以布局被放大了，你外面套成 ScrollView 就可以了，保证布局纵向的内容也能完成预览

如果你想横屏后还能达到你想要的布局效果，请你公司的设计师再出一套针对横屏的设计图，你根据这个横屏的设计图为所有横屏设备在创建一套布局，框架能做到的只能公式化的进行拉伸或缩小，你想要达到什么效果，框架并不知道，也不需要知道，想要更精细化更完美的适配，就自己多写一套布局
