### ISSUE TITLE
华为折叠屏平行视界显示问题

### ISSUE THREAD

**Issue by RiceRichhonour** [JessYanCoding/AndroidAutoSize#257]
大佬好，
      
是这样的，我用autosize用于项目，然后在华为折叠屏，平行视界（就是打开时候，能分屏，左右显示不同内容），然后左侧一部分图标还是很大，没有按照一半的比例显示。

进入下级下下级界面后，返回首页，首页刷新重绘了，又正常了。求解，感谢。

**Comment by JessYanCoding** [comment]
https://github.com/JessYanCoding/AndroidAutoSize/issues/13#11
