### ISSUE TITLE
WindowManager中获取DisplayMetrics问题

### ISSUE THREAD

**Issue by JuneLeo** [JessYanCoding/AndroidAutoSize#26]
WindowManager windowManager = (WindowManager) activity.getSystemService(Context.WINDOW_SERVICE);
        Display display = windowManager.getDefaultDisplay();
        DisplayMetrics metrics = new DisplayMetrics();
        display.getMetrics(metrics);
这样获取到的metrics中的density，densityDpi，scaledDensity，是否适配后的？
如果不是，是否可以考虑保存了原始density，densityDpi，scaledDensity后，hook直接修改
小弟入行时间不长，勿喷！只是提出自己的一些想法！

**Comment by JessYanCoding** [comment]
你这个方式获得的是经过框架修改后的，Resources.getSystem().getDisplayMetrics();  这个获得的是原始未经修改的
