### ISSUE TITLE
腾讯乐固加固后失效

### ISSUE THREAD

**Issue by hjhrq1991** [JessYanCoding/AndroidAutoSize#261]
乐固加固后失效，有没有解决方案？

**Comment by NateRobinson** [comment]
我也遇到了

**Comment by NateRobinson** [comment]
我用的 me.jessyan:autosize:1.1.2 并且用的最新的加固固件加固出来在大部分机型上表现正常，目前发现 MI5 ,还有部分华为机型上的却还是会不行，导致整个页面都变形了 @JessYanCoding

**Comment by BeijingSnail** [comment]
> 乐固加固后失效，有没有解决方案？

你可以使用360的加固试试

**Comment by JessYanCoding** [comment]
https://github.com/JessYanCoding/AndroidAutoSize/issues/13#11

**Comment by hjhrq1991** [comment]
万能解决方案，看这里!!! 这里要感谢 Blankj 老师提供的解决方案，在任何情况下本来适配正常的布局突然出现适配失效，适配异常等问题，只要重写 Activity 的 getResources() 方法即可，如果是 Dialog、PopupWindow 等控件出现适配失效或适配异常，同样在每次 show() 之前调用 AutoSize#autoConvertDensity() 即可
    @Override
    public Resources getResources() {
        //需要升级到 v1.1.2 及以上版本才能使用 AutoSizeCompat
        AutoSizeCompat.autoConvertDensityOfGlobal((super.getResources());//如果没有自定义需求用这个方法
        AutoSizeCompat.autoConvertDensity((super.getResources(), 667, false);//如果有自定义需求就用这个方法
        return super.getResources();
    }
