### ISSUE TITLE
平板上切换语言后显示   

### ISSUE THREAD

**Issue by TrueloveSomeGIRl** [JessYanCoding/AndroidAutoSize#263]
![a](https://user-images.githubusercontent.com/25426589/72136641-34c2a700-33c4-11ea-90e8-67ac2f4f1680.jpg)
![b](https://user-images.githubusercontent.com/25426589/72136645-35f3d400-33c4-11ea-8267-d86db015a2ca.jpg)

切换英文的时候 显示和手机正常 但是未中文的时候 展示的VIew 和手机显示天差地别

**Comment by JessYanCoding** [comment]
https://github.com/JessYanCoding/AndroidAutoSize/issues/13#11
