### ISSUE TITLE
Dielog弹出框问题

### ISSUE THREAD

**Issue by zhangzhengithubs** [JessYanCoding/AndroidAutoSize#264]
![zz](https://user-images.githubusercontent.com/47585226/72198812-c9351400-346d-11ea-96cd-d82f97dc9158.jpg)

**Comment by zhizhongbiao** [comment]
这个问题本质上和我提出那个问题是一样的issue31@作者，这是个系统的选择时间的TimePiacker弹框

**Comment by JessYanCoding** [comment]
https://github.com/JessYanCoding/AndroidAutoSize/issues/1
https://github.com/JessYanCoding/AndroidAutoSize/issues/13#11
