### ISSUE TITLE
取消单个Fragment（这里使用的是DialogFragment）没作用

### ISSUE THREAD

**Issue by zhizhongbiao** [JessYanCoding/AndroidAutoSize#265]
我的DialogFg实现了CancelAdapter并没有实现了取消适配的作用，当我在Application里面调用了 AutoSizeConfig.getInstance().setCustomFragment(true);，取消适配起作用了，但我的侧栏菜单适配出现异常，字体图标变得很大，界面刷新（侧栏菜单使用切换不同的Fg的，这里的刷新指的是连续不停切换不同的Fg界面，fg切换用的是Navigation，应该是相当以前的replay，view会被destroy的）几次又变回正常了，但是在次打开那个DialogFG（想要取消适配的DialogFg），然后侧栏适配又出现一样的适配问题，切换几遍fg又变回正常，本想着在想要取消适配的那个Dialogfg的打开之前 AutoSizeConfig.getInstance().setCustomFragment(true);，然后在其关闭之前 AutoSizeConfig.getInstance().setCustomFragment(false);，发现然并卵，请作者看看是否是存在这样的问题，谢谢

**Comment by JessYanCoding** [comment]
https://github.com/JessYanCoding/AndroidAutoSize/blob/master/demo/src/main/java/me/jessyan/autosize/demo/CustomFragment1.java#L47
