### ISSUE TITLE
小米4s android7.0出现适配问题修改，

### ISSUE THREAD

**Issue by ttdazi** [JessYanCoding/AndroidAutoSize#266]
[适配问题1.1.2](https://github.com/JessYanCoding/AndroidAutoSize/issues/163) 就是你说的这个问题，麻烦尽快修改，目前用的1.1.2，看你v1.1.2更了不少问题，

**Comment by JessYanCoding** [comment]
https://github.com/JessYanCoding/AndroidAutoSize/commit/c1a891e4e19a2a2db7b1347852fd3eaed8ba3423

这几天会更新
