### ISSUE TITLE
夜神模拟器的小问题

### ISSUE THREAD

**Issue by Android-xiaoxian** [JessYanCoding/AndroidAutoSize#267]
implementation 'me.jessyan:autosize:1.1.2'
在小米9手机 上正常适配，夜神模拟器不知道怎么回事就不能适配了，适配日志也打印了的
其他手机暂时没有试过，希望只是模拟器的问题
`01-20 10:44:30.186 5928-5928/com.xxx.xxxD/AndroidAutoSize: com.xxx.xxx.activity.TransitionActivity used the global configuration.
01-20 10:44:30.186 5928-5928/com.xxx.xxxD/AndroidAutoSize: The com.xxx.xxx.activity.TransitionActivity has been adapted! 
    TransitionActivity Info: isBaseOnWidth = true, designWidthInDp = 375.000000, designWidthInSubunits = 375.000000, targetDensity = 2.880000, targetScaledDensity = 3.312000, targetDensityDpi = 460, targetXdpi = 2.880000
`

**Comment by JessYanCoding** [comment]
https://github.com/JessYanCoding/AndroidAutoSize/issues/13#11

**Comment by Android-xiaoxian** [comment]
不好意思，我是重写了BaseActivity和BaseApplication的getResource方法导致适配失败，实在是抱歉，没看你的提醒
