### ISSUE TITLE
关于使用admob广告不能正常显示的问题

### ISSUE THREAD

**Issue by dengyiming1983** [JessYanCoding/AndroidAutoSize#268]
使用了AndroidAutoSize框架后，在xml放入一个admob广告view（adView）的时候，其设置是BANNER属性。运行后看到的效果未能正常显示，只显示一部分。
在不使用AndroidAutoSize的时候，admob广告是能正常显示出来的。
请问如何能使用该框架的同时，广告也能正常显示。谢谢

例如能否特定组件取消适配的呢？请问有没有相关方法？
<CancelAdaptView>
       <Button
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:text="button"/>
</CancelAdaptView>
希望实现以上这种方法可以取消特定控件适配。

**Comment by JessYanCoding** [comment]
issues 中回答过多次，自己找找，副单位或取消适配都有api
