### ISSUE TITLE
通过默认配置项目适配失败

### ISSUE THREAD

**Issue by XuanJiAndroid** [JessYanCoding/AndroidAutoSize#27]
### Environment
- [x] Autosize Version: 0.8.0
- [x] Target Android Version: API28
- [x] Device Model: Nexus 5x
- [x] Device Resolution: 750*1334
- [x] Design Size On AndroidManifest: 750*1334

### Bug Description:
适配失败，看日志像是1比1输出，但这个跑出来的效果差很远

### Log:

```log
08-27 08:10:28.119 4224-4224/com.zhixiang.balancewallet D/AndroidAutoSize: designWidthInDp = 750, designHeightInDp = 1334, screenWidth = 750, screenHeight = 1334
08-27 08:10:28.120 4224-4224/com.zhixiang.balancewallet D/AndroidAutoSize: initDensity = 2.0, initScaledDensity = 2.0
08-27 08:10:28.214 4224-4224/com.zhixiang.balancewallet D/AndroidAutoSize: com.zhixiang.balancewallet.ui.MainActivity used the global configuration.
08-27 08:10:28.216 4224-4224/com.zhixiang.balancewallet D/AndroidAutoSize: The com.zhixiang.balancewallet.ui.MainActivity has been adapted! 
    MainActivity Info: isBaseOnWidth = true, designWidthInDp = 750.000000, targetDensity = 1.000000, targetScaledDensity = 1.000000, targetDensityDpi = 160

```

### Screenshot

layout文件预览效果
![1535357836 1](https://user-images.githubusercontent.com/21168212/44648941-2cf3a400-aa15-11e8-8146-b288f8a3f7b9.png)
模拟器跑起来的效果
![1535357854 1](https://user-images.githubusercontent.com/21168212/44648972-37ae3900-aa15-11e8-8e7b-1d4f7cff0761.png)

### Related Code:
```java
  

```

### Others:
配置只是配置了AndroidManifest文件而已，View写的是DP单位

**Comment by ljackChen001** [comment]
请在 AndroidManifest 中填写全局设计图尺寸 (单位 dp)   注意看括号里的

**Comment by JessYanCoding** [comment]
提供布局文件

**Comment by XuanJiAndroid** [comment]
搞定了，直接将设计图的尺寸宽高/2即可解决了
