### ISSUE TITLE
三星s10 lineSpacingExtra异常

### ISSUE THREAD

**Issue by TokenYc** [JessYanCoding/AndroidAutoSize#272]
### Environment
- [x] Autosize Version: 1.1.2 
- [x] Target Android Version: 29 
- [x] Device Model: 三星s10 
- [x] Device Resolution: 3040px* 1440px 
- [x] Design Size On AndroidManifest: 375dp * 812dp 

### Bug Description:
在三星s10上，当TextView设置lineSpacingExtra后，行间距明显过大。以下是今日头条在一加3和三星s10上的对比。
![一加三](https://i.loli.net/2020/03/03/FNlgYcA6C1V2mzq.png)
![三星s10](https://i.loli.net/2020/03/03/8zOFMJnp94jtC6K.png)

**Comment by JessYanCoding** [comment]
兄弟你贴今日头条的截图，是想反馈今日头条 APP 的 Bug？

**Comment by TokenYc** [comment]
是这样的：先是在我们自己app中发现了这个问题，因为这个库本质上原理跟今日头条一样的嘛，所以就去看了下今日头条有没有相同的问题。发现还真有，就顺手截了今日头条的图。
@JessYanCoding

**Comment by JessYanCoding** [comment]
框架的功能只是改 density，textView 设置 lineSpacingExtra 是否使用了正确的 density ，还需要你自己去断点看下，如果 density 是正确的，建议使用其他的属性，或者自定义代替
