### ISSUE TITLE
希望有用于B4A的封装

### ISSUE THREAD

**Issue by watersoft123** [JessYanCoding/AndroidAutoSize#274]
我在用第三方IDE写安卓应用，采用的是B4X系列中的B4A（目前已免费），官网www.b4x.com。看到这个适配方法很强大，但我不会JAVA，无法封装供B4A使用，希望能有机会在B4A上使用。

**Comment by JessYanCoding** [comment]
抱歉，精力有限，这个框架只会使用 JAVA 编写，并且只提供 ARR 包或者 JAR 包，以及 JAVA 世界的依赖方式，如果你想使用这个框架，请自行想其他方法来使用 JAVA 库，这个框架不会主动考虑兼容其他的  IDE 或语言，你能使用其他 JAVA 库或 Android 库就能使用本框架。

**Comment by JessYanCoding** [comment]
看了下这个 IDE，是跨平台的，如果能跨平台，那这个 IDE 应该会考虑兼容现存的 JAVA 库，如果这个 IDE，连开源库都无法依赖，那这 IDE 相当于放弃了 JAVA 生态，所有项目的功能都需要从 0 开始编写，效率很其低，那使用这个 IDE 有什么意义呢？

**Comment by watersoft123** [comment]
谢谢大牛回复。
B4X的库基本都是JAVA写成的，可以内嵌简单的JAVA，也可以引入第三方的jar。我也是不想学JAVA，才找到了B4X。
内嵌JAVA:[https://www.b4x.com/android/forum/threads/inline-java-code.50141/#content](url)
引入JAR:[https://www.b4x.com/android/forum/threads/accesing-third-party-jar-with-additionaljar-and-javaobject-picasso.40904/#content](url)
我看你回复中提到可以提供JAR包，但没有找到下载的地方，能否提供一下? 谢谢。
另外，这个jar包的主入口方法或函数是什么，用到哪些参数，需要在B4A里面通过RunMethod方法进行调用。

**Comment by JessYanCoding** [comment]
jar 只有你自己打，我这里只又默认打的 aar 包，https://bintray.com/jessyancoding/maven/autosize/1.2.1#files/me%2Fjessyan%2Fautosize%2F1.2.1

**Comment by JessYanCoding** [comment]
jar 入口方法，自己看文档和 Demo，注释说的都很详细

**Comment by watersoft123** [comment]
好的，谢谢，我试试看
