### ISSUE TITLE
页面带webView

### ISSUE THREAD

**Issue by wangshuogit** [JessYanCoding/AndroidAutoSize#277]
当一个页面中有WebView时 第一次进入那个页面是没有 适配的 请问下 大神 这是什么问题  当第一次运行程序 或者退出重新启动程序或者程序在后台被杀了 重新进入程序 点开那个带webView的页面都是没有适配的 一定要返回在次进入那个页面 才会适配

**Comment by JessYanCoding** [comment]
看常见问题汇总，自己找找 issues ，这个问题回答过多次

**Comment by wangshuogit** [comment]
好的 谢谢



在 2020-03-16 10:41:47，"JessYan" <notifications@github.com> 写道：

看常见问题汇总，自己找找 issues ，这个问题回答过多次
