### ISSUE TITLE
一个比较冷门的问题，如果是多屏显示，对副屏适配可能存在问题

### ISSUE THREAD

**Issue by dlgit88839** [JessYanCoding/AndroidAutoSize#278]
### Environment
- [x] Autosize Version: 
- [x] Target Android Version: 
- [x] Device Model: 
- [x] Device Resolution: 
- [x] Design Size On AndroidManifest: 

### Log:

```log


```

### Related Code:
```java
  

```

**Comment by JessYanCoding** [comment]
什么问题

**Comment by dlgit88839** [comment]
副屏不会生效，因为副屏的display和主屏不同，在副屏presentation初始化过程中会根据display生成context，getResource和主屏获取到的也就不同

**Comment by JessYanCoding** [comment]
https://github.com/JessYanCoding/AndroidAutoSize/issues/188

这个是类似的 issues。

https://github.com/JessYanCoding/AndroidAutoSize/issues/1#issuecomment-504654664

可以参照上面这个回答，看是否能重写 ContextWrapper 和他的 getResources() 返回一个经过适配的 Resources，如果不行的话，那就没办法了，Presentation 可能不允许这样做，也就是用不了所有今日头条适配方案

**Comment by Kidlite** [comment]
在 Presentation的构造函数里，修改DisplayMetrics的density即可

**Comment by dxy1046** [comment]
> > 在 Presentation的构造函数里，修改DisplayMetrics的density即可
> 
> @Kidlite 请问能贴下代码吗

请问这个问题您有解决的办法吗
