### ISSUE TITLE
BottomDialog(DialogFragment)距离底部有一定的间距

### ISSUE THREAD

**Issue by TaylorKunZhang** [JessYanCoding/AndroidAutoSize#279]
### Environment
- [x] Autosize Version:  1.2.1
- [x] Target Android Version:  Android 8.0
- [x] Device Model:  荣耀8、华为P9、魅族16
- [x] Device Resolution:  1080px * 1920px
- [x] Design Size On AndroidManifest:  375dp * 778dp

### Bug Description:

底部显示的弹窗距离底部有一定的间距。

### Log:

```log


```

### Screenshot

以下代码有间隔：

```kotlin
class MainActivity : AppCompatActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        btnShowDialog.setOnClickListener {
            // 显示弹窗
            AutoSizeCompat.autoConvertDensityOfGlobal((super.getResources()))
            BottomDialog().showDialog(supportFragmentManager)
        }
    }

    override fun getResources(): Resources {
        AutoSizeCompat.autoConvertDensityOfGlobal((super.getResources()))
        return super.getResources()
    }
}
```
![Screenshot_20200317-145920](https://user-images.githubusercontent.com/15033489/76831064-8de60580-6861-11ea-952f-2efab5e65fb9.jpg)

以下代码没有间隔：

```kotlin
class MainActivity : AppCompatActivity(), CancelAdapt {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        btnShowDialog.setOnClickListener {
            // 显示弹窗
            BottomDialog().showDialog(supportFragmentManager)
        }
    }
}
```
![Screenshot_20200317-150058](https://user-images.githubusercontent.com/15033489/76831478-5fb4f580-6862-11ea-8168-57aca5b5b34d.jpg)

### Related Code:
```java
  

```

### Others:
已提供源码
[bottom-dialog-space.zip](https://github.com/JessYanCoding/AndroidAutoSize/files/4342063/bottom-dialog-space.zip)

**Comment by JessYanCoding** [comment]
https://mp.weixin.qq.com/s/SDHL26XgIjjlK-RLd_SSCw

**Comment by TaylorKunZhang** [comment]
我这里并没有写死弹窗的宽高，宽度是match_parent，高度是wrap_content
弹窗布局文件源码如下：
```xml
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:background="@drawable/bg_dialog"
    android:orientation="vertical">

    <Space
        android:layout_width="match_parent"
        android:layout_height="25dp" />

    <TextView
        android:layout_width="match_parent"
        android:layout_height="22dp"
        android:gravity="center"
        android:text="@string/bottom_dialog_title"
        android:textColor="@color/black_1F"
        android:textSize="16dp"
        android:textStyle="bold" />

    <Space
        android:layout_width="match_parent"
        android:layout_height="18dp" />

    <TextView
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginStart="25dp"
        android:layout_marginEnd="25dp"
        android:lineSpacingExtra="5dp"
        android:text="@string/bottom_dialog_content"
        android:textColor="@color/black_1F"
        android:textSize="14dp" />

    <Space
        android:layout_width="match_parent"
        android:layout_height="30dp" />

    <Button
        android:id="@+id/btnPositive"
        style="@style/Widget.AppCompat.Button.Borderless"
        android:layout_width="match_parent"
        android:layout_height="40dp"
        android:layout_marginStart="30dp"
        android:layout_marginEnd="30dp"
        android:background="@drawable/bg_button_green"
        android:text="@string/bottom_dialog_button_positive"
        android:textColor="@color/white"
        android:textSize="16dp" />

    <Space
        android:layout_width="match_parent"
        android:layout_height="15dp" />

</LinearLayout>
```

**Comment by JessYanCoding** [comment]
DialogFragment 高度 match_parent，里面的内容给个 Gravity.BOTTOM

**Comment by TaylorKunZhang** [comment]
是的，这是一种解决方案，在项目中，我采用了另一种方案，主要考虑到点击弹窗上方（对用户来讲）能关闭弹窗，点击弹窗区域不会关闭弹窗，而且弹窗本身有背景。

所以在 `LinearLayout ` 外面套了一个 `FrameLayout`，在 `FrameLayout` 的高度是 `match_parent `，在 `LinearLayout` 上设置了 `android:layout_gravity="bottom"`。

```xml
<?xml version="1.0" encoding="utf-8"?>
<FrameLayout 
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_gravity="bottom"
        android:background="@drawable/common_rect_white_radius_10_0"
        android:orientation="vertical">
       ...
    </LinearLayout>

</FrameLayout>
```

提这个 `issue` 主要是希望能从底层解决这个问题，这样在处理底部弹窗的时候不必特殊处理。

**Comment by JessYanCoding** [comment]
底层解决不了这个问题，因为这本来就是你布局导致的，不是框架导致的，框架原理只是修改 density，怎么布局，布局效果这都是你自己去作的，至于框架原理建议读读我的文章，这框架原理和 AutoLayout 等通过修改 view 的属性来达到屏幕适配的方案根本不是一个东西，懂原理，你才知道我说的什么。 https://github.com/JessYanCoding/AndroidAutoSize/issues/13

**Comment by steven-gao** [comment]
> 是的，这是一种解决方案，在项目中，我采用了另一种方案，主要考虑到点击弹窗上方（对用户来讲）能关闭弹窗，点击弹窗区域不会关闭弹窗，而且弹窗本身有背景。
> 
> 所以在 `LinearLayout ` 外面套了一个 `FrameLayout`，在 `FrameLayout` 的高度是 `match_parent `，在 `LinearLayout` 上设置了 `android:layout_gravity="bottom"`。
> 
> ```
> <?xml version="1.0" encoding="utf-8"?>
> <FrameLayout 
>     android:layout_width="match_parent"
>     android:layout_height="match_parent">
> 
>     <LinearLayout
>         android:layout_width="match_parent"
>         android:layout_height="wrap_content"
>         android:layout_gravity="bottom"
>         android:background="@drawable/common_rect_white_radius_10_0"
>         android:orientation="vertical">
>        ...
>     </LinearLayout>
> 
> </FrameLayout>
> ```
> 
> 提这个 `issue` 主要是希望能从底层解决这个问题，这样在处理底部弹窗的时候不必特殊处理。

最外面的一层FrameLayout可以不加，直接用LinearLayout。
