### ISSUE TITLE
状态栏问题

### ISSUE THREAD

**Issue by wcnmtx** [JessYanCoding/AndroidAutoSize#28]
### Environment
- [x] Autosize Version: v0.8.0
- [x] Target Android Version: Android 4.4.4
- [x] Device Model: Galaxy E7
- [x] Device Resolution: 720*1280
- [x] Design Size On AndroidManifest: 375*667

### Bug Description:
设计给的图片是750px *1334px  然后我在AndroidManifest设置的是375*667
发现状态栏和标题栏之间有点空隙。暂时只测了红米note5 和 金立S9L 没问题

### Log:
![d3d9924b-b40d-42c3-9245-76c9a2e606a9](https://user-images.githubusercontent.com/8731096/44715024-5bdb4a00-aae9-11e8-8a47-c8801e32a807.png)

### Screenshot

![screenshot_2018-08-28-17-42-02](https://user-images.githubusercontent.com/8731096/44715257-e4f28100-aae9-11e8-8e8c-20372ffe6318.png)

### Related Code:

   获取状态栏高度的代码
```java
   public static int getStatusBarHeight(Context context) {
        int result = 0;
        int resourceId = context.getResources().getIdentifier("status_bar_height", "dimen", "android");
        if (resourceId > 0) {
            result = context.getResources().getDimensionPixelSize(resourceId);
        }
        return result;
    }

```

### Others:

      还有个问题就是，字体也可以用px吗 ？

**Comment by JessYanCoding** [comment]
1.第一个问题使用框架的 ScreenUtils#getStatusBarHeight() 获取状态栏的高度

2.第二个问题，问的我挺无语的，不管是框架中的注释，还是文章原理，我从来没有提到过，px 可以用来做适配，你有在认真看我的文章吗，这个和 AndroidAutoLayout 一滴点关系都没，字体想适配，你用 sp、还是 dp 都可以，用 px 你在想什么

**Comment by wcnmtx** [comment]
非常感谢，解决了空隙问题。有仔细阅读，第二问题因为也是没有看到适配字体说明，所以顺带问问。老哥稳。

**Comment by JessYanCoding** [comment]
还有更稳的，AndroidAutoSize  已经把今日头条这方案做到极致，更新到 v0.9.1 版本，可以支持五种单位 (dp、sp、pt、in、mm)，以下单位全部支持，使用后面的三个冷门单位，就可以避免修改 density 导致的其他三方库控件以及系统控件的显示异常，还可以直接填写设计图的像素，不需要在转化为 dp
```java
public static float applyDimension(int unit, float value,
                                       DisplayMetrics metrics)
    {
        switch (unit) {
        case COMPLEX_UNIT_PX:
            return value;
        case COMPLEX_UNIT_DIP:
            return value * metrics.density;
        case COMPLEX_UNIT_SP:
            return value * metrics.scaledDensity;
        case COMPLEX_UNIT_PT:
            return value * metrics.xdpi * (1.0f/72);
        case COMPLEX_UNIT_IN:
            return value * metrics.xdpi;
        case COMPLEX_UNIT_MM:
            return value * metrics.xdpi * (1.0f/25.4f);
        }
        return 0;
    }
```

**Comment by wcnmtx** [comment]
哈哈。我已经上车了。
