### ISSUE TITLE
界面元素有时候会缩小

### ISSUE THREAD

**Issue by azhon** [JessYanCoding/AndroidAutoSize#280]
### Environment
- [x] Autosize Version: 1.1.2
- [x] Target Android Version: 6.0
- [x] Device Model: 华为

### Log:

```log


```

### Screenshot

![QQ图片20200319092905](https://user-images.githubusercontent.com/20559556/77022252-17154d80-69c4-11ea-8b3a-66fef70c7831.png)

### Related Code:
```java
  

```

**Comment by Alexxiaopang** [comment]
同样，第一次进去界面元素缩小，多发生在自定义view，后面就正常了

**Comment by azhon** [comment]
> 同样，第一次进去界面元素缩小，多发生在自定义view，后面就正常了

问题是我现在不是自定义view

**Comment by JessYanCoding** [comment]
https://github.com/JessYanCoding/AndroidAutoSize/issues/13

**Comment by Alexxiaopang** [comment]
我这边解决了，你测量一下你的，DisplayMetrics#density ，如果没正确设置，试试手动调用框架的设置，你多看一下https://github.com/JessYanCoding/AndroidAutoSize/issues/13 这里面有解决方案的

**Comment by oOJohn6Oo** [comment]
只有同方向切换的，比如`sensorLandscape`，我用下面的代码完美解决。
```
    override fun getResources(): Resources {
        AutoSizeCompat.autoConvertDensityOfGlobal(super.getResources())
        return super.getResources()
    }
    override fun onConfigurationChanged(newConfig: Configuration) {
        super.onConfigurationChanged(newConfig)
        if(newConfig.orientation == Configuration.ORIENTATION_LANDSCAPE)
                       AutoSize.autoConvertDensityOfGlobal(this)
    }
```

可是我想做到横竖屏切换都按手机的宽边适配，目前还在想办法...

**Comment by Alexxiaopang** [comment]
> 只有同方向切换的，比如`sensorLandscape`，我用下面的代码完美解决。
> 
> ```
>     override fun getResources(): Resources {
>         AutoSizeCompat.autoConvertDensityOfGlobal(super.getResources())
>         return super.getResources()
>     }
>     override fun onConfigurationChanged(newConfig: Configuration) {
>         super.onConfigurationChanged(newConfig)
>         if(newConfig.orientation == Configuration.ORIENTATION_LANDSCAPE)
>                        AutoSize.autoConvertDensityOfGlobal(this)
>     }
> ```
> 
> 可是我想做到横竖屏切换都按手机的宽边适配，目前还在想办法...

兄弟，你可以试一下这样，切换是否按照宽度适配，通过log可以看一下，是否能解决，或者在适当的位置调用autoConvertDensity
    @Override
    public Resources getResources() {
        if (currentOrientation == Configuration.ORIENTATION_LANDSCAPE) {
            AutoSizeCompat.autoConvertDensity(super.getResources(), 375, false);
        } else {
            AutoSizeCompat.autoConvertDensity(super.getResources(), 375, true);
        }
        return super.getResources();
    }

**Comment by oOJohn6Oo** [comment]
> > 只有同方向切换的，比如`sensorLandscape`，我用下面的代码完美解决。
> > ```
> >     override fun getResources(): Resources {
> >         AutoSizeCompat.autoConvertDensityOfGlobal(super.getResources())
> >         return super.getResources()
> >     }
> >     override fun onConfigurationChanged(newConfig: Configuration) {
> >         super.onConfigurationChanged(newConfig)
> >         if(newConfig.orientation == Configuration.ORIENTATION_LANDSCAPE)
> >                        AutoSize.autoConvertDensityOfGlobal(this)
> >     }
> > ```
> > 
> > 
> > 可是我想做到横竖屏切换都按手机的宽边适配，目前还在想办法...
> 
> 兄弟，你可以试一下这样，切换是否按照宽度适配，通过log可以看一下，是否能解决，或者在适当的位置调用autoConvertDensity
> @override
> public Resources getResources() {
> if (currentOrientation == Configuration.ORIENTATION_LANDSCAPE) {
> AutoSizeCompat.autoConvertDensity(super.getResources(), 375, false);
> } else {
> AutoSizeCompat.autoConvertDensity(super.getResources(), 375, true);
> }
> return super.getResources();
> }

谢谢，我已经弄好了，思路是一样的，判断orientation其实比较麻烦，需要保存变量，如果不保存直接从configuration里面读会不断调用`getResources()`直接崩溃，我是这么写的：
```kotlin

    override fun getResources(): Resources {
        AutoSizeCompat.autoConvertDensity(
            super.getResources(),
            1024f,
            AutoSizeConfig.getInstance().screenWidth > AutoSizeConfig.getInstance().screenHeight
        )
        return super.getResources()
    }

    override fun onConfigurationChanged(newConfig: Configuration) {
        super.onConfigurationChanged(newConfig)
        if (newConfig.orientation == Configuration.ORIENTATION_LANDSCAPE)
            AutoSize.autoConvertDensity(this, 1024f, newConfig.orientation == Configuration.ORIENTATION_LANDSCAPE)
    }
```

**Comment by JessYanCoding** [comment]
https://github.com/JessYanCoding/AndroidAutoSize/blob/master/demo/src/main/java/me/jessyan/autosize/demo/BaseApplication.java#L84

**Comment by azhon** [comment]
弃坑了，转sw适配了
