### ISSUE TITLE
第三方库中的Activity弹出Toast时文字很小，除了自己改第三方库，有没有其他办法解决？

### ISSUE THREAD

**Issue by RichMoster** [JessYanCoding/AndroidAutoSize#283]
说明：
1、使用副单位mm
2、已经取消对第三方库的适配
 AutoSizeConfig.getInstance().getUnitsManager()
                .setSupportDP(false)
                .setSupportSubunits(Subunits.MM);
 AutoSizeConfig.getInstance().getExternalAdaptManager()
                .addCancelAdaptOfActivity(PictureSelectorActivity.class)
                .addCancelAdaptOfActivity(PictureSelectorWeChatStyleActivity.class)
                .addCancelAdaptOfActivity(PictureSelectorCameraEmptyActivity.class)
                .addCancelAdaptOfActivity(PictureCustomCameraActivity.class)
                .addCancelAdaptOfActivity(PicturePreviewActivity.class)
                .addCancelAdaptOfActivity(PictureSelectorPreviewWeChatStyleActivity.class)
                .addCancelAdaptOfActivity(PictureVideoPlayActivity.class)
                .addCancelAdaptOfActivity(PictureExternalPreviewActivity.class)
                .addCancelAdaptOfActivity(UCropActivity.class)
                .addCancelAdaptOfActivity(VideoPreviewActivity.class)
                .addCancelAdaptOfActivity(PictureMultiCuttingActivity.class);

**Comment by JessYanCoding** [comment]
如果只是字体小，整个 Toast 的大小没问题，那应该是使用 sp 导致的，因为你项目使用的设计图尺寸和第三方的设计图尺寸差距很大，建议在使用副单位的时候关闭对 sp 的支持，并使用副单位作为字体的单位，AutoSizeConfig.getInstance().getUnitsManager().setSupportSP(false)。

如果想继续使用 sp，并关闭对 sp 的支持可以使用 AutoSizeConfig.getInstance().setExcludeFontScale(true)。

如果想在使用 sp 的情况下，全局调整 App 中的字体大小，并且字体大小不随系统字体大小改变，可使用 AutoSizeConfig.getInstance().setPrivateFontScale(0.8f)。

https://github.com/JessYanCoding/AndroidAutoSize/blob/master/demo/src/main/java/me/jessyan/autosize/demo/BaseApplication.java#L77
