### ISSUE TITLE
会对通过系统资源获取状态栏高度有影响

### ISSUE THREAD

**Issue by gh1225987336** [JessYanCoding/AndroidAutoSize#284]
private static int getStatusBarHeight(Context context) {
        // 获得状态栏高度
        int resourceId = context.getResources().getIdentifier("status_bar_height", "dimen", "android");
        int height=context.getResources().getDimensionPixelSize(resourceId);
        return height;
    }
使用副单位后此方法获取不到正确的状态栏高度。

**Comment by JessYanCoding** [comment]
https://github.com/JessYanCoding/AndroidAutoSize/issues/232

**Comment by shaobin0604** [comment]
@gh1225987336 使用 `Resources.getSystem()` 替换 `context.getResources()` 即可
