### ISSUE TITLE
升级1.2.1导致极验SDK无法正常校验

### ISSUE THREAD

**Issue by KerryZhang2016** [JessYanCoding/AndroidAutoSize#289]
之前一直使用的是1.1.2 autoSize，今天升级到了1.2.1
使用的时候发现极验SDK无法正常使用，会返回TimeOut的网络错误。错误日志如下（极验SDK是一个做真实用户身份验证的SDK，使用时会弹出一个窗口让用户挪动滑块进行验证）：

{errorCode='208', errorDesc='request error:java.lang.NullPointerException: Attempt to get length of null array  {1.ConnectException 无法连接到主机 （检查网络、清空缓存） 2.SocketTimeOutException 请求超时（检查网络、清空缓存、待会测试）3. SSLHandshakeException 证书异常（检查网络、清空缓存）4.UnknownHostException 域名解析异常 （dns污染，检查网络、清空缓存、联系运维）5. 其他,联系我们 }', duration=404, challenge='xxxx', type='Sensebot', sdkVersion='4.1.5', isChangeDesc=false}

将autoSize版本改回1.1.2即可恢复正常。无法定位具体的原因。
PS：1.2.1版本，在代码调用resources.displayMetrics时，会进行主线程的判断，不为主线程就会抛出异常。这样的设计会不会侵入性太高了？

**Comment by JessYanCoding** [comment]
加入主线程判断这个和侵入性有什么关系，你设置 displayMetrics 的线程和获取 displayMetrics 的线程不是一个线程，那你怎么能保证获取到的值一定就是你设置之后的正确值。

至于你说的极验SDK验证的问题，上面报的所有错误都和网络有关，而 AndroidAutoSize 根本就没申请过网络权限，建议你联系 极验SDK 的客服，验证不通过是它这个 SDK 的验证问题，我作为一个开源库只保证自己的核心功能是能正确工作的，它 SDK 出问题了，你来找我，感觉顺序弄反了。

**Comment by KerryZhang2016** [comment]
displayMetrics的问题，大部分情况下写 UI 或者更新 UI肯定是在主线程进行。只是项目有一些特殊场景，比如网络请求时需要传递屏幕尺寸，而这个参数的设置是通过OKHttp的interceptor在切换线程后获取添加的，这个情况就会导致崩溃。感觉库里直接判断主线程然后throw exception，可能有点欠妥了吧，抛出的这个excetion开发者很难去自己处理。

极验的问题你说的有道理。我只是升级了autosize版本之后会出现问题，降级后问题会消失。看了更新日志后没法定位问题所在，所以提了这个issue想请教下有没有可能导致问题的原因。我再去研究研究吧~多谢回复

**Comment by JessYanCoding** [comment]
你的意思是让我在主线程异常处理时，抛出一个更加温和的 Exception，这个我能理解，但我不能理解的是，为什么你在 Okhttp 的 Interceptor 中切换线程执行某段代码会奔溃，我自己也经常在 Interceptor 中做一些 UI 操作，比如在网络请求出错时给一些 UI 的展示，从来没遇到过奔溃的问题，你也没说奔溃的原因是什么的，所以你说的奔溃，我可能认为是你自己没处理好的原因导致的。

**Comment by KerryZhang2016** [comment]
嗯嗯 你说的有道理。
我之前开发中接触displayMetrics比较少，对于它的多线程获取了解的也不够，不太了解这个Exception的原理。
受教了~多谢分享！
