### ISSUE TITLE
有用户反馈偶尔布局错乱，不确定是不是AutoSize的问题

### ISSUE THREAD

**Issue by KerryZhang2016** [JessYanCoding/AndroidAutoSize#290]
![Screenshot_20200427-123432](https://user-images.githubusercontent.com/7929481/80569827-48a21f80-8a2c-11ea-9ad3-7d1ff9103f2a.png)
有用户反馈App首先显示效果如图，重启后可以恢复。
手机系统：google pixel 4 xl, android 10
开发测试中没有遇到这种问题，不确定是不是AutoSize导致的。

**Comment by JessYanCoding** [comment]
https://github.com/JessYanCoding/AndroidAutoSize/issues/13#11
