### ISSUE TITLE
使用过程中遇到的问题

### ISSUE THREAD

**Issue by 751811032** [JessYanCoding/AndroidAutoSize#293]
我觉得这个使用之前一定要给大家说清楚会出现什么样的问题，
如果稍微复杂一点的界面，不能只单纯的以高为单位，或者以宽为单位，写起来就会复杂的多，特别是有列表的情况下会出现错位，大小不一的情况。需要实时校正宽或者高的单位。我觉得现在只适合做一些比较单一，简单一点的界面，可以固定高度或者固定宽度写一整套界面的项目

**Comment by JessYanCoding** [comment]
https://github.com/JessYanCoding/AndroidAutoSize/issues/13  问题都汇总在这，写的都很全，很详细，你不会没看吧。。。

**Comment by 751811032** [comment]
不好意思，我可能语气不太对，但是我不是针对这个项目。用之前也有认真去考察这个优缺点，单那一想缺点有点不能接受，但是一搜索，现在基本上用的适配方案都是您的这套适配方案，所以想着大家伙都用肯定没有问题。因为我这有多个相对复杂的界面，不能单纯只以某一方向来适配，用过之后发现对复杂界面的适配难度超过了我的想象，所以只是想提醒一下大家可能会遇到的问题，以及这个复杂度是否可以接受。

**Comment by JessYanCoding** [comment]
你看下这篇 [文章](https://mp.weixin.qq.com/s/SDHL26XgIjjlK-RLd_SSCw)，现在只能以单一方向来适配，我觉得你可能对现在屏幕适配方式不太理解。

目前所有主流的方案都是以单一方向来适配的，不可能让布局的高宽同时平铺满屏幕，因为这个方式本来就是错的，因为这种方案没有考虑到机型高宽比和设计图高宽比不同的问题。

一个设计图为 16:9 的布局，不可能在 18: 9 的设备上，既能保证高宽同时平铺满屏幕，还能保证布局的高宽比例不变，现在的适配方案只有两种:

第一种，让布局高宽强行平铺满屏幕且高宽比例变形
第二种，保证高宽比例不变，并在高宽中只选择一侧拉伸平铺满屏幕，而另一侧按相同比例拉伸，但不保证能平铺满屏幕

你可以把他理解为，第一种是 Imagview  ScaleType 中的 **FIT_XY**，第二种是 **CENTER_CROP**，所以你一般平时会用 FIT_XY 适配图片吗，为了强行适配让图片变形可不是最好的解决方案。

所以现在所有主流的适配方案都是用的第二种，至于没有平铺满屏幕的那一侧，则可以使用可滑动控件，比如 ScrollView 或者 RecyclerView 就可以了。

第一种适配方式的代表框架就是 [AndroidAutoLayout](https://github.com/hongyangAndroid/AndroidAutoLayout)，之所以他在那个时代成为主流，是因为那个时代的手机基本都是 16:9，而在现在这个全面屏时代，各种高宽比的屏幕都有，这个框架早就已经水土不服。

你还在用过去的思维去思考现在的方案，那肯定是不可能实现你的需求的，别说今日头条方案实现不了你的需求，SW 方案以及其他方案也都无法实现你的需求，如果实现了，你说明这个方案就是错的。

**Comment by JessYanCoding** [comment]
所以不管你是用其他的适配框架，还是自己写屏幕适配，不要把所有的关注点都放在让布局在设备上的呈现效果和设计图一模一样，因为即使你的测试机的高宽比和设计图的高宽比一模一样，能完全呈现设计图，但在其他高宽比不一样的手机上也还是无法完美呈现设计图，况且，现在大部分的设计师都是以 iphone 的尺寸做的设计图。

**Comment by 751811032** [comment]
嗯嗯，明白你说的意思，我想要实现的功能是这样的，我举个例子你可能就大概清楚了。

**Comment by 751811032** [comment]
嗯嗯，明白你的意思，我想要的功能大概是这样的，我举个例子，看我说的清楚了吗。
我用咱们的项目试验过，在设备上， 底部菜单栏，顶部状态栏是以高度为基准是最美观的。有一些view是以高度为基准，是能最大限度的还原设计图
但是在这个基础上，界面中有一块区域是横向排列了密密麻麻的几个组件，不大不小，正好填充横向屏幕，此时以高度为基准，要不就会超出屏幕，要不就不能填充屏幕。

**Comment by 751811032** [comment]
嗯嗯，明白你的意思，我想要的功能大概是这样的，我举个例子，看我说的清楚了吗。
我用咱们的项目试验过，在设备上， 底部菜单栏，顶部状态栏是以高度为基准是最美观的。有一些view是以高度为基准，是能最大限度的还原设计图
但是在这个基础上，界面中有一块区域是横向排列了密密麻麻的几个组件，不大不小，正好填充横向屏幕，此时以高度为基准，要不就会超出屏幕，要不就不能填充屏幕，百分比的view就会变形了。
所以就不得不创建多个fragment，设置不同的基准，切换activity的时候，有view复用稍有不慎就会错位了。
此时如果有一个办法就是我想要以高度为基准的时候就以高度为基准，想要以宽度为基准的时候就以宽度为基准。那是多么的舒服啊。
非常感谢作者的无私奉献。也非常钦佩作者的能力。

**Comment by JessYanCoding** [comment]
我知道你想实现的是什么，包括你上面所叙述的想让这个框架实现这个需求时会出现的问题，我都在 [这篇文章中](https://mp.weixin.qq.com/s/SDHL26XgIjjlK-RLd_SSCw) 画图展示过，因为在这类方案诞生时，我就知道会出现这些问题的。

但是就上面我说的那样，所有现在主流的框架都不可能实现这个需求，如果能实现只可能在某几款和你设计图高宽比一致的机型上实现，在其他高宽比和设计图不一致的机型上必定出现 view 高宽变形，原理很简单，一个正方形的物体是永远无法在保证高宽比不变的情况下，填满一个长方形的盒子的。

你这个需求想在所有机型上适配，最好的方法就是让布局纵向或横向可滑动，只保证高宽中的一方能平铺满屏幕。
