### ISSUE TITLE
单Activity多fragment适配问题

### ISSUE THREAD

**Issue by xiang23** [JessYanCoding/AndroidAutoSize#3]
现在这样适配都对到activity,对多fragment不怎么友好..比如cancelAdapter

**Comment by JessYanCoding** [comment]
没办法，只有 Activity 能自定义 DisplayMetrics，这个不是我定的，是 Google 定的

**Comment by JessYanCoding** [comment]
不过也有办法，如果你想每个 Fragment 都可以自定义的话，必须每生成一个 Fragment，就切换一次 density，必须一个个生成 Fragment，不能同时生成

**Comment by xiang23** [comment]
假设每个fragment density一样的情况其实仍旧是创建时的调用适配（因为其实都是对的同一个Activity没什么意义），如果两个fragment density不一样的话 显示的时候重新调用适配这样会有问题吗？

**Comment by JessYanCoding** [comment]
两个 Fragment 的 density 不可能不一样，都是一样的，不过可以通过
```
density = 1;
new  Fragment1
 density = 2
new  Fragment2
```
在 Fragment 显示视图之前切换就可以了，Activity 我也是这样做的，你们以为 Activity 可以单独设置 density，其实是幻觉，我只不过在这个 Activity setContentView 之前，按照它的需求切换了 density，这个 density 是全局的，不存在什么单独设置这一说

**Comment by xiang23** [comment]
明白,Thx

**Comment by xiang23** [comment]
按这种说法density是全局的话，假设A,B两个Activity A density=1 B density=2 A start B 然后 B finish回到A  这时候比如A突然需要动态addview 就需要重新设置一遍density对吧？

**Comment by JessYanCoding** [comment]
对，是这个道理，因为全局的 density 现在是 2，而框架，为了避免这个问题，是在每次 onCreate 的时候主动重新设置 density，不过需要重新自定尺寸的页面毕竟在少数，全局 density 给我们带来的好处是减少大量工作量，带来的坏处是，适配范围不可控，影响范围也越大

**Comment by JessYanCoding** [comment]
Fragment 自定义尺寸，需求很常见吗？我使用 FragmentLifecycleCallbacks 也可以做到和 Activity 一样的让 Fragment 可以自定义尺寸，但是我担心弄太复杂了，而且全局的 density 在频繁切换的时候也有太多不可确定性，做是可以做，但感觉这个需求也不是太常见，这个成本和收益不相符

**Comment by JessYanCoding** [comment]
和模式无关，只要 onCreate 中的 setContentView，计算好这个 Activity 正确的 density 就行 setContentView 之后布局就一定定型了，哪怕是其他模式启动时，不执行 onCreate 也无所谓了，因为他的布局已经根据之前的 density 设置好了，至于现在的 density 是多少，并不影响之前的布局

除非这个 Activity 的布局在  setContentView 后改变，这时就必须重新计算并且设置 density

**Comment by xiaobailong24** [comment]
晓得，很赞

**Comment by JessYanCoding** [comment]
@xiang23 'me.jessyan:autosize:0.8.0'   已经支持了 Fragment 自定义适配参数

**Comment by xiang23** [comment]
@JessYanCoding 感谢大大的付出。    
然后我直接用demo试了一下fragment 在屏幕旋转的时候会出现问题。
demo里正好加的三个fragment都是自定义适配的好复现。

我的使用的是nexus S的模拟器 28版本的sdk

我打印了下生命周期发现问题大概是这样
正常情况下
![image](https://user-images.githubusercontent.com/14964761/44620718-eba3ad00-a8cb-11e8-83bf-5b9d989f88d7.png)
而旋转以后
![image](https://user-images.githubusercontent.com/14964761/44620722-0544f480-a8cc-11e8-9e9a-648d9cf54203.png)
fragment自顶往下调用了所有create后才开始自下往上依次调用onCreateView 这样导致三个fragment都设置了fragment3的适配参数导致适配出现问题。

效果图
正常图1：
![image](https://user-images.githubusercontent.com/14964761/44620763-a59b1900-a8cc-11e8-9b73-8be3ea128222.png)
旋转后转回来：
![image](https://user-images.githubusercontent.com/14964761/44620773-c2375100-a8cc-11e8-8bea-6e6c2d3656ee.png)

**Comment by JessYanCoding** [comment]
https://github.com/JessYanCoding/AndroidAutoSize/commit/7d738553abe30d5b36774e5f32c975a9f2695c7a   看来最好的办法只有这样了

**Comment by MrLeeys** [comment]
程序奔溃闪白屏后，界面错乱，从新调用 AutoSizeConfig.getInstance().restart(); 不起作用，还有麻烦我提的问题，别无缘无故删除，有什么问题，可以回复我吗，一声不吭删除，真的服

**Comment by JessYanCoding** [comment]
常见 issues 不是提 issues 的地方，有 issues，自己按规则提 issues，不按规则提 issues，我有权利直接删除或者 close，https://github.com/JessYanCoding/AndroidAutoSize/blob/master/.github/ISSUE_TEMPLATE.md <https://github.com/JessYanCoding/AndroidAutoSize/blob/master/.github/ISSUE_TEMPLATE.md> 里面写的很清楚

**Comment by JessYanCoding** [comment]
https://raw.githubusercontent.com/JessYanCoding/AndroidAutoSize/master/.github/ISSUE_TEMPLATE.md <https://raw.githubusercontent.com/JessYanCoding/AndroidAutoSize/master/.github/ISSUE_TEMPLATE.md>

**Comment by MrLeeys** [comment]
@JessYanCoding  好吧，没注意看提问格式

**Comment by JessYanCoding** [comment]
@MrLeeys 你如果还想提 Issues 那就新建一个 Issues，并按规则完善 Issues 信息，你上面回复的消息，我马上也会删除，在别人的 Issues 中回复无关的信息，不仅会打扰到和这个 Issues 有关联的人，还会混淆检察历史 Issues 寻找解决方案的人，既然要想使用开源就得按正确的规则办事，这种错误的操作即使你喜欢也必须纠正

**Comment by jackyHuangH** [comment]
我使用过程出现了一个问题：主页面acticity+多个fragment,配合fragmentation库，发现无论activity还是fragment页面，顶部与状态栏之间总是有个间隙，另外一台米4（1080*1920）却没有这个问题，改成 @Override
    public boolean isBaseOnWidth() {
        return false;
    }
    @Override
    public float getSizeInDp() {
        return 0;
    }
问题依然存在。大佬有空看看呗
用的最新1.0.0版本，手机一加三，安卓8.0，分辨率：1080*1920，适配尺寸width=360dp,height=640dp。

**Comment by JessYanCoding** [comment]
@jackyHuangH 按照 [规范](https://github.com/JessYanCoding/AndroidAutoSize/blob/master/.github/ISSUE_TEMPLATE.md) 从新提一个 issues，截图一定要有
