### ISSUE TITLE
在模拟器上运行，有底部导航栏的情况，适配的时候会有一条白底

### ISSUE THREAD

**Issue by ljackChen001** [JessYanCoding/AndroidAutoSize#30]
### Environment
- [x] Autosize Version:  v0.8.0
- [x] Target Android Version:  Android 9.0
- [x] Device Model:  Pixel XL
- [x] Device Resolution: 1440px * 2560px 
- [x] Design Size On AndroidManifest: 360dp * 640dp 

### Bug Description:

在模拟器上运行，有底部导航栏的话，适配的时候会有一条白底，用命令隐藏底部导航栏 adb shell settings put global policy_control immersive.navigation=* 就没有白底了。有人在真机测试中遇到类似的情况吗？

### Log:

```log
SettingActivity Info: isBaseOnWidth = true, designWidthInDp = 360.000000, targetDensity = 4.000000, targetScaledDensity = 4.000000, targetDensityDpi = 640
```

### Screenshot

![screenshot_1535510571](https://user-images.githubusercontent.com/13534229/44762554-19158280-ab7a-11e8-9f57-687095d6bfcd.png)

### Related Code:
```java
  

```

**Comment by JessYanCoding** [comment]
https://github.com/JessYanCoding/AndroidAutoSize/issues/8  看看这里

**Comment by ljackChen001** [comment]
OK解决了 现在是用的全局高度适配，总感觉宽度适配比高度更加好一点0.0

**Comment by JessYanCoding** [comment]
对，因为大多数页面宽度是固定，高度因为可以上下滑动，所以不是固定的，但这个方案因为要适配屏幕高宽比和设计图高宽比不一样的适配，所以只能让高和宽中的一个正好填充屏幕，所以大多数情况用，以宽为基准就行了
