### ISSUE TITLE
字体适配

### ISSUE THREAD

**Issue by dawnhope** [JessYanCoding/AndroidAutoSize#300]
### Environment
- [x] Autosize Version: 
- [x] Target Android Version: 
- [x] Device Model: 
- [x] Device Resolution: 
- [x] Design Size On AndroidManifest: 

### Bug Description:
字体按照设计图上面的dp尺寸设置成sp后字体普遍较大点，跟设计图出入很大，但以dp单位设置字体大小时跟设计图完全一致，请问是否只支持dp适配，sp并不能适配？

### Log:

```log


```

### Related Code:
```java
  

```

**Comment by JessYanCoding** [comment]
请百度 dp  和 sp 的区别，理解清楚这两个单位的各自的意义，如果你没修改系统字体大小，sp  和 dp 是一致的，如果你期望任何时候，不管用户怎么修改系统字体大小， App 字体大小都和设计图一致，那还何必使用 sp，用 dp 就是。

如果实在想用 sp，又不想 App 字体根随系统字体的大小而改变，随时保持和设计图一致，框架也是支持的 https://github.com/JessYanCoding/AndroidAutoSize/blob/master/demo/src/main/java/me/jessyan/autosize/demo/BaseApplication.java#L77

**Comment by dawnhope** [comment]
dp和sp区别知道，刚开始的时候一直是设置sp比设置dp的字体大，以为框架不支持适配sp，后来发现是测试机系统字体设置大一倍导致的，非常感谢您的回复。
