### ISSUE TITLE
设计图是px，按照什么转成design_width_in_dp呢？

### ISSUE THREAD

**Issue by dotfeng** [JessYanCoding/AndroidAutoSize#302]
设计图肯定是px，design_width_in_dp要填dp的话，density是多少？

**Comment by qq326126439** [comment]
用副单位可以直接填px,  其他的大部分设计图如Iphone6, 4.7屏幕750x1334分辨率，计算方法sqrt((750^2)+(1334^2))/4.7 =dpi.  
根据google dp换算px= dp* (dpi /160) ,dp= px/(dpi/160)  算出dp值
具体可以看看作者的掘金
