### ISSUE TITLE
autosize 横屏跳转到系统设置界面返回出现界面部分图片变大

### ISSUE THREAD

**Issue by Alanqiu** [JessYanCoding/AndroidAutoSize#306]
![image](https://user-images.githubusercontent.com/5857925/88148199-d6a73400-cc30-11ea-8950-985be1b185f2.png)
![image](https://user-images.githubusercontent.com/5857925/88148259-e9ba0400-cc30-11ea-986d-cf847d6707d9.png)
![image](https://user-images.githubusercontent.com/5857925/88148359-0eae7700-cc31-11ea-96e0-c303d1ac03de.png)
网上查找的解决方案都无法解决。

### Environment
- [x] Autosize Version: 
- [x] Target Android Version: 
- [x] Device Model: 
- [x] Device Resolution: 
- [x] Design Size On AndroidManifest: 
测试华为p30、OPPO 都存在此问题，有兄弟遇到这种情况吗？
![image](https://user-images.githubusercontent.com/5857925/88148954-f7bc5480-cc31-11ea-8e4f-63a80ec15710.png)
这里加入打印出现多次进入此方法。感谢提供解决方案。

### Log:

```log


```

### Related Code:
```java
  

```

**Comment by JessYanCoding** [comment]
https://github.com/JessYanCoding/AndroidAutoSize/issues/13

**Comment by Alanqiu** [comment]
重写getResources()方法，解决了谢谢@JessYanCoding
