### ISSUE TITLE
我引入后运行报错java.lang.NoClassDefFoundError，自己解决了，贡献一下思路。

### ISSUE THREAD

**Issue by crook3** [JessYanCoding/AndroidAutoSize#32]
### Environment
- [x] Autosize Version: v0.9.1 
- [x] Target Android Version: Android 6.0.1 
- [x] Device Model: 网易mumu模拟器 
- [x] Device Resolution:   1080px * 1920px 
- [x] Design Size On AndroidManifest:  1280dp * 720dp 

### Bug Description:
java.lang.NoClassDefFoundError: me.jessyan.autosize.FragmentLifecycleCallbacksImpl
        at me.jessyan.autosize.ActivityLifecycleCallbacksImpl.<init>(ActivityLifecycleCallbacksImpl.java:45)

日志中提示FragmentLifecycleCallbacksImpl这个类找不到，报错，但是我去External Libraries里面能找到引入的Autosize包里面有该类。所以这个问题显得很诡异。
不知道问题出在哪里，只能回到原点，自己新建工程，重新引入，运行，没问题！这就奇怪了。于是我对比gradle里面的依赖及配置信息，由于使用的是Android studio 3.1.4，compileSdkVersion，targetSdkVersion，com.android.support:appcompat-v7:26.1.0等属性版本不一致，版本23可能太低了，  改成使用新建工程后的默认版本26，具体版本可参照新建工程后的版本，问题解决了。
### Log:

```日志中打印了屏幕相关信息

```

### Related Code:
```
  

```

**Comment by JessYanCoding** [comment]
ok，感谢贡献，已将该 issues 收录于 https://github.com/JessYanCoding/AndroidAutoSize/issues/13#7

**Comment by GeminiWy** [comment]
请问在不升级版本的情况下，这个问题有没有其他方案解决呢？FragmentManager.FragmentLifecycleCallbacks可以替换成其他的类吗？

**Comment by JessYanCoding** [comment]
@GeminiWy 使用旧版本 v0.7.0，里面不包含 FragmentManager.FragmentLifecycleCallback 以及 v7 包

**Comment by GeminiWy** [comment]
@JessYanCoding 谢谢

**Comment by TanJunDang** [comment]
sdk版本都改成了26  还是不行

**Comment by AndBird** [comment]
这个坑我也找了好久，需要support v4 25以上
implementation 'me.jessyan:autosize:1.1.1'
implementation 'com.android.support:support-v4:25.3.0'

**Comment by yuxuelian** [comment]
我也遇到了这个错误  这里分享一下我的解决经验
我报这个错误是因为我使用了AndroidX  这个工程还是使用的v4那套兼容包    在 gradle.properties 配置
android.useAndroidX=true
android.enableJetifier=true
这两个配置,重新编译  问题解决

**Comment by kongfanshuai** [comment]
java.lang.RuntimeException: Unable to get provider me.jessyan.autosize.InitProvider: java.lang.ClassNotFoundException: Didn't find class "me.jessyan.autosize.InitProvider"

**Comment by JessYanCoding** [comment]
@kongfanshuai multidex

**Comment by qrh672114236** [comment]
java.lang.ClassNotFoundException,Didn't find class "me.jessyan.autosize.InitProvider" on path: DexPathList[[zip file "/data/app/-1.apk"],nativeLibraryDirectories=[/data/app-lib-1, /vendor/lib, /system/lib, /data/datalib]],BaseDexClassLoader.java,56]

兼容测试部分手机运行报这个错误 ，App 已添加 MultiDex.install(this)  auto版本1.1.2   multidex版本1.0.3

**Comment by e9ab98e991ab** [comment]
AndroidAutoSize 0.7.0 + 1.1.2 综合版本
https://github.com/e9ab98e991ab/AndroidAutoSize

**Comment by Allen-ZXJ** [comment]
java.lang.ClassNotFoundException,Didn't find class "me.jessyan.autosize.InitProvider" on path: DexPathList[[zip file "/data/app/-1.apk"],nativeLibraryDirectories=[/data/app-lib-1, /vendor/lib, /system/lib, /data/datalib]],BaseDexClassLoader.java,56]

auto版本1.2.1，  系统android10，奔溃

**Comment by barrielin126-design** [comment]
如果用service调用dialog弹窗的怎么去适配啊
