### ISSUE TITLE
默认横屏显示，在关闭屏幕，再解锁进入或者回到桌面再次进入时，popupwindow和dialogfragment会出现适配失效。

### ISSUE THREAD

**Issue by leeManong** [JessYanCoding/AndroidAutoSize#33]
### Environment
- [x] Autosize Version:  v0.9.1
- [x] Target Android Version:  Android 8.0
- [x] Device Model:  华为荣耀8 
- [x] Device Resolution: 1080px * 1920px 
- [x] Design Size On AndroidManifest: 584dp * 830dp 

### Bug Description:
项目默认是横屏显示的，本来适配是正常的，但是在锁屏解锁后或者切到桌面再回到app会出现popupwindow和dialog适配失效。

### Log:

```
 D/AndroidAutoSize: designWidthInDp = 584, designHeightInDp = 830, screenWidth = 1920, screenHeight = 1080
 D/AndroidAutoSize: initDensity = 3.0, initScaledDensity = 3.0
 D/AndroidAutoSize: initScaledDensity = 3.0 on ConfigurationChanged
 D/AndroidAutoSize: cn.pluss.yunlan.paddiancan.activity.LoginActivity implemented by me.jessyan.autosize.internal.CustomAdapt!
 D/AndroidAutoSize: The cn.pluss.yunlan.paddiancan.activity.LoginActivity has been adapted! 
    LoginActivity Info: isBaseOnWidth = false, designHeightInDp = 830.000000, targetDensity = 1.214458, targetScaledDensity = 1.214458, targetDensityDpi = 194, targetXdpi = 1.214458
 D/AndroidAutoSize: cn.pluss.yunlan.paddiancan.activity.MainActivity implemented by me.jessyan.autosize.internal.CustomAdapt!
 D/AndroidAutoSize: The cn.pluss.yunlan.paddiancan.activity.MainActivity has been adapted! 
    MainActivity Info: isBaseOnWidth = false, designHeightInDp = 830.000000, targetDensity = 1.214458, targetScaledDensity = 1.214458, targetDensityDpi = 194, targetXdpi = 1.214458
 D/AndroidAutoSize: initScaledDensity = 3.0 on ConfigurationChanged
 D/AndroidAutoSize: initScaledDensity = 3.0 on ConfigurationChanged

```

### Screenshot
正常的效果
![qq 20180830151433](https://user-images.githubusercontent.com/26250827/44835797-d500ab80-ac67-11e8-88ff-620dc0f5aef6.jpg)
非正常效果
![qq 20180830151425](https://user-images.githubusercontent.com/26250827/44835801-d7fb9c00-ac67-11e8-8fbb-4b25a758c91c.jpg)

### Related Code:
```java
  

```

### Others:
DialogFragment也会出现这个问题，图就没截了。

**Comment by JessYanCoding** [comment]
回到 App 时调用 AutoSize.autoConvertDensity(getActivity(), 830, false);

**Comment by leeManong** [comment]
popupwindow如果本来就是show的状态，切回来时是正常的没有改变。但是这时重新new的popupwindow是不正常的。

我在Activity中onConfigurationChanged重新设置density，发现onConfigurationChanged有时会不回调。有时有作用有时没作用。于是我又在Application中registerComponentCallbacks中onConfigurationChanged设置栈顶的Activity的density，这样每次解锁屏幕时确实都会回调。但是有时还是会不起作用。

最后我把上面两种方法一起用，结果就没出现不起作用的情况了。

**Comment by JessYanCoding** [comment]
问题的原因还是，popupwindow 显示之前，density 的值不是预期的值，所以只要想办法，在 popupwindow 显示布局之前将 density 的值调整到期望的值就可以咯，所以我还是建议看看我新增的副单位，避免这些暗坑
