### ISSUE TITLE
请教一个ContentProvider 初始化的问题

### ISSUE THREAD

**Issue by yizems** [JessYanCoding/AndroidAutoSize#341]
https://github.com/JessYanCoding/AndroidAutoSize/blob/ee03f086a64f6f1aef450a97ac0d3174732457e0/autosize/src/main/java/me/jessyan/autosize/InitProvider.java#L39

我最近在查一个生产问题, 利用ContentProvider 这种方式进行SDK 的初始化 部分情况下会出现 application 为null 的情况, 请问你知道这个什么情况下会发生么? 

```
<provider
   android:name="me.jessyan.autosize.InitProvider"
   android:authorities="${applicationId}.autosize-init-provider"
   android:exported="false"
/>
```

**Comment by liuqi19-tal** [comment]
how  to solve it ？ 我在多进程的app里面也遇到了

**Comment by yizems** [comment]
<provider has a param, it can init in every process.

android:multiprocess="true"/>
