### ISSUE TITLE
是否适配Jetpack Compose?

### ISSUE THREAD

**Issue by lic2050** [JessYanCoding/AndroidAutoSize#348]

**Comment by JessYanCoding** [comment]
原理上，只要 Android SDK 不将 DP 计算的方式修改，任何框架都可以支持

**Comment by Dboy233** [comment]
这个我试过，是可以适配的。Compose的 .dp .sp都有效

**Comment by SerendipityMatthew** [comment]
我用了 compose 和 AutoSize， compose 总是弄不好 UI 的问题， 设备上Preview 和实际运行的有对齐的问题，把 AutoSize 去掉就解决了。

**Comment by qq71768174** [comment]
> 这个我试过，是可以适配的。Compose的 .dp .sp都有效

请问：compose中是如何配置和使用这个框架的？

**Comment by Dboy233** [comment]
> > 这个我试过，是可以适配的。Compose的 .dp .sp都有效
> 
> 请问：compose中是如何配置和使用这个框架的？

使用方式和Android 一样没区别

**Comment by janecer** [comment]
> 原理上，只要 Android SDK 不将 DP 计算的方式修改，任何框架都可以支持

我想知道，我当前项目用的是原始dp适配，项目引入了compose,同时引入autosize框架 我想改为副单位适配，比如mm。我在compose中如何写一个尺寸的单位 比如10.mm?

**Comment by JessYanCoding** [comment]
@janecer AutoSizeUtils#mm2px 代码里使用单位都需要用工具类转成 px
