### ISSUE TITLE
高度和宽度一维适配的讨论

### ISSUE THREAD

**Issue by houziershi** [JessYanCoding/AndroidAutoSize#35]
我们公司车载项目我采用的是适配：
https://github.com/yatoooon/AndroidScreenAdaptation

     
    private float calculateValue(float value) {
        if ("px".equals(unit)) {
            return value * ((float) actualWidth / (float) designWidth);
        } else if ("dp".equals(unit)) {
            int dip = dp2pxUtils.px2dip(actualDensity, value);
            value = ((float) designDpi / 160) * dip;
            return value * ((float) actualWidth / (float) designWidth);

        }
        return 0;
    }

原本设计以宽度作为标准进行适配，后面发现一个问题：byd车载的屏幕是：1000x1920 ; 按照标准图（宽高640x360(16:9) ），1920/640 = 3; 结果实际高度1000 < 1080 ；导致底部view被遮挡。

后面，我修改了该方法：

     /**
     * Description: 标准宽高640x360(16:9) density = 1.0 dpi = 160
     * 1. 高度低于设计高度，以高度作标准缩放；
     * 2. 高度高于设计高度，但是高度：宽度 < 9:16，以高度作标准缩放；
     * 3. 其余以宽度作标准缩放；
     * @param
     * @return
     */
    public float calculateValue(float value) {
        if ("px".equals(unit)) {
              return value * ((float) actualWidth / (float) designWidth);
          } else if ("dp".equals(unit)) {
            int dip = dp2pxUtils.px2dip(actualDensity, value);
             value = ((float) designDpi / 160) * dip;
             if (actualHeight < designHeight || actualWidth * designHeight / designWidth > actualHeight) {
                return value * ((float) actualHeight / (float) designHeight);
            }
            return value * ((float) actualWidth / (float) designWidth);
        }
        return 0;
    }

我提的问题是：
头条的方案，本质也是缩放，也会存在这个问题？不知你同意否？

**Comment by JessYanCoding** [comment]
兄弟，你可能还没使用 AndroidAutoSize，所以还不了解这个框架，AndroidAutoSize 其实不只能使用以宽作为基准，每个 Activity 甚至 Fragment 都可以自定义以高还是宽为基准，以及设计图尺寸，应用到你上面的需求无非就是在自定义的时候加个判断条件

**Comment by houziershi** [comment]
是的。 AndroidAutoSize 已经具备。

**Comment by JessYanCoding** [comment]
你说的 AndroidScreenAdaptation 这个框架，我之前看过源码，本身原理和 AndroidAutoLayout 非常相似，它是遍历 View Tree，挨个设置所有 View 的属性，本身是有性能损耗的，但 AndroidAutoSize 不会有性能损耗，使用也比 AndroidScreenAdaptation 简单，在加上新增的副单位解决了，修改 density 所造成的对三方库和系统控件的影响，可以说是目前性价比最高的屏幕适配方案

**Comment by houziershi** [comment]
是的。头条方案本身因为：一次修改，全局改变。后期维护无所适从。假如一处 UI 出问题了，你打算怎么改？你没法改，而且旧项目 UI 全都变了。所以才会放弃。 AndroidScreenAdaptation 这个框架，我使用后的总结是：放弃这个项目吧，不值得。光是缺点，你都改不过来。
对于你的这个项目： 我觉的最大的好处是解决了一次修改，全局改变的问题，利于修改和维护。这个方案这个时候就很值得推荐和使用了。同时，它还能自定义以宽或者高为维度进行适配。

**Comment by chenxi0203** [comment]
这样又会带来一个问题，如果以后要替换适配库那还不得改死，每个地方的单位都得变。

**Comment by JessYanCoding** [comment]
@chenxi0203 对，所以 AndroidAutoSize 可以同时支持 dp，sp 以及副单位，想使用哪个自行选择，没有完美的方案，只可能选择一个最适合自己的方案，你要减轻工作量避免影响其他三方库就用副单位，想要低侵入性就用 dp
