### ISSUE TITLE
Library contains references to both AndroidX and old support library. This seems like the library is partially migrated. Jetifier will try to rewrite the library anyway.

### ISSUE THREAD

**Issue by xxxifan** [JessYanCoding/AndroidAutoSize#352]
gradle提示：Library contains references to both AndroidX and old support library. This seems like the library is partially migrated. Jetifier will try to rewrite the library anyway.

**Comment by geeklx** [comment]
me.too

**Comment by JessYanCoding** [comment]
框架本身是迁移了 AndroidX 的，只是框架为了同时向下兼容 Support，所以也含有[兼容 Support 的代码](https://github.com/JessYanCoding/AndroidAutoSize/blob/master/autosize/src/main/java/me/jessyan/autosize/AutoSizeConfig.java#L165)，如果项目依赖 AndroidX 框架会走 AndroidX 的方式，如果项目依赖 Support 框架就走 Support 的方式，并且框架是使用 [compileOnly](https://github.com/JessYanCoding/AndroidAutoSize/blob/master/autosize/build.gradle#L29) 的方式依赖了这两个库，所以不用担心 Support 的代码也被打包进项目，这个提示如果不导致编译失败就可以忽略，以后会删除兼容 Support 的代码

**Comment by llllonger** [comment]
gradle新版本上面编译失败，提示就是上面的内容

**Comment by xxxifan** [comment]
> gradle新版本上面编译失败，提示就是上面的内容

版本号多少？我的7.0.2没有问题，只是会提示而已

**Comment by GuangNian10000** [comment]
我也是，只会警告
