### ISSUE TITLE
密度会动态改变，第一次加载正常

### ISSUE THREAD

**Issue by IsSwm** [JessYanCoding/AndroidAutoSize#36]
我出现了一个问题，密度会动态改变，我不知道是否与本库有关联。图片第一次加载时密度是正确的，滑动图片导致密度缩小了3倍左右。有可能是自身原因，目前解决方案是在全局写了一个变量保存第一次获取到的密度

### Screenshot

![image](https://user-images.githubusercontent.com/22268505/44966234-9d964580-af6c-11e8-9a7f-a43543ae6a1e.png)
![bings](https://user-images.githubusercontent.com/22268505/44966244-a7b84400-af6c-11e8-88f0-57bd269bffed.gif)

### Related Code:
```java
   //    dp 和 px 之间的转换
        fun dp2px(dip: Float): Int {
            val density = context.resources.displayMetrics.density
            return (dip * density + 0.5f).toInt()
        }

```

**Comment by JessYanCoding** [comment]
很有可能是你自身的代码导致的，因为框架的代码只会在  onCreate 中执行一次，后面不会在执行，所以绝对不会框架在持续不断的改变 density，AutoSizeConfig.getInstance().getInitDensity() 可以获取最初的 density

**Comment by IsSwm** [comment]
ok,可能我使用的这个轮播库造成的。导致图片有很多问题。
