### ISSUE TITLE
EditText 的复制和剪切字体显示看起来很小

### ISSUE THREAD

**Issue by haidao0810** [JessYanCoding/AndroidAutoSize#363]
<meta-data
            android:name="design_width_in_dp"
            android:value="750" />
        <meta-data
            android:name="design_height_in_dp"
            android:value="1334" />
输入框长按复制 弹出的操作宽很窄 字体也很小

**Comment by JessYanCoding** [comment]
https://github.com/JessYanCoding/AndroidAutoSize/issues/13
