### ISSUE TITLE
CancelAdapt失效

### ISSUE THREAD

**Issue by 330676687** [JessYanCoding/AndroidAutoSize#365]
`implementation 'androidx.appcompat:appcompat:1.3.0'`
更新该依赖到1.3.0，会导致CancelAdapt失效， 1.2.0版本正常

**Comment by AlbertLarry** [comment]
AutoSize.cancelAdapt(activity)

**Comment by 330676687** [comment]
> AutoSize.cancelAdapt(activity)

试了没用

**Comment by AlbertLarry** [comment]
最根本的原因是，onresume 没有走，然后 AutoSize.cancelAdapt 这个方法没有走到。你在自己的activity 的其他生命周期的时候，设置这个，应该是可以的，我这边是可以的

**Comment by jxtx123456** [comment]
cancelAdapt失效可能是基类中的getResources引起的，添加一个变量跳过就行了

![image](https://user-images.githubusercontent.com/10148767/146910034-90adfb1a-18f4-42ce-abfd-2036812d84c6.png)

**Comment by burnzl** [comment]
@Override
public Resources getResources() {
Resources oldResources = super.getResources();
if (mResources == null)
mResources = new Resources(oldResources.getAssets(), oldResources.getDisplayMetrics(), oldResources.getConfiguration());
Configuration cf = super.getResources().getConfiguration(); //获取设置的配置信息
int ori = cf.orientation; //获取屏幕方向
getHandler(this).post(new Runnable() {
@Override
public void run() {
if (ori == Configuration.ORIENTATION_LANDSCAPE) {
//横屏
AutoSizeCompat.autoConvertDensityBaseOnWidth(mResources, AutoSizeConfig.getInstance().getDesignHeightInDp());
} else if (ori == Configuration.ORIENTATION_PORTRAIT) {
AutoSizeCompat.autoConvertDensityBaseOnWidth(mResources, AutoSizeConfig.getInstance().getDesignWidthInDp());
}
}
});

return mResources;
}



在 2021-12-21 17:57:51，"jxtx123456" ***@***.***> 写道：

cancelAdaptshixia失效可能是基类中的getResources引起的，添加一个变量跳过就行了

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 330676687** [comment]
> @OverRide public Resources getResources() { Resources oldResources = super.getResources(); if (mResources == null) mResources = new Resources(oldResources.getAssets(), oldResources.getDisplayMetrics(), oldResources.getConfiguration()); Configuration cf = super.getResources().getConfiguration(); //获取设置的配置信息 int ori = cf.orientation; //获取屏幕方向 getHandler(this).post(new Runnable() { @OverRide public void run() { if (ori == Configuration.ORIENTATION_LANDSCAPE) { //横屏 AutoSizeCompat.autoConvertDensityBaseOnWidth(mResources, AutoSizeConfig.getInstance().getDesignHeightInDp()); } else if (ori == Configuration.ORIENTATION_PORTRAIT) { AutoSizeCompat.autoConvertDensityBaseOnWidth(mResources, AutoSizeConfig.getInstance().getDesignWidthInDp()); } } }); return mResources; } 在 2021-12-21 17:57:51，"jxtx123456" ***@***.***> 写道： cancelAdaptshixia失效可能是基类中的getResources引起的，添加一个变量跳过就行了 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

nice!!
