### ISSUE TITLE
SDK开发有无好的适配方式

### ISSUE THREAD

**Issue by kuroyukihime0** [JessYanCoding/AndroidAutoSize#366]
目前想到的方式是修改源码使用白名单的方式, 只适配SDK中的activity ;
如果集成sdk的产品用了autosize, 那就exclude掉修改过的;
感觉这样侵入还是比较大, 有无更好的方式?

**Comment by JessYanCoding** [comment]
建议不要在项目开发者不知情的情况下，帮他引入 autosize，由于 density 是全局的，所以在项目开发者不知情或者不熟悉该方案的情况下引入项目，可能会出现项目开发者解决不了的问题，除非你明确告知开发者，并且有完备的文档和解决方案。
