### ISSUE TITLE
Android 10适配不生效

### ISSUE THREAD

**Issue by lqx359** [JessYanCoding/AndroidAutoSize#367]
问题：如果开发者只是想要自己进行全局适配，把核心代码复制一份，在application进行初始化即可。非Android10系统只需要设置一次density值，但是在Android10机型上就不生效，但是取到的density是修改后的值。
修复：在application实现ActivityLifecycleCallBacks，在onActivityCreated方法中进行density的值设置  这样就没问题了。
有人能帮忙解释一下 为何！

**Comment by JessYanCoding** [comment]
因为在高版本上，Activity 的 getResource  和 Application 的 getResource 拿到是不同的 Resource 实例，所以在高版本上需要对每个 Activity 都进行设置 density
