### ISSUE TITLE
状态栏和标题栏中间有个间隔

### ISSUE THREAD

**Issue by JGNS** [JessYanCoding/AndroidAutoSize#37]
### Environment
- [x] Autosize Version: 
- [x] Target Android Version: 
- [x] Device Model: 
- [x] Device Resolution: 
- [x] Design Size On AndroidManifest: 

### Log:

```log


```

### Related Code:
```java
  

```

**Comment by JGNS** [comment]
大佬，排查了下，主要是我用了状态栏适配工具（blankj大佬的工具类）,注释掉就没问题了，大佬有自己的Q群吗，交流方便

**Comment by JGNS** [comment]
旋转，横屏，大佬试过没？是我代码问题吗，Toast变大很多

**Comment by JessYanCoding** [comment]
@JGNS QQ群-301733278

**Comment by JessYanCoding** [comment]
@JGNS 建议使用副单位，看看 demo-subunits
