### ISSUE TITLE
全局悬浮窗口，WindowManager里面添加view，重写rootView的generateLayoutParams方法，修改没有效果

### ISSUE THREAD

**Issue by ffyliu** [JessYanCoding/AndroidAutoSize#370]
### Environment
- [x] Autosize Version: 
- [x] Target Android Version: 
- [x] Device Model: 
- [x] Device Resolution: 
- [x] Design Size On AndroidManifest: 

device：华为mate9，分辨率1080*1920，android9.0

<meta-data
            android:name="design_width_in_dp"
            android:value="360" />
        <meta-data
            android:name="design_height_in_dp"
            android:value="640" />

### Bug Description:

已经看过，没有找到对应的解决办法。

### Log:

```log


```

### Screenshot

在android-studio中预览的效果：（预览用的是Pixel2）
![image](https://user-images.githubusercontent.com/43327380/128114074-7a66e55c-771b-4421-8bf7-bd2b92b7fee9.png)

真机上面实际展示效果：
![image](https://user-images.githubusercontent.com/43327380/128114183-4046362c-567e-4bce-959d-b3ce09b01366.png)

### Related Code:
```java
  
下面这个1080值，修改任意值都没有效果，都是上面固定的大小
@Override
    public LayoutParams generateLayoutParams(AttributeSet attrs) {
        AutoSizeCompat.autoConvertDensity(getResources(), 1080, true);//如果没有自定义需求用这个方法
        return super.generateLayoutParams(attrs);
    }

``
### Others:

**Comment by JessYanCoding** [comment]
https://github.com/JessYanCoding/AndroidAutoSize/issues/1#issuecomment-504654664

**Comment by ffyliu** [comment]
已经解决，非常感谢
@JessYanCoding

**Comment by JakeHao** [comment]
> 已经解决，非常感谢 @JessYanCoding

请教一下, 最后是如何解决的呢, 我也遇到同样的问题
