### ISSUE TITLE
做电视tv版，适配使用方式和app一样的吗？

### ISSUE THREAD

**Issue by OkamiyGit** [JessYanCoding/AndroidAutoSize#371]
### Environment
- [x] Autosize Version: 
- [x] Target Android Version: 
- [x] Device Model: 
- [x] Device Resolution: 
- [x] Design Size On AndroidManifest: 

### Log:

```log


```

### Related Code:
```java
  

```

**Comment by JessYanCoding** [comment]
对的

**Comment by ousq** [comment]
TV 适配用这个如何 @OkamiyGit
