### ISSUE TITLE
屏幕适配配置问题

### ISSUE THREAD

**Issue by Liyize97126** [JessYanCoding/AndroidAutoSize#374]
我的项目涉及到横屏的适配，我查阅网上资料后看到下图中的配置方式，项目中目前已使用AndroidManifest全局适配，想问一下作者这种配置方式能否同原有的适配方式同时使用，谢谢。
### 网上找到的初始化配置代码截图
![image](https://user-images.githubusercontent.com/62363765/129447913-ce38a48d-b5cc-45ec-a2fc-6653448baf20.png)

**Comment by JessYanCoding** [comment]
没问题

**Comment by Liyize97126** [comment]
好的，谢谢了
