### ISSUE TITLE
使用DataBind方式，会导致自适应框架失效

### ISSUE THREAD

**Issue by MrJiangDong** [JessYanCoding/AndroidAutoSize#376]
### Environment
- [x] Autosize Version: 
- [x] Target Android Version: 
- [x] Device Model: 
- [x] Device Resolution: 
- [x] Design Size On AndroidManifest: 

### Log:

```log


```

### Related Code:
```java
  

```

**Comment by JessYanCoding** [comment]
贴出日志，截图，相关代码
