### ISSUE TITLE
小米Mix2 Demo运行，底部留空

### ISSUE THREAD

**Issue by shengMR** [JessYanCoding/AndroidAutoSize#378]
直接使用demo运行手机上

### Environment
- [x] Autosize Version: v1.2.1
- [x] Target Android Version: Android 9
- [x] Device Model: XiaoMi MIX 2
- [x] Device Resolution: 1080 * 2160
- [x] Design Size On AndroidManifest: 360dp * 640dp

### Bug Description:
手机运行Demo，下方空出一个高度出来，类似Toolbar的高度，模拟器弄同样的像素尺寸的手机则正常

### Screenshot
![54C29373E83C4082C8F76707D2A27CCA](https://user-images.githubusercontent.com/23476485/136910771-7cf2bf7d-5b3e-43fe-9c29-83157db662af.jpg)

**Comment by JessYanCoding** [comment]
https://github.com/JessYanCoding/AndroidAutoSize/blob/master/demo/src/main/java/me/jessyan/autosize/demo/BaseApplication.java#L109
