### ISSUE TITLE
和Tinker热更新有冲突

### ISSUE THREAD

**Issue by ixiongyu** [JessYanCoding/AndroidAutoSize#38]
### Environment
- [x] Autosize Version:  0.9.1
- [x] Target Android Version:  Android 8.0 
- [x] Device Model:  Samsung S9+
- [x] Device Resolution:  1440px * 2960px
- [x] Design Size On AndroidManifest: 360dp * 640dp
- [x] Tinker Version: 1.9.2

### Log:

```log
09-04 15:04:36.299 7450-7450/xx.xx D/AndroidAutoSize: designWidthInDp = 0, designHeightInDp = 0, screenWidth = 1440, screenHeight = 2960
09-04 15:04:36.300 7450-7450/xx.xx D/AndroidAutoSize: initDensity = 3.5, initScaledDensity = 2.8


```

### Screenshot

![image](https://user-images.githubusercontent.com/11729558/45016055-1b824b80-b056-11e8-8758-4a4c696c297d.png)

这是全部日志，可以看到没有执行DefaultAutoAdaptStrategy中的方法打印出相应的log
![image](https://user-images.githubusercontent.com/11729558/45015330-f096f800-b053-11e8-9dd9-7331e2e4ce1c.png)
这是AutoSizeConfig中获取到的appcation的相关信息
### Related Code:
```java
  
```

### Others:

整合了tinker（DefaultLifeCycle注解的方式）之后就不起作用了，DefaultAutoAdaptStrategy中的applyAdapt都不会执行。适配失败

**Comment by JessYanCoding** [comment]
问题原因很有可能是进程导致的，DefaultAutoAdaptStrategy 注册的进程和你这个 Activity 所在的进程不是同一个，所以才不会执行 DefaultAutoAdaptStrategy 中的 log

**Comment by JessYanCoding** [comment]
使用 **v0.9.5**，**implementation 'me.jessyan:autosize:0.9.5'**，然后调用 **AutoSize#initCompatMultiProcess(Context)**，像 [这样](https://github.com/JessYanCoding/AndroidAutoSize/blob/master/demo/src/main/java/me/jessyan/autosize/demo/BaseApplication.java#L77)

**Comment by ixiongyu** [comment]
好的 谢啦

**Comment by BingoKingCoding** [comment]
> 使用 **v0.9.5**，**implementation 'me.jessyan:autosize:0.9.5'**，然后在 **App** 初始化时调用 **AutoSize#initCompatMultiProcess(Context)**，像 [这样](https://github.com/JessYanCoding/AndroidAutoSize/blob/master/demo/src/main/java/me/jessyan/autosize/demo/BaseApplication.java#L77)

使用这种方式也是失效的

**Comment by JessYanCoding** [comment]
@BingoKingCoding https://github.com/JessYanCoding/AndroidAutoSize/issues/13#11
