### ISSUE TITLE
setExcludeFontScale(true) 不生效

### ISSUE THREAD

**Issue by breewf** [JessYanCoding/AndroidAutoSize#380]
### Environment
- [x] Autosize Version: 1.2.1
- [x] Target Android Version: Android 11
- [x] Device Model: OnePlus 8T
- [x] Device Resolution: 1080px * 2400px
- [x] Design Size On AndroidManifest: 375dp * 667dp

### Bug Description:
关闭主单位 sp 支持，setSupportSP(false) 同时设置 setExcludeFontScale(true) 屏蔽系统字体大小带来的影响，isExcludeFontScale 结果为 true，设置正确，但是修改系统字体大小后使用 sp 单位的字体大小仍受系统调节的影响。

AutoSize 中 setDensity(DisplayMetrics displayMetrics, float density, int densityDpi, float scaledDensity, float xdpi)方法中，有如下判断：

`
if (AutoSizeConfig.getInstance().getUnitsManager().isSupportSP()) {
            displayMetrics.scaledDensity = scaledDensity;
        }
`

因为 isSupportSP()为 false 而不走此逻辑，但 scaledDensity 的计算又受到 isExcludeFontScale 的影响。如何在 setSupportSP(false) 的情况下同时设置 setExcludeFontScale(true) 来屏蔽系统字体大小设置带来的影响呢？

**Comment by JessYanCoding** [comment]
你的需求，对于框架来说是矛盾的，因为 setSupportSP(false) 是框架放弃对 sp 的适配，并不是让 Android 系统放弃对 sp 的适配，而 setExcludeFontScale 和 setPrivateFontScale 这两个功能都是基于 setSupportSP 为 true 时的延伸功能。

setSupportSP(false) 只是表明框架不会影响 sp 的最终值，但是即使框架不介入 sp 的计算，sp 的系统默认特性本来就是会根随系统字体大小的改变而改变的。

所以要想改变 sp 的系统默认特性，让 sp 不跟随系统字体大小的改变而改变，反而要将 setSupportSP 设为 true，setExcludeFontScale(true)，让框架介入 sp  的计算，从而影响最终的结果

**Comment by breewf** [comment]
是的，不使用这种方案了，感谢回复。
