### ISSUE TITLE
Android 12 页面布局错乱，其他系统正常，已经尝试“已知问题”相关方案未解决

### ISSUE THREAD

**Issue by xiuqiao** [JessYanCoding/AndroidAutoSize#389]
### Environment
- [x] Autosize Version: 
- [x] Target Android Version: 
- [x] Device Model: 
- [x] Device Resolution: 
- [x] Design Size On AndroidManifest: 

### Log:

```log


```

### Related Code:
```java
  

```

**Comment by JessYanCoding** [comment]
有截图吗

**Comment by xiuqiao** [comment]
感谢，已解决，由于功能上有个地方会通过 createConfigurationContext 动态修改  resource 用法错误导致每次创建新的Resource。但是除 Android 12 在其他版本即使修改了 Resource 布局也正常，只有12上布局错乱了，具体原因还不清楚，猜测和每次都创建新的Resource导致。

> 有截图吗
