### ISSUE TITLE
JDK 11 编译问题

### ISSUE THREAD

**Issue by zhangnin** [JessYanCoding/AndroidAutoSize#390]
环境：
JDK 11
Studio 7.1.2
Gradle gradle-7.2-bin.zip

编译时报了一个警告：

[Processor] Library 'C:\Users\Administrator\.gradle\caches\modules-2\files-2.1\com.github.JessYanCoding\AndroidAutoSize\v1.2.1\a44df9822e0cb91242358f070ef813714fd81c05\AndroidAutoSize-v1.2.1.aar' contains references to both AndroidX and old support library. This seems like the library is partially migrated. Jetifier will try to rewrite the library anyway.

翻译：
包含对 AndroidX 和旧支持库的引用。这似乎图书馆已部分迁移。 Jetifier 无论如何都会尝试重写库。

**Comment by JessYanCoding** [comment]
https://github.com/JessYanCoding/AndroidAutoSize/issues/352
