### ISSUE TITLE
手机重启，快速打开app，适配失效

### ISSUE THREAD

**Issue by Dboy233** [JessYanCoding/AndroidAutoSize#394]
手机重启之后，刚进入桌面，马上点开app，大概率会出现适配失效。。。
google手机android 9.0

**Comment by JessYanCoding** [comment]
延迟一会儿点开 App 就不会适配失效吗，日志里有 exception 吗
可以考虑可能是初始化机制可能没生效，可以断点 [这个位置](https://github.com/JessYanCoding/AndroidAutoSize/blob/master/autosize/src/main/java/me/jessyan/autosize/InitProvider.java#L42) 看看在 App 打开时，是否调用，没调用就使用 [#249] 的方法，自行初始化

**Comment by Dboy233** [comment]
> 延迟一会儿点开 App 就不会适配失效吗，日志里有 exception 吗 可以考虑可能是初始化机制可能没生效，可以断点 [这个位置](https://github.com/JessYanCoding/AndroidAutoSize/blob/master/autosize/src/main/java/me/jessyan/autosize/InitProvider.java#L42) 看看在 App 打开时，是否调用，没调用就使用 [#249] 的方法，自行初始化

是我，我想应该也是这个问题。
