### ISSUE TITLE
oppo Android 12 空指针

### ISSUE THREAD

**Issue by wr1024** [JessYanCoding/AndroidAutoSize#398]
- [x] Autosize Version: 
- [x] Target Android Version: 
- [x] Device Model: 

异常信息：
 java.lang.NullPointerException
Attempt to invoke interface method 'void me.jessyan.autosize.AutoAdaptStrategy.applyAdapt(java.lang.Object, android.app.Activity)' on a null object reference
com.xxx.BaseActivity.onStart(BaseActivity.java:96)

出错堆栈：
 me.jessyan.autosize.ActivityLifecycleCallbacksImpl.onActivityStarted(ActivityLifecycleCallbacksImpl.java:74)
android.app.Application.dispatchActivityStarted(Application.java:400)
android.app.Activity.dispatchActivityStarted(Activity.java:1369)
android.app.Activity.onStart(Activity.java:1894)
androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:495)
androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:246)
com.xxxxx.BaseActivity.onStart(BaseActivity.java:96)
android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1470)
android.app.Activity.performStart(Activity.java:8154)
android.app.ActivityThread.handleStartActivity(ActivityThread.java:3799)
android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
android.app.ActivityThread$H.handleMessage(ActivityThread.java:2341)
android.os.Handler.dispatchMessage(Handler.java:106)
android.os.Looper.loopOnce(Looper.java:233)
android.os.Looper.loop(Looper.java:344)
android.app.ActivityThread.main(ActivityThread.java:8184)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)

**Comment by JessYanCoding** [comment]
你自己断点看下，报空指针的位置在[调用前明明是判了空的](https://github.com/JessYanCoding/AndroidAutoSize/blob/e402ecdd99/autosize/src/main/java/me/jessyan/autosize/ActivityLifecycleCallbacksImpl.java#L73)，既然能走进判断里面的代码 (框架初始化完成会有一个框架默认的实现，正常流程下永远不会为null)，那说明有地方在判空通过之后调用了 setAutoAdaptStrategy#setAutoAdaptStrategy(null)，或者这个报错 Log 根本不是问题所在，只是 App 已经发生奔溃，内存被回收，才报空
