### ISSUE TITLE
小米8 上面适配没有成功  界面展示异常

### ISSUE THREAD

**Issue by XuMuFei** [JessYanCoding/AndroidAutoSize#4]

**Comment by JessYanCoding** [comment]
截图，以及框架的打印日志，日志中搜索 **AndroidAutoSize** 可以看到日志

**Comment by JessYanCoding** [comment]
是否加入了 WebView?

**Comment by Firedamp** [comment]
去年写了个类似的方案用于项目中。
看到朋友在我方案中的留言就过来看看哈。
项目中有一些共性问题可以一起探讨，我在我那边的Q&A也写了一些；
以及也修复过一些在特定MIUI上才会出现的问题。

**Comment by JessYanCoding** [comment]
@Firedamp 你好，感谢分享，你的这个开源项目，很不错，我去年就关注过，当时比较忙就没有重视，直到今日头条分享出来后，才开始重新关注，于是才有了这个框架，原理和你的都差不多，只是用的单位不同，按理说你的方案影响范围还小一点，你开源比较久，很多遇到的问题都可以借鉴你的

想请教你两个问题：

1.这个 MIUI 失效的问题，就是通过 RudenessScreenHelper#getMetricsOnMiui(context.getResources()); 这个方法解决的把？

2. 在 onActivityStarted 和 onActivityResumed 重新设置 density 是为了解决什么问题

**Comment by Firedamp** [comment]
1. 这个MIUI失效的问题我不确定，因为你说的这个方法我当时是为了解决在MIUI7+Android5.x上复现的一个问题，该问题在其他版本MIUI上很少出现，当时是扒了MIUI代码才找到问题的；
2. 反正就一行代码又不费性能，我在能加的地方都加了；

**Comment by JessYanCoding** [comment]
刚刚有个 Issues，是 小米note3，版本是 miui9 8.3.1 开发版，发现你这个代码可以解决这个问题，感谢贡献

**Comment by Firedamp** [comment]
有没有兴趣来阿里工作
