### ISSUE TITLE
平板适配起来很糟糕 

### ISSUE THREAD

**Issue by shenhuanet** [JessYanCoding/AndroidAutoSize#40]
平板适配起来很糟糕

**Comment by JessYanCoding** [comment]
实际效果，和期望效果截图，详细描述，都给到我，才能帮你解决问题

**Comment by 13kmsteady** [comment]
@shenhuanet 我的也是平板项目，使用的这个适框架。在 10.1，21，32 寸的设备上发现适配的效果都挺好的。

**Comment by shenhuanet** [comment]
@JessYanCoding 比如加入Toolbar，高度会变大，显得很庞大

**Comment by JessYanCoding** [comment]
@shenhuanet 这个是正常的，等比例放大，在这个框架上，不管是平板还是 TV 和手机的适配效果没有任何区别，都是用同样的比例放大，框架不存在对 平板 和 TV  的适配效果单独处理这一说，只可能手机的设计图等比例放大后，你觉得在平板上感觉很大，这些是正常的这就是百分比库的特性，不管是小屏还是大屏在百分比库的作用下都只能显示相同的内容
