### ISSUE TITLE
啊啊

### ISSUE THREAD

**Issue by coolmaye** [JessYanCoding/AndroidAutoSize#401]
两次切换到后台，dialog里面的rv直接失去适配，变的很大，用各种方法均无法解决，行吧，你就当我是个菜逼，我还这种菜逼还真领略不到rv和dialog什么时候能和屏幕密度挂上钩。

**Comment by JessYanCoding** [comment]
兄弟，你觉得你遇到的问题很多，抱怨一下，我也很能理解，不过，既然你认为这个库是个一无是处的 XX 玩意儿，何必两年时间还在使用这个库呢，自己写一个屏幕适配，或者切换为现存的其他方案，也需要不了你几天时间把。

你觉得一个产品真的的很难用，还一直使用，心里难受，工作量增加，感觉一直在受虐，又不弃坑，何必呢，兄弟，我这个是免费开源的框架，又没收你一分钱，对你来说切换又不需要付出啥成本，你吐槽完后，改变不了什么，该改的 bug 一个不少，我是你，有这时间吐槽，还不如想想如何切换到其他屏幕适配框架，做些对自己切实可用的事。

**Comment by JessYanCoding** [comment]
建议你以后给任何开源库提 issues 前，调整好心态，戾气不要这么重，要说技术就好好说技术，不要说与技术无关的废话，任何开源作者也没有收你的费，不需要舔着脸为你做有偿服务，感受到了你这不友好的语气，也不可能还能认真的解决你的问题。

你要是想解决问题，态度调整好，大家互相尊重，如果厌恶了某个库，不想再使用也不需要在这浪费时间，大家都很忙，开源作者也没求着你用这个库，也没收你钱，即使开源库不合你意，你觉影响了你自己的工作，这个也都是你自己的选择。
