### ISSUE TITLE
多次点击有网络请求的控件会出现崩溃问题

### ISSUE THREAD

**Issue by yonglf** [JessYanCoding/AndroidAutoSize#43]
### Environment
- [x] Autosize Version: 
- [x] Target Android Version: 
- [x] Device Model: 
- [x] Device Resolution: 
- [x] Design Size On AndroidManifest: 

### Log:

```log


```

### Related Code:
```java
  

```

**Comment by yonglf** [comment]
注释掉这个插件后 一切正常

**Comment by JessYanCoding** [comment]
截图，错误信息，详细描述，什么都没有，无法帮你解决问题
