### ISSUE TITLE
windowmanager中的view整体变小

### ISSUE THREAD

**Issue by winter110** [JessYanCoding/AndroidAutoSize#430]
我有一个系统APP，用的autsize1.2.1版本，每次启动时都是用startService启动一个service，在service中获取WindowManager，把创建的view添加到windowmanager里，有时会出现view整体变小了，我看这些解决方案都是让调用AutoSize.autoConvertDensityOfGlobal()，可是相关的方法都需要一个activity对象，我的app里只有一个空壳activity，启动是也不会启动它，这种情况应该怎么办？

**Comment by zongren** [comment]
解决了吗朋友，我遇到一模一样的情况

**Comment by winter110** [comment]
> 解决了吗朋友，我遇到一模一样的情况

我在service的oncreate里添加了下面两行代码后，目前还没出现过这个问题了
AutoSizeCompat.autoConvertDensityOfGlobal(super.getResources());
AutoSizeCompat.autoConvertDensity(super.getResources(), 1280, true);
