### ISSUE TITLE
布局预览错乱

### ISSUE THREAD

**Issue by booldplx** [JessYanCoding/AndroidAutoSize#438]
你好，请问一下我现在XML布局预览只有指定设备为TV的时候才可以正常预览，而选择任何手机的时候都会显示错乱，比如一个40dp高度的按钮就能占手机显示高度的一半了。而实际运行起来是没有问题的，请问我是哪里设置错误了吗？谢谢

**Comment by JessYanCoding** [comment]
https://github.com/JessYanCoding/AndroidAutoSize/blob/master/README-zh.md#preview
