### ISSUE TITLE
Android 14 Cannot showing default system SoftKeyboard

### ISSUE THREAD

**Issue by SamTang2014** [JessYanCoding/AndroidAutoSize#452]
### Environment
- [x] Autosize Version: 1.2.1
- [x] Target Android Version: Android 14
- [x] Device Model: Pixel 6a/ Pixel 4a 5g

### Bug Description:
Just a kindly remind, SoftKeyboard cannot showing in android 14 when using  `AutoSizeCompat.autoConvertDensityOfGlobal((super.getResources()));`

**Comment by 98Degree** [comment]
Have you solved this problem

**Comment by liuyan0619** [comment]
Have you solved this problem

**Comment by xiaolunan** [comment]
我是删除以下代码解决了
@OverRide
public Resources getResources() {
//需要升级到 v1.1.2 及以上版本才能使用 AutoSizeCompat
AutoSizeCompat.autoConvertDensityOfGlobal((super.getResources()));
返回 super.getResources();
}

**Comment by Chinahuangzhengyu** [comment]
![1703302985110](https://github.com/JessYanCoding/AndroidAutoSize/assets/30626728/2832e7de-e0ff-494c-b144-931902268188)

**Comment by daleige** [comment]
#### Reason:

Android 14 popped up a soft keyboard and called the getResource method, which was in a child thread, while the autoConvertDensity method verified whether it was the main thread
![image](https://github.com/JessYanCoding/AndroidAutoSize/assets/12762466/46d64055-a23e-40fd-9aff-056bcdb084a3)

#### Solution:

The autoConvertDensity method is only called on the main thread
```kotlin
    override fun getResources(): Resources {
        if (ThreadUtils.isMainThread() && super.getResources() != null) {
            // AutoSizeCompat.autoConvertDensityOfGlobal((super.getResources()));
            AutoSizeCompat.autoConvertDensity(super.getResources(), 380f, true)
        }
        return super.getResources()
    }
```
