### ISSUE TITLE
统一隐私政策之前初始化sdk，因为调用了getApplicationInfo提示不合规，怎么处理

### ISSUE THREAD

**Issue by h-zhouwenjun** [JessYanCoding/AndroidAutoSize#454]
### Environment
- [x] Autosize Version: 
- [x] Target Android Version: 
- [x] Device Model: 
- [x] Device Resolution: 
- [x] Design Size On AndroidManifest: 

### Log:

```log


```

### Related Code:
```java
  

```

**Comment by h-zhouwenjun** [comment]
![Uploading AAE2F119-2C20-427e-AC0C-F5D224469D2B.png…]()

**Comment by JessYanCoding** [comment]
https://github.com/JessYanCoding/AndroidAutoSize/issues/249  取消自动初始化，在合适时间手动初始化
