### ISSUE TITLE
使用AndroidAutoSize:0.9.5版登录布局偶现错乱和崩溃（紧急）

### ISSUE THREAD

**Issue by jacksPeak** [JessYanCoding/AndroidAutoSize#48]
设备信息：
设备：honor
Android：7.0
EMUI版本：5.0.1
崩溃日志:

![image](https://user-images.githubusercontent.com/13911593/45466623-9bdb3780-b74d-11e8-95c9-1e4087029c18.png)
![image](https://user-images.githubusercontent.com/13911593/45466633-ae557100-b74d-11e8-8fcd-e4fa3f4e487c.png)

注释AndroidAutoSize依赖解决了问题

**Comment by JessYanCoding** [comment]
更新 v0.9.5 才出的问题，还是旧版本都有问题

**Comment by JessYanCoding** [comment]
建议你把，你项目的依赖环境，和布局搬到官方的 demo 上，看是否报错，这样才可能找到问题，你这个问题报的错和这个框架一点关系都没

**Comment by jacksPeak** [comment]
之前用的v0.8.0有这个问题升级到了v0.9.5还是会有这个问题，只在上述机型上遇到了此问题切注释掉AndroidAutoSize的依赖才不会遇到问题。这个日志是crash之后的唯一异常日志

**Comment by JessYanCoding** [comment]
你需要向我上面描述的那样操作，找出发生错误的真正问题，我没有你的这个手机，也没有你的 App 以及开发环境，你不这样做，我是无法解决问题的

**Comment by lwlizhe** [comment]
这问题解决了么？看着有点慌啊……
请问是框架的问题么？

**Comment by jacksPeak** [comment]
目前项目有点忙还没来得及找原因，不过确实取消依赖以后不会出现问题了。当时布局会错乱（TextInputLayout布局下移甚至crash）AppCompatCheckBox点击选中后消失。等过了这阵子我会测试测试的

**Comment by kouhengsheng** [comment]
me too

**Comment by JessYanCoding** [comment]
@kouhengsheng 向上面我说的这样做，找出问题，才能解决问题
