### ISSUE TITLE
一个页面不能同时支持dp和副单位适配

### ISSUE THREAD

**Issue by liaohuyu** [JessYanCoding/AndroidAutoSize#49]
如题，问题不大~~

**Comment by liaohuyu** [comment]
追加一个问题，为什么副单位都是修改的DisplayMetrics.xdpi，而不是ydpi，是因为TypedValue计算的时候只用到xdpi么？

**Comment by JessYanCoding** [comment]
可以的，在是我在设计时就已经考虑了的，demo-subunits 不可以，是因为设置了 AutoSizeConfig.getInstance().getUnitsManager().setSupportDP(false); ，把这行代码去掉，只保留 AutoSizeConfig.getInstance().getUnitsManager().setSupportSubunits(Subunits.MM); 即可 dp 和副单位都支持，自己在 Demo 上实验

**Comment by JessYanCoding** [comment]
对
```java
public static float applyDimension(int unit, float value,
                                       DisplayMetrics metrics)
    {
        switch (unit) {
        case COMPLEX_UNIT_PX:
            return value;
        case COMPLEX_UNIT_DIP:
            return value * metrics.density;
        case COMPLEX_UNIT_SP:
            return value * metrics.scaledDensity;
        case COMPLEX_UNIT_PT:
            return value * metrics.xdpi * (1.0f/72);
        case COMPLEX_UNIT_IN:
            return value * metrics.xdpi;
        case COMPLEX_UNIT_MM:
            return value * metrics.xdpi * (1.0f/25.4f);
        }
        return 0;
    }
```
系统只用到了 xdpi，那如果我改 ydpi 就毫无意义了

**Comment by liaohuyu** [comment]
我试了下   同一个页面不能一起支持哦。     if (isBaseOnWidth) {
                targetDensity = AutoSizeConfig.getInstance().getScreenWidth() * 1.0f / sizeInDp;
            } else {
                targetDensity = AutoSizeConfig.getInstance().getScreenHeight() * 1.0f / sizeInDp;
            }
            targetScaledDensity = targetDensity * (AutoSizeConfig.getInstance().
                    getInitScaledDensity() * 1.0f / AutoSizeConfig.getInstance().getInitDensity());
            targetDensityDpi = (int) (targetDensity * 160);

            if (isBaseOnWidth) {
                targetXdpi = AutoSizeConfig.getInstance().getScreenWidth() * 1.0f / sizeInDp;
            } else {
                targetXdpi = AutoSizeConfig.getInstance().getScreenHeight() * 1.0f / sizeInDp;
            }

            mCache.put(key, new DisplayMetricsInfo(targetDensity, targetDensityDpi, targetScaledDensity, targetXdpi));，sizeInDp是固定了的，只能支持一个。。。。        可以请教下，ydpi系统什么用到了么？

**Comment by JessYanCoding** [comment]
可以，经过了测试的，你复制的代码根本不是支持副单位和 dp 的核心代码，如果你 **manifest** 写的是像素值，布局中有副单位和dp，那布局中的高宽值，全部用设计图中的像素，不要在将像素除以 density，除以 density 当然不行

直接在 demo-subunits 测试，把 **AutoSizeConfig.getInstance().getUnitsManager().setSupportDP(false); ** 删掉，将布局里面的部分 **mm** 换成 **dp**，得到布局效果和全部使用 **mm** 布局是一样的，除非我们两个用的不是一个东西，不然不可能不可以

**Comment by liaohuyu** [comment]
这个明白了，我以为dp还是要正常dp。感谢大佬百忙之中的细心解答。
