### ISSUE TITLE
请教大神，v7包下的AlertDialog 弹出时超出屏幕该怎么解决，其他UI都可以完美适配

### ISSUE THREAD

**Issue by luping1994** [JessYanCoding/AndroidAutoSize#50]
### Environment
- [x] Autosize Version:  v0.9.1
- [x] Target Android Version:  Android 7.0
- [x] Device Model:华为平板
- [x] Device Resolution:  800px * 1280px
- [x] Design Size On AndroidManifest: 360dp * 640dp

### Bug Description:
AlertDialog 弹出时超出屏幕,具体请看下面的截图

### Log:

```log


```

### Screenshot

![qq 20180913155216](https://user-images.githubusercontent.com/17812279/45475075-e076cb00-b76d-11e8-9797-7c776abf0f1e.jpg)

### Related Code:
```java
  

```

**Comment by LouisShark** [comment]
@luping1994 请问你是怎么解决的。。
