### ISSUE TITLE
DefaultErrorActivity.class是针对于三方库举例的类吧？

### ISSUE THREAD

**Issue by SimpleGentleman** [JessYanCoding/AndroidAutoSize#51]
### Environment
- [x] Autosize Version: 
- [x] Target Android Version: 
- [x] Device Model: 
- [x] Device Resolution: 
- [x] Design Size On AndroidManifest: 

### Log:

```log


```

### Related Code:
```java
  

```

**Comment by SimpleGentleman** [comment]
抱歉多问一句，在创建实时预览布局虚拟设备时，为何计算对角线尺寸是除以72，而不是除以410左右呢？不是指手机的逻辑密度值嘛？ 
 那对于750*1334 的设计稿尺寸，以pt副单位标注，创建虚拟设备值对角长度怎么算，除数是多少，没看懂你这边为何是72？  谢谢！@JessYanCoding

**Comment by JessYanCoding** [comment]
我的公式不写的很清楚吗，只有用 DP 为单位的时候，公式 (sqrt(纵向分辨率^2+横向分辨率^2))/dpi，除数不是固定的，dpi 是根据你的实际设备算出来的

其他单位，诸如 pt 的公式 (sqrt(纵向分辨率^2+横向分辨率^2))/72，除数 72 是固定不变的

mm 的公式 (sqrt(纵向分辨率^2+横向分辨率^2))/25.4，除数 25.4 也是固定不变的

为什么这些副单位，除数不变，而 dp 的除数会变，这也不是我猜的，可能你没认真看我的文章，这个是系统定的

```java
public static float applyDimension(int unit, float value,
                                       DisplayMetrics metrics)
    {
        switch (unit) {
        case COMPLEX_UNIT_PX:
            return value;
        case COMPLEX_UNIT_DIP:
            return value * metrics.density;
        case COMPLEX_UNIT_SP:
            return value * metrics.scaledDensity;
        case COMPLEX_UNIT_PT:
            return value * metrics.xdpi * (1.0f/72);
        case COMPLEX_UNIT_IN:
            return value * metrics.xdpi;
        case COMPLEX_UNIT_MM:
            return value * metrics.xdpi * (1.0f/25.4f);
        }
        return 0;
    }
```

**Comment by JessYanCoding** [comment]
针对第一个问题，我注释都写的很清楚，如果你用副单位的话，不必理会

**Comment by SimpleGentleman** [comment]
第一个问题，我明白，如果是副单位，直接就隔离了外部三方库，是不用理会；
第二个我知道了，是系统源码就这样计算的，抱歉；
最终谢谢你这么详细的解答，很感谢！

**Comment by JessYanCoding** [comment]
这里还要补充一下，为了让副单位都能达到最好的预览效果，通过公式算出的模拟器的屏幕尺寸都是非常大的，这会导致什么呢，就是如果你将控件高宽设置成 wrap_content，预览效果会显示的非常小，比如你将一个 ImageView 的高宽设置成 wrap_content，那这个图片在预览时会显得非常小，因为图片大小没变，模拟器的屏幕尺寸非常大，所以预览效果会非常小，这是无解的

但是不用担心，wrap_content 只是让 Preview 的预览效果非常小，运行到实际设备上，是不会有变化的，因为实际设备的屏幕尺寸是正常的

**Comment by ytsxg123** [comment]
我今天创建了一个pt的预览，image wrap_content出现了较大的问题，这个预览问题有没有好的解决方案或者编码规范可以去处理这个事情。
