### ISSUE TITLE
DisplayMetrics  自己输出 和 三方库 输出的值不一致

### ISSUE THREAD

**Issue by jiaqingrui** [JessYanCoding/AndroidAutoSize#52]
我设置的尺寸是375 * 667
我代码输出了一下我屏幕 的尺寸 1080*1920  density=2.75 densityDpi440
我用咱这个库 打印的日志 是 
isBaseOnWidth = true, designWidthInDp = 375.000000, targetDensity = 2.880000, targetScaledDensity = 2.880000, targetDensityDpi = 460, targetXdpi = 2.880000
和系统 DisplayMetrics 输出的不太一样

**Comment by JessYanCoding** [comment]
发现你根本不懂今日头条这个方案，建议你认真看下我的 [文章](https://www.jianshu.com/p/55e0fca23b4f) 这个方案的核心就是修改 DisplayMetrics 的参数达到屏幕适配的效果，如果 DisplayMetrics 的参数一致保持和系统不变那这个库有什么存在的意义
