### ISSUE TITLE
关于屏幕适配的这三个库的比较

### ISSUE THREAD

**Issue by lwlizhe** [JessYanCoding/AndroidAutoSize#54]
非常感谢博主的开源精神，不过对于我这种工期赶，任务重的情况，我更希望能有一个稳定的开源框架，请问Rudeness、AndroidUtilCode还有AndroidAutoSize，这三个库都有什么特点或者不同么？
这不是提bug，因此如果有什么不妥的地方，可以关闭，不过还是博主能回答一下，非常感谢…………

**Comment by lwlizhe** [comment]
对了还有一点，我们UI有个设计，某个页面是需要纵向适配的……但是其他页面是需要横向适配的……所以说，有没有提供切换方向的这个功能？好像看readme中没有提到这块……

**Comment by JessYanCoding** [comment]
1. 你问这个问题之前肯定是没有认真调研过这三个库的，甚至可能连 **Demo** 都可能没跑过，你说的切换适配方向是最基础的功能，这个功能在 **Demo** 中都有展示，别说 **Activity** 可以自由切换方向和设计图尺寸，连 **Fragment** 也可以自由切换方向和设计图尺寸，建议你看看 **Demo**，你如果你认真看看我的注释和文档，你就知道这个库的用心程度，这也是很多人愿意选择 **AndroidAutoSize** 的原因

2. 其他两个库，我写这个库之前都看过，你可能不怎么了解这个方案，也没看过我库的源码，所以可能有在选择上的疑惑，我这个库和那两个库，核心原理是一样的，但是他们只是把这个方案，当成了工具类来封装，因为他们的不足，所以我才写了 AndroidAutoSize 这个库，在写之前我也是深入研究了今日头条这个方案和其他类似方案，所以也写了一篇 [科普文章](https://juejin.im/post/5b7a29736fb9a019d53e7ee2)，反响还不错

这个库不止是把今日头条的方案封装，还扩展了很多其他功能，这一点从代码就可以看出来，他们的库 200 行代码不到，我这个库代码少说 2000 行代码，因为我不是把这个方案当成工具类来封装，而是当成一个独立的库，他们两个库有的功能我这个库都有，而且还扩展了更多的功能，优化了很多东西，更成熟稳定，所以这个库才开源一个月就拿了近 3k star，就是因为它和其他库相比是有差异化的

你要说这个三个库的对比，AndroidUtilCode 支持 dp 来适配，Rudeness 支持 pt 来适配，原理都是一样的，AndroidAutoSize 原理也一样，支持 dp、sp、pt、in、mm，以及一些其他的功能，简单理解就是 AndroidAutoSize 他们的完善版本，不然 AndroidAutoSize 也没存在的意义

[MVPArms](https://github.com/JessYanCoding/MVPArms) 会接入 AndroidAutoSize，现在已经有上千个项目接入 AndroidAutoSize，开源项目就是这样，用的人越多，越稳定，因为踩的坑越多

**Comment by lwlizhe** [comment]
额，非常感谢解答，其实我关注这个今日头条方案蛮早的（笑~~）他们字节跃动技术团队好像在知乎发过，不知道是不是首发，我也是早早在下面评论过（PS：那篇文章确实有一点很有争议）…………后来没怎么继续关注，是因为那个今日头条方案其实不是很成熟，自己也写过demo，发现跟其他人一样，出现过很多种异常，因此也放弃了关注…………
今天也是找一个项目的时候发现了您这个库（也是想看有没有横纵方向都适配的库），也是很惊讶这么短时间内就有相关技术库了，看了下issue区才知道另外2个库，所以想直观的了解下各个区别点（其实就是偷懒）……
另外……我这确实没有仔细看过demo和wiki，只是大概性的看了下，这点确实是我的锅，非常抱歉……

所以，如果总结性的来说的话，Rudeness和AndroidUtilCode 属于工具类，AndroidAutoSize拓展的版本，就是这样吧……

**Comment by JessYanCoding** [comment]
对，AndroidAutoSize 做的就是把这个方案优化到极致，也让关注这个方案的人，有一个归属地，这个方案的确不是完美的，但是却是成本最低的，现在使用 pt、in、mm 等冷门单位也可以避免一些坑

**Comment by lwlizhe** [comment]
好像今日头条只是上线到灰度测试吧…………
这玩意其实我个人真的感觉不是很稳定…………我和别人也交流过……发现可能是这个今日头条方案有时候会莫名其妙的失效…………我就说个我自己当时遇到的一个问题吧：自己放到后台一段时间，然后切回来，界面就全炸了……可能是我们几个写的代码的问题吧；另外听说部分8.0上面会失效，反正问题是不少的样子；
我很惊讶这么短时间就出了一个库的原因，就是能做到稳定和全面适配可不是一件容易的事，毕竟density这玩意都是各个ROM厂商为了适配自己的各种奇葩屏幕尺寸瞎jb乱写死的，而不是按照谷歌官方文档上说的那样设计的；而且这个density以及相应的px计算是系统的部分，因此各个ROM厂商会不会更改很大部分也不得而知，恶意揣测一下，谁知道会不会他自己写个计时器，定时更新density呢？？（笑~~）
目前也是没有时间去学习和研究这个库，不过也是很感谢博主的开源精神，虽然这个今日头条技术虽然非常简单，但是能适配到所有机型，做好维护工作，要耗费大量的精力和时间的，另外能推广和大量测试这个库，也是蛮耗精力的，这些都是像我这种又懒，文笔又差的人所做不到的…………

**Comment by JessYanCoding** [comment]
8.0 上的问题，早已经解决了，原因是通过 Activity 和 Application 获取到的 DisplayMetrics 不是同一个对象，两个对象都设置 density 就可以了，定制随时更新 density 也无所谓的，在 Activity setContentView 之前框架就会把 density 调整到当前 Activity 需要的值

唯一担心就是定制系统导致的 density 在某些情况下失效，这确实是一个最大的问题，不过也无法回避，在必要时刻不断修正 density 就可以了，鱼和熊掌不可兼得，有优点就会有缺点，如果你担心稳定性可以了解下 smallestWidth 限定符屏幕适配方案，这是我今天才发布的 [文章](https://juejin.im/post/5ba197e46fb9a05d0b142c62)，描述的非常细，可以看下，这个方案在灵活度和使用成本上都没今日头条这个方案好，但最大的优点就是你所关注的稳定

**Comment by lwlizhe** [comment]
目前就是使用的sw的限定符方式做的适配（毕竟也没其他方案了……），用screenMatcher插件生成的限定符其实也蛮方便的……有时候蛮羡慕ios的……他们那就那几种……而且尺寸、分辨率、屏幕横竖比都是一套对应一套的……
