### ISSUE TITLE
Toast 尺寸过于小

### ISSUE THREAD

**Issue by liuyouth** [JessYanCoding/AndroidAutoSize#55]
像这个系统的自带组件是否在框架内解决更为友好一些。

**Comment by JessYanCoding** [comment]
自定义 toast，或者在 toast show 之前 使用 AutoSize#autoConvertDensity 修改下设计图尺寸，直到设计图显示正常

**Comment by DevXue** [comment]
@JessYanCoding    老哥，  我现在就是用的副单位进行适配的，    然而今天出现了个问题就是，我引入的第三发库中有Toast弹框，这个Toast弹出来字体特别特别小， 而且我确定我关闭了对dp的支持，用的mm副单位，  这个问题是怎么引起的呢？  第三方库中的Toast弹框没有自定义，就是系统提供的方法··

**Comment by DevXue** [comment]
@JessYanCoding 我直接拿Demo开刀， 在subunits的Demo中写了Toast弹框，  运行之后 弹出来特别小。

**Comment by DevXue** [comment]
@JessYanCoding    感谢作者大大！

**Comment by yungelee** [comment]
@DevXue,我也研究了一下准备在项目中使用。你弹系统对哈u框出来是先手动调整设计图尺寸&关闭sp支持，然后show完了之后两个都恢复之前的设计尺寸吗(因为项目比较大了怕接入引入的问题，想多了解点)
