### ISSUE TITLE
全面屏底部有黑条

### ISSUE THREAD

**Issue by QuincySx** [JessYanCoding/AndroidAutoSize#56]
### Environment
- [x] Autosize Version:  v0.9.5 
- [x] Target Android Version:  Android 8.0 
- [x] Device Model:  自定义 、其他全面屏也有此问题比如 S8、小米6X
- [x] Device Resolution: 1080px * 2220px  5.3寸
- [x] Design Size On AndroidManifest: 360dp * 640dp

### Bug Description:
有一点不太明白，我是用的宽度适配，我布局设置高度设置为 match_parent 为什么底部有黑条呢

##### 配置：
什么都没做，默认的

##### 布局
```
<android.support.constraint.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context=".ui.Main2Activity">

    <TextView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:background="#FFFFFF"
        android:text="ssssdfdfd"
        android:textSize="16sp"
        android:textStyle="bold"
        android:textColor="#000000"
        app:layout_constraintBottom_toBottomOf="parent" />
</android.support.constraint.ConstraintLayout>
```

### Log:
```log
Main2Activity Info: isBaseOnWidth = true, designWidthInDp = 360.000000, targetDensity = 3.000000, targetScaledDensity = 3.000000, targetDensityDpi = 480, targetXdpi = 3.000000
```

### Screenshot
![image](https://user-images.githubusercontent.com/13297229/46092747-3032a900-c1e8-11e8-84aa-ef6faff23da0.png)

**Comment by JessYanCoding** [comment]
先不依赖框架，看看还有黑条不，如果关了框架就没有黑条不，那就试试在使用框架的情况下将 ConstraintLayout 替换成 LinearLayout，框架只是更改了 density，density 只会影响布局 dp 换算成 px 的过程，所以这个方案和 View 或者什么全面屏、刘海屏理论上来说并不存着任何关联关系，所以认真检察下是不是 View 或者哪个地方没设置对

**Comment by zsitlife** [comment]
试试在功能清单里设置最大纵横比2.1有没有效果

**Comment by QuincySx** [comment]
找到问题的关键了

targetSdkVersion >= 24 才支持全面屏的
targetSdkVersion < 24 需要添加以下代码

```
<meta-data 
  android:name="android.max_aspect"
  android:value="ratio_float" />
```

**Comment by JessYanCoding** [comment]
👌
