### ISSUE TITLE
-已解决

### ISSUE THREAD

**Issue by hais1992** [JessYanCoding/AndroidAutoSize#58]
求解，如何才能让系统以及一些第三方的控件、类库恢复正常。
换个方法问，就是怎样才能让这些控件展示出未使用AndroidAutoSize之前的样子。
下面图一是 AutoSizeConfig.getInstance().unitsManager.setSupportDP(false).supportSubunits = Subunits.PT
图二是 AutoSizeConfig.getInstance().unitsManager.setSupportDP(true).supportSubunits = Subunits.PT

![screenshot_2018-10-02-10-59-57-1015175296](https://user-images.githubusercontent.com/5223993/46328076-a5164080-c637-11e8-9d1b-77bb674216d8.png)
![screenshot_2018-10-02-11-40-47-0847707386](https://user-images.githubusercontent.com/5223993/46328141-16ee8a00-c638-11e8-88ab-ae07a5ccd83f.png)

**Comment by MoYuFly** [comment]
你是如何解决的，倒是说说啊，我现在关闭了，dp，sp的支持，dialogfragment 的取消和确定按钮没了，其他字体，框框什么都正常。
