### ISSUE TITLE
RecyclerView中的item适配不起作用

### ISSUE THREAD

**Issue by yannickxgg** [JessYanCoding/AndroidAutoSize#6]

**Comment by JessYanCoding** [comment]
提供页面截图，+ 框架日志截图

**Comment by yannickxgg** [comment]
sorry，是我这边自己设置的问题！

**Comment by wulijie** [comment]
AndroidAutoSize: initScaledDensity = 1.0 on ConfigurationChanged

我这边的问题是长时间待机在一个页面，上层覆盖一个页面，下面的页面内有RecyclerView，RecyclerView在很长一段时间回来以后，就适配失效了。
