### ISSUE TITLE
关于自定义view适配

### ISSUE THREAD

**Issue by senonwx** [JessYanCoding/AndroidAutoSize#62]
请问自定义view中怎么去设置控件的大小以及字体的大小？比如说怎么设置canvs绘制控件的大小等等

**Comment by JessYanCoding** [comment]
建议先看看我之前写的 [文章](https://www.jianshu.com/p/55e0fca23b4f)，理解下今日头条方案的原理，该方案和你使用什么 View 没有任何关系，实现原理和 鸿洋 的 AndroidAutoLayout 有本质上的区别，你平时的系统控件怎么用，自定义 View 就怎么用，使用上没有任何区别，如果自定义 View 时，想使用代码写死控件的大小，使用 [AutoSizeUtils](https://github.com/JessYanCoding/AndroidAutoSize/blob/master/autosize/src/main/java/me/jessyan/autosize/utils/AutoSizeUtils.java) 将你想使用的单位转换成像素即可
