### ISSUE TITLE
设计图尺寸

### ISSUE THREAD

**Issue by zhangweitao521** [JessYanCoding/AndroidAutoSize#63]
## 设计图尺寸
- 大神，我还是不明白该怎么在AndroidMainfest.xml配置尺寸；
- 假如设计图尺寸是750px*1334px，里面的所有尺寸都是以px标注的，包括文字大小也是24px；
- 是否可以写成一下配置；
```html
<meta-data
            android:name="design_width_in_dp"
            android:value="750"/>
<meta-data
            android:name="design_height_in_dp"
            android:value="1334"/>
```
- 然后在布局文件中同样以跟设计图一样的尺寸标注，比如
```html
<TextView
            android:layout_width="match_parent"
            android:layout_height="90px"
            android:gravity="center"
            android:text="犯我中华者虽远必诛"
            android:textColor="#000000"
            android:padding="16px"
            android:margain="32px"
            android:textSize="48px"/>
```
- 不然我要是把它全部转换成dp，1.工作量大2.会有偏差3.不知道以哪个转换率转换，1、1.5、2等,求指教

**Comment by JessYanCoding** [comment]
用副单位，即可按照设计图的标注，等比例的填写布局尺寸，不需要将 px 转换为 dp，详情请看 [demo-subunits](https://github.com/JessYanCoding/AndroidAutoSize/blob/master/demo-subunits/)，注释比代码还多，认真看注释

**Comment by JessYanCoding** [comment]
@DevXue 使用副单位，可以只是使用 px，比如像你上面的描述直接填写 20mm 即可，认真看 [demo-subunits](https://github.com/JessYanCoding/AndroidAutoSize/blob/master/demo-subunits/)，里面注释很详细

**Comment by DevXue** [comment]
@JessYanCoding   感谢大佬的指点，  我已经看懂了！  
我还有个疑问想问大佬！  在APPlication配置了使用mm来设置尺寸，  我现在遇到个问题就是  我在xml中写了两个Button  没有设置任何的宽高， 就是宽度为：match_parent  高度为：wrap_content   然后运行项目，发现Button特别小  字体也是特别小， 请问用了mm之后 ，以后布局中的 宽高  字体大小都是必须要设置实际的值吗？？？
![rqtumjz10 38 5tlw2d3fpx](https://user-images.githubusercontent.com/9455329/47144360-deb69f00-d2f9-11e8-8f4a-65bd6ac3ca7e.png)
![_20181018171853](https://user-images.githubusercontent.com/9455329/47144380-ed04bb00-d2f9-11e8-995e-65926b839cb9.png)

**Comment by JessYanCoding** [comment]
字体大小你不设置具体值，框架怎么知道什么大小的字体在屏幕上的显示效果最好，框架又不是人工智能...，wrap_content 是看 View 内容的大小，你内容都小，当然 View 本身也小，这些算比较基础的知识把，你太懂的话就看你的想法，设计具体值

**Comment by DevXue** [comment]
@JessYanCoding   感谢指点！
