### ISSUE TITLE
一加手机8.0适配顶部与状态栏之间有空隙

### ISSUE THREAD

**Issue by jackyHuangH** [JessYanCoding/AndroidAutoSize#64]
### Environment
- [x] Autosize Version: v1.0.0
- [x] Target Android Version:  Android 8.0 
- [x] Device Model:  Oneplus A3000(一加三)
- [x] Device Resolution:  1080px * 1920px
- [x] Design Size On AndroidManifest:  360dp * 640dp 

### Bug Description:

我按照文档配置，项目中首页Activity+多fragment,个人中心为activity，都出现顶部与状态栏之间有空隙，将baseOnwidth返回false依旧如此，但是另一台同分辨率的小米4（Android6.0）却正常，暂未找到解决方案

### Log:

```log
一加三：
2018-10-19 10:29:10.790 5854-5854/com.zenchn.housemonitor D/AndroidAutoSize: designWidthInDp = 360, designHeightInDp = 640, screenWidth = 1080, screenHeight = 1920
2018-10-19 10:29:10.791 5854-5854/com.zenchn.housemonitor D/AndroidAutoSize: initDensity = 2.375, initScaledDensity = 2.375
10:15:14.215 30842-30842/com.zenchn.housemonitor D/AndroidAutoSize: com.zenchn.housemonitor.mvp.main.MainActivity used the global configuration.
2018-10-19 10:15:14.217 30842-30842/com.zenchn.housemonitor D/AndroidAutoSize: The com.zenchn.housemonitor.mvp.main.MainActivity has been adapted! 
    MainActivity Info: isBaseOnWidth = true, designWidthInDp = 360.000000, targetDensity = 3.000000, targetScaledDensity = 3.000000, targetDensityDpi = 480, targetXdpi = 3.000000

小米4：
10-19 10:22:09.176 1471-1471/? D/AndroidAutoSize: designWidthInDp = 360, designHeightInDp = 640, screenWidth = 1080, screenHeight = 1920
10-19 10:22:09.176 1471-1471/? D/AndroidAutoSize: initDensity = 3.0, initScaledDensity = 2.58
10:23:07.397 1471-1471/com.zenchn.housemonitor D/AndroidAutoSize: com.zenchn.housemonitor.mvp.main.MainActivity used the global configuration.
10-19 10:23:07.397 1471-1471/com.zenchn.housemonitor D/AndroidAutoSize: The com.zenchn.housemonitor.mvp.main.MainActivity has been adapted! 
    MainActivity Info: isBaseOnWidth = true, designWidthInDp = 360.000000, targetDensity = 3.000000, targetScaledDensity = 2.580000, targetDensityDpi = 480, targetXdpi = 3.000000

```

### Screenshot

一加三手机：
![tim 20181019101549](https://user-images.githubusercontent.com/20255347/47194029-50d5c500-d388-11e8-903b-cd15d4026ab0.jpg)
![tim 20181019101605](https://user-images.githubusercontent.com/20255347/47194031-5501e280-d388-11e8-8147-cb53d36e3f95.jpg)
![tim 20181019101612](https://user-images.githubusercontent.com/20255347/47194035-58956980-d388-11e8-8b65-780670607591.jpg)

小米4：
![tim 20181019102441](https://user-images.githubusercontent.com/20255347/47194272-4c5ddc00-d389-11e8-9d1b-208ef84c3c89.png)
![tim 20181019102451](https://user-images.githubusercontent.com/20255347/47194281-51bb2680-d389-11e8-82e4-d703e9e41768.png)
![tim 20181019102456](https://user-images.githubusercontent.com/20255347/47194286-54b61700-d389-11e8-9524-cbbeafd7707f.png)

### Related Code:
```java
  baseFragment中配置：
 //今日头条屏幕适配方案配置
        AutoSizeConfig.getInstance().setCustomFragment(true);

```

**Comment by JessYanCoding** [comment]
如果是以宽度为基准，都会出现间隙的话，那很大概率不是框架原因了，因为框架的原理并没有涉及到与 View 相关的操作，只是单纯的修改 density，修改 density 只会影响 dp 转 px 的过程，你先把 AndroidAutoSize 取消依赖，看看是否还有间隙

**Comment by jackyHuangH** [comment]
取消依赖是没有间隙的，高度都是match_parent，顶到顶部的

**Comment by JessYanCoding** [comment]
实现 CancelAdapt 取消有间隙的页面的适配，看看是否还有间隙

**Comment by dxy1046** [comment]
@jackyHuangH 你应该是使用了沉浸式状态栏吧，ImmersionBar参考一下这个沉浸式的实现吧

**Comment by jackyHuangH** [comment]
我就是用的immer沉浸

**Comment by jackyHuangH** [comment]
@dxy1046 感谢老哥，我就是用的immer,不过没注意他更新了，已经找到解决方案了

**Comment by JessYanCoding** [comment]
👍已更新到常见 issues 中，以便于有相同问题的人快速索引 issues

**Comment by PhonHai** [comment]
> @dxy1046 感谢老哥，我就是用的immer,不过没注意他更新了，已经找到解决方案了
> ![tim 20181019134016](https://user-images.githubusercontent.com/20255347/47199522-8d171e80-d3a4-11e8-8403-857e59358929.png)

兄弟  没有这个方法啊，能不能发一下代码出来

**Comment by gyf-dev** [comment]
@jackyHuangH ImmersionBar更新到2.3.2-beat02版本之后，也不必使用两个参数的fitSystemWindows了

**Comment by Mac-sir** [comment]
初次添加使用适配没有问题，但是后面需要添加沉浸式状态栏后，在地下有一段空白（状态栏的距离）要怎么解决才好呢？
