### ISSUE TITLE
关于兼容部分rom缩放模式的问题

### ISSUE THREAD

**Issue by xiang23** [JessYanCoding/AndroidAutoSize#66]
是这样的,有部分品牌的rom有特殊的缩放模式（三星，好像魅族也有）
![8351e5faca5c5f077e2789451432848f](https://user-images.githubusercontent.com/14964761/47404202-fe791780-d77e-11e8-93b9-04bc3b00f521.jpg)
可以看到不同于分屏，这种模式下宽高都可以比较随意的改变。

当改变时view宽高时,按ScreenUtils.getScreenSize的逻辑的话就会发生差异
![image](https://user-images.githubusercontent.com/14964761/47404668-c4a91080-d780-11e8-948c-2ea765d59aa6.png)
上面的那个是按ScreenUtils.getScreenSize取的
下面的那个是按context.getResources().getDisplayMetrics()取的
可以看到明显不一致

事实上对普通手机分屏模式下应当也取的不一样

**Comment by JessYanCoding** [comment]
你好，我现在没有你说的此类设备，对你说的这种模式也不是很了解，不过，AndroidAutoSize 提供了 AutoSizeConfig#setScreenWidth 和 AutoSizeConfig#setScreenHeight，你可在进入这个模式，或在这个模式下用户改变宽高时自行将你上面获得的正确的高宽尺寸设置给框架

这里还需要注意一点，在此模式下，用户改变高宽时，如果这时布局的所有 View 并没有重新绘制，那今日头条屏幕适配方案是对这种模式是无论如何都不可能兼容的，因为今日头条屏幕适配的本质是只是修改 dp 转 px 算法，影响 px 的最终结果，如果系统不调用 TypedValue#applyDimension 重新设置各个 view px 值，那这个方案将无济于事

**Comment by xiang23** [comment]
这种模式会重建所有的view，我现在的处理方案就是手动使用setScreenWidth 和setScreenHeight是可以的。
7.0以后手机的使用分屏应该也会出现这种问题。
高改变了与ScreenUtils.getScreenSize()取到的应该也不一致，如果此时使用基于高的适配那么应该就能复现。

**Comment by JessYanCoding** [comment]
如果 ScreenUtils.getScreenSize() 中直接修改为返回 context.getResources().getDisplayMetrics() 中的高宽尺寸，按你的说法应该可以解决分屏和缩放模式，但我怕这会导致其他的问题，或者其他用户的某些需求不能实现，所以我还是建议先不修改，继续使用现有的方式，分屏和缩放模式这种特殊需求，通过单独的方法手动设置 AutoSizeConfig#setScreenWidth 和 AutoSizeConfig#setScreenHeight 来解决，所以希望你能提供你设置 AutoSizeConfig#setScreenWidth 的具体代码（在哪个时机调用的），我把这个 issues 提到常见 issues 中，让后续有同样问题的使用者能够看到

**Comment by xiang23** [comment]
发现三星的话如果缩放和分屏甚至有可能不重建view,但是把适配方法设置的参数还原了...要比较完美适配可能recyclerview或者viewpager等里面都要手动调用适配方法。。先放着了毕竟三星国内少数，有空再想象有什么比较好的方法

**Comment by JessYanCoding** [comment]
我可以按照你上面的建议提供一个在适配函数执行前后都会回调的监听器，你看这样能否解决这个问题

**Comment by JessYanCoding** [comment]
https://github.com/JessYanCoding/AndroidAutoSize/commit/54a166c731a9609ad7c0e4e9f3cd72fb66e9aa82

**Comment by JessYanCoding** [comment]
现在 AndroidAutoSize 已经将 ScreenUtils.getScreenSize 中屏幕尺寸的获取方式修改为了 context.getResources().getDisplayMetrics()，这样应该可以兼容大部分手机的缩放和分屏模式
