### ISSUE TITLE
文档中介绍的自定义模拟器无法创建

### ISSUE THREAD

**Issue by FynnJason** [JessYanCoding/AndroidAutoSize#67]
你好，设计师只给出了iphonex的设计图，分辨率为1125x2436，创建模拟器模拟器非常简单，设置screen size为4.8，设置好分辨率，顺利创建后，模拟器无法启动。不知道大佬知不知道原因。

**Comment by FynnJason** [comment]
用了第三方的模拟器来设置，不过还是没有解决AS中模拟器自定义尺寸为什么启动不了的问题。

**Comment by JessYanCoding** [comment]
这个就不清楚了，没遇到过 AS 自带模拟器无法启动的问题
