### ISSUE TITLE
提个疑问 ，在作者的demo中 使用mm适配的模块，尝试修改demo中文字的大小，会发现文字的大小会影响控件的高度。

### ISSUE THREAD

**Issue by pengjunhong** [JessYanCoding/AndroidAutoSize#68]
![11](https://user-images.githubusercontent.com/18617995/47474662-9263e580-d84a-11e8-97f8-777dea91bb2f.png)

**Comment by JessYanCoding** [comment]
你就算不用 AndroidAutoSize，字体大小也会影响 View，最常见的就是字体太大，导致挤压其他 View，这是 View 的特性导致的和框架没什么关系

**Comment by pengjunhong** [comment]
![12](https://user-images.githubusercontent.com/18617995/47474925-efac6680-d84b-11e8-99ec-6a3f74491157.png)

再次尝试发现 其实没有影响高度  但是会是控件下移。
