### ISSUE TITLE
主页面有很多个fragment，第一次运行软件，有的页面整体变得很大；当程序退出后，以后再进来都很正常，请问这是什么问题？

### ISSUE THREAD

**Issue by wjj201411** [JessYanCoding/AndroidAutoSize#69]
![266669149b766e919f034c3c0fe292ec](https://user-images.githubusercontent.com/9624595/47499289-2d33e280-d892-11e8-937d-cc3e35aed602.jpg)

正常效果
![534f4aab9a08970ccf5f9bf2cbbff025](https://user-images.githubusercontent.com/9624595/47499209-f5c53600-d891-11e8-935a-8f620dcd7cbb.jpg)

第一次运行时日志
![id4cszekc p ny_ng6 zhg](https://user-images.githubusercontent.com/9624595/47499221-fcec4400-d891-11e8-9a9f-0fa48f1b5008.png)

**Comment by JessYanCoding** [comment]
由于 Fragment 的生命周期特别复杂，很多特殊情况会导致框架自动适配的失效，如果遇到失效请在合适的时机手动适配比如 https://github.com/JessYanCoding/AndroidAutoSize/blob/master/demo/src/main/java/me/jessyan/autosize/demo/CustomFragment1.java#L47，参考 https://github.com/JessYanCoding/AndroidAutoSize/issues/13#11

**Comment by anuo10** [comment]
兄弟  你解决了么  我的也是  我还纳闷是什么原因呢 我的主页全是 fragment, 有时候进来  整体会变小 ,怎么解决呢?分享一波???我的并不是因为屏幕旋转导致的,就是偶然性的 ,但频率有点高

**Comment by wmjwmj828** [comment]
设计搞的尺寸是750*1334，那在fragment的onCreateView中调用AutoSize.autoConvertDensity(getActivity(), 375, true)指定density吗。是传的375吗，运行后尺寸不对

**Comment by JessYanCoding** [comment]
onCreateView 中调用 AutoSize.autoConvertDensity() 即可，不需要实现 CustomAdapt，AutoSize.autoConvertDensity() 中填写你 manifest 中写的宽度

**Comment by anuo10** [comment]
AutoSize.autoConvertDensity(getActivity(), 375, true);我把这句话加载我的 BaseFragment 的 onCreateView 方法中,还是不行...很尴尬

**Comment by JessYanCoding** [comment]
不行是哪种不行你也没截图，只要确定，View 在被绘制之前 density 被修改成期望的值，按系统的原理不会出现问题，除非是系统定制过，修改了某些东西

**Comment by anuo10** [comment]
暂时复现不了,不好意思哈,我看上面讲解,是在创建 fragment 的时候去约束布局,我想根据 fragment 的生命周期的去约束,应该就可以了.要是还有问题,再反馈哈

**Comment by JessYanCoding** [comment]
@anuo10 好的👌

**Comment by wmjwmj828** [comment]
我添加了AutoSize.autoConvertDensity(Objects.requireNonNull(getActivity()), 750, true);
但是偶尔重新进入app后，fragment中部分布局适配失效，我这里是include了一个布局，可以看到从横线开始适配就失效了，横线是40px的
![0iu7 o t it8_bph2p p9](https://user-images.githubusercontent.com/31396243/47695579-a1c5a300-dc3d-11e8-8cf3-a11596d0283d.png)

**Comment by JessYanCoding** [comment]
@wjj201411 重新进入 App 也需要调用 AutoSize.autoConvertDensity，比如在 onResume 中调用

**Comment by wmjwmj828** [comment]
我已经再onCreateView中调用了autoConvertDensity，还要在onResume中调用吗。
关于上面那个fragment中全部布局适配失效，控件变大的情况，虽然不会必现，但是测试反馈给我还是会偶现，我已经在onCreateView中调用了autoConvertDensity。

**Comment by wmjwmj828** [comment]
好的，谢谢群主哈

**Comment by DevXue** [comment]
@JessYanCoding   建议大佬加个更新日志···    我之前用的是1.0.0，今天看了下成了1.0.5了！  不知道大佬更新了什么！，  哈哈哈   这只是我个人的愚见啊！

**Comment by JessYanCoding** [comment]
@DevXue 一直有的哈 https://github.com/JessYanCoding/AndroidAutoSize/releases

**Comment by wmjwmj828** [comment]
@JessYanCoding 请问这个打印有方法控制吗
MainActivity Info: isBaseOnWidth = true, designWidthInDp = 750.000000, targetDensity = 1.440000, targetScaledDensity = 1.440000, targetDensityDpi = 230, targetXdpi = 1.440000

**Comment by JessYanCoding** [comment]
@wmjwmj828  AutoSizeConfig.getInstance()
                .setLog(false);

**Comment by JessYanCoding** [comment]
@wjj201411 兄弟，下图中说的软件是不是你上面截图的那个软件？
![ac6b7528-f99f-4c66-9e1e-919d1323496f](https://user-images.githubusercontent.com/15711968/53486542-f120c080-3ac3-11e9-8acd-98cb55568965.png)
![cca383ae-2f37-4fa8-a326-5512283185b8](https://user-images.githubusercontent.com/15711968/53486543-f1b95700-3ac3-11e9-9022-478fe7ece9f3.png)
