### ISSUE TITLE
建议多加点注释，我进来是一头雾水，不知道怎么用

### ISSUE THREAD

**Issue by liguangze** [JessYanCoding/AndroidAutoSize#7]
<manifest>
    <application>            
        <meta-data
            android:name="design_width_in_dp"
            android:value="360"/>
        <meta-data
            android:name="design_height_in_dp"
            android:value="640"/>           
     </application>           
</manifest>

看到了只需这一步
下面的CustomAdapt CancelAdapt 这个实现是什么意思
建议多添加点文字注释
还有用法，博客里面原理看的差不多，最后还是不知道怎么用

**Comment by JessYanCoding** [comment]
[中文 README](https://github.com/JessYanCoding/AndroidAutoSize/blob/master/README-zh.md) 已添加
