### ISSUE TITLE
你好，大神，麻烦请教下，我在项目里引用了“implementation 'me.jessyan:autosize:1.0.5'”，并且再AndroidManifest.xml文件中标注了设计图的尺寸宽高，分别为360、640，但是我再xml布局文件中设置高度为640dp在小米8上只显示了4/5屏，宽度也没沾满。这是什么原因呢？

### ISSUE THREAD

**Issue by w525721508** [JessYanCoding/AndroidAutoSize#73]
### Environment
- [x] Autosize Version: 
- [x] Target Android Version: 
- [x] Device Model: 
- [x] Device Resolution: 
- [x] Design Size On AndroidManifest: 

### Log:

```log


```

### Related Code:
```java
  

```

**Comment by w525721508** [comment]
> #8

你好，非常感谢你能回复我，我也很认真的看了一遍8楼的内容和原理，现在我大概明白了，咱们框架在没指定以高为基准的前提下都是以宽为基准的。比如我的设计图的宽高为：360dp/622dp,则框架默认以360dp为基准来计算density。从而实现宽度适配。但是我高度622dp*density的值小于手机真实的高度px，就导致的高度填充不满的情况。  对于这种宽高比例和设计图不同的手机，应该怎么操作才能适配呢？

**Comment by JessYanCoding** [comment]
框架只能保证在高度和宽度中只有一方可以和设计图上一模一样，另外一方肯定会和设计图出现偏差，原因就是保证能适配宽高比例和设计图不同的手机，你都知道高度上不能通过指定具体 dp 来实现显示效果和设计图完全一样，那你就不指定具体 dp，使用 wieght、RelativeLayout、或者约束布局，非指定具体 dp 的方式来实现整体的布局，这个是基础就不多说了
