### ISSUE TITLE
在三星Note Edge曲面屏手机适配出错

### ISSUE THREAD

**Issue by jaminchanks** [JessYanCoding/AndroidAutoSize#75]
设计图宽度尺寸375dp；
以下蓝色控件设计图宽度为187.5dp，理论上应占屏幕宽度一半。
在Pixel 2XL上的运行效果如下（尺寸匹配成功，最终读取到的屏幕宽度为375dp）：
<img src="https://user-images.githubusercontent.com/7419297/47901639-7c45cd00-debb-11e8-8e36-f685d09a4191.png" width="400">
在三星Note Edge上的运行效果如下（尺寸匹配失败，最终读取到的屏幕宽度不为375dp）: 
<img src="https://user-images.githubusercontent.com/7419297/47901716-ac8d6b80-debb-11e8-9fd1-23f53454e337.png"  width="400">

**Comment by JessYanCoding** [comment]
你这侧面不是有黑边吗

**Comment by jaminchanks** [comment]
> 你这侧面不是有黑边吗

有黑边。。这样看来，获取到的屏幕宽度应该是375减去了黑边的宽度，
但是不是很明白，为什么像下面的绿色和红色采用的是权重去分配宽度，能各自占据屏幕的一半。
而采用dp去分配宽度的蓝色却无法刚好占据屏幕的一半

**Comment by jaminchanks** [comment]
> 你这侧面不是有黑边吗

黑边是系统自带的。这种情况就会出现适配有问题吗。。
当我尝试着修改你源码中的ScreenUtils.java中的getScreenSize(Context context)方法为以下时，
```java
 public static int[] getScreenSize(Context context) {
        int[] size = new int[2];
//
//        WindowManager w = (WindowManager) context.getSystemService(Context.WINDOW_SERVICE);
//        Display d = w.getDefaultDisplay();
//        DisplayMetrics metrics = new DisplayMetrics();
//        d.getMetrics(metrics);
//        // since SDK_INT = 1;
//        int widthPixels = metrics.widthPixels;
//        int heightPixels = metrics.heightPixels;
//
//        // includes window decorations (statusbar bar/menu bar)
//        if (Build.VERSION.SDK_INT >= 14 && Build.VERSION.SDK_INT < 17)
//            try {
//                widthPixels = (Integer) Display.class.getMethod("getRawWidth").invoke(d);
//                heightPixels = (Integer) Display.class.getMethod("getRawHeight").invoke(d);
//            } catch (Exception ignored) {
//            }
//        // includes window decorations (statusbar bar/menu bar)
//        if (Build.VERSION.SDK_INT >= 17)
//            try {
//                Point realSize = new Point();
//                Display.class.getMethod("getRealSize", Point.class).invoke(d, realSize);
//                widthPixels = realSize.x;
//                heightPixels = realSize.y;
//            } catch (Exception ignored) {
//            }
        size[0] = context.getResources().getDisplayMetrics().widthPixels;
        size[1] = context.getResources().getDisplayMetrics().heightPixels;
        return size;
    }
```
三星Note Edge的尺寸得到了适配，最终的显示效果与Pixel 2XL中的一致。

**Comment by JessYanCoding** [comment]
那这个问题可能是原先的代码，在这个系统上获取到的屏幕宽度和期望的不一致，这段代码，是我在一个开源项目的工具类中复制过来的，理论上 getDisplayMetrics().widthPixels 也是没问题的

**Comment by jaminchanks** [comment]
那你在新的发布中能修复这个问题吗？

**Comment by JessYanCoding** [comment]
你需要提供一下，是哪段代码产生了误差，错误值是多少，期望值是多少，我看 [AndroidUtilCode](https://github.com/Blankj/AndroidUtilCode/blob/master/utilcode/src/main/java/com/blankj/utilcode/util/ScreenUtils.java#L42) 的代码也通过 getRealSize 获取的屏幕尺寸，你可以再测试下使用 AndroidUtilCode 的代码是否还有这种问题

**Comment by jaminchanks** [comment]
<a href="https://github.com/Blankj/AndroidUtilCode/blob/master/utilcode/src/main/java/com/blankj/utilcode/util/ScreenUtils.java#L42">AndroidUtilCode</a>的代码依然无法解决这个问题。
我参考了github上另外一个获取屏幕宽度的方法<a href="https://github.com/WuXiaolong/AndroidUtils/blob/e0fd21fbbd7365f37cd0b24043b142f9c1666f47/library/src/main/java/com/wuxiaolong/androidutils/library/DisplayMetricsUtil.java#L33">getScreenWidth</a>。这个解决了问题。
<a href="https://github.com/Blankj/AndroidUtilCode/blob/master/utilcode/src/main/java/com/blankj/utilcode/util/ScreenUtils.java#L42">AndroidUtilCode</a>中获取到的宽度是实际的屏幕宽度，而<a href="https://github.com/WuXiaolong/AndroidUtils/blob/e0fd21fbbd7365f37cd0b24043b142f9c1666f47/library/src/main/java/com/wuxiaolong/androidutils/library/DisplayMetricsUtil.java#L33">getScreenWidth</a>或者 getDisplayMetrics().widthPixels 所获取到的屏幕宽度会减去黑边的宽度，比如在Note Edge 中前者获取到的宽度是1600，后者是1532，中间多出来的就是黑边的宽度。

**Comment by JessYanCoding** [comment]
https://github.com/JessYanCoding/AndroidAutoSize/commit/dbe18139bee1d76e7cd3b86224cbb874abaeb123   你用源码依赖下，看问题解决没，解决我就发到远程库

**Comment by jaminchanks** [comment]
在note edge，pixel 2xl 和mix2s测试过，没有问题了。

**Comment by JessYanCoding** [comment]
ok，最好以高度为基准适配也测试下，me.jessyan:autosize:1.0.6 已发布

**Comment by jaminchanks** [comment]
以高度为基准也测试过了一遍，没有发现问题。:ok_hand:
