### ISSUE TITLE
莫名其妙的Crash

### ISSUE THREAD

**Issue by DCRain** [JessYanCoding/AndroidAutoSize#76]
### Environment
- [x] Autosize Version: v1.0.5
- [x] Target Android Version:  Android 8.1 
- [x] Device Model: 小米8
- [x] Device Resolution: 1080px * 2248px
- [x] Design Size On AndroidManifest: 375dp * 667dp

### Bug Description:
我使用的是1.0.5版本，1.0.1时也会出现问题。使用AndroidAutoSize时，常常会出现如图所示的异常，导致App直接崩溃，而且频率还有点高，一直找不到原因。一开始并不知道这个是框架的问题，后来全部继承CancelAdapt后，居然神奇的不出现了。从AndroidAutoSize日志上来看，一切正常。

![c6488c7db139767ef9e554c00761247f](https://user-images.githubusercontent.com/6848397/47960026-e41c2500-e02d-11e8-9af7-5abf65562784.jpg)
### Log:

![cfece45c-16aa-4186-a8c4-783da20ca4eb](https://user-images.githubusercontent.com/6848397/47960056-b2578e00-e02e-11e8-9ab6-67ea6d992750.png)

### Related Code:
```java
  

```

**Comment by JessYanCoding** [comment]
如果只有这些报错日志的话，无法确定是 AndroidAutoSize 的问题，并且我也无法帮你帮助你解决问题，因为这个报错日志没有任何有价值的信息，无法分析出任何问题

**Comment by DCRain** [comment]
> 如果报错信息只有这一点的话，很难分析出问题，看报错和 AndroidAutoSize 没什么关系
对啊，看着是没什么关系，但是，我一取消CancelAdapt就出问题，添加上CancelAdapt就不出问题，这就很尴尬了。

**Comment by JessYanCoding** [comment]
那试试在实现 CancelAdapt 的情况下，使用 AutoSize#autoConvertDensityOfGlobal 会报错不

**Comment by DCRain** [comment]
> 那试试在实现 CancelAdapt 的情况下，使用 AutoSize#autoConvertDensityOfGlobal 会出现同样的问题不
问题倒是没有，但是也没有适配。

**Comment by JessYanCoding** [comment]
使用 AutoSize#autoConvertDensityOfGlobal 和不实现 CancelAdapt 是同样的效果，如果调用 AutoSize#autoConvertDensityOfGlobal 不奔溃的话，那这就不是框架的问题，因为框架的原理也只是通过 ActivityLifecycleCallbacksImpl#onActivityCreated 在每个 Activity onCreate 之前调用 AutoSize#autoConvertDensityOfGlobal，没有再做其他的操作

**Comment by DCRain** [comment]
> 使用 AutoSize#autoConvertDensityOfGlobal 和不实现 CancelAdapt 是同样的效果，如果调用 AutoSize#autoConvertDensityOfGlobal 不奔溃的话，那这就可能不是框架的问题，因为框架的原理也只是通过 ActivityLifecycleCallbacksImpl#onActivityCreated 在每个 Activity onCreate 之前调用 AutoSize#autoConvertDensityOfGlobal，没有再做其他的操作

😂
