### ISSUE TITLE
横屏后能不能自动将design_width，和design_height互换

### ISSUE THREAD

**Issue by xjunz** [JessYanCoding/AndroidAutoSize#78]
### Environment
- [x] Autosize Version: 
- [x] Target Android Version: 
- [x] Device Model: 
- [x] Device Resolution: 
- [x] Design Size On AndroidManifest: 

### Log:

```log


```

### Related Code:
```java
  

```

**Comment by JessYanCoding** [comment]
这个属于业务的需求，框架不会自动帮你做这个操作，你可以通过框架提供的 AutoSizeConfig#setDesignWidthInDp 和 AutoSizeConfig#setDesignHeightInDp 自行在屏幕旋转时互换
