### ISSUE TITLE
影响statusBar的高度

### ISSUE THREAD

**Issue by sachil** [JessYanCoding/AndroidAutoSize#79]
- 手机型号：RedmiNote 4X
- MIUI版本：9.6稳定版
- Android版本：Android 7.0
- 屏幕尺寸：5.5英寸
- 屏幕分辨率：1080*1920

manifest设置为：
```
        <meta-data android:name="design_width_in_dp"
                   android:value="432"/>

        <meta-data android:name="design_height_in_dp"
                   android:value="768"/>
```
kotlin获取statusBar高度的代码：
```
    fun getStatusBarHeight(context: Context): Int {
        val resourceId = context.resources.getIdentifier("status_bar_height",
                "dimen", "android")
        return if (resourceId > 0) context.resources.getDimensionPixelSize(resourceId) else 0
    }
```
**问题描述：**

未添加AndroidAutoSize依赖时得到的statusBar高度为60px，添加AndroidAutoSize依赖后得到的statusBar高度却为50px。

**Comment by JessYanCoding** [comment]
因为 density 被框架修改了，所以需要使用 Resources.getSystem().getIdentifier("status_bar_height", "dimen", "android"); 来获取 statusBar，可以直接使用 me.jessyan.autosize.utils.ScreenUtils#getStatusBarHeight 获取 statusBar 高度
