### ISSUE TITLE
DialogFragment底部对有一部分的magin

### ISSUE THREAD

**Issue by xiaowifi** [JessYanCoding/AndroidAutoSize#80]
### Environment
- [x] Autosize Version: 
- [x] Target Android Version: 
- [x] Device Model: 
- [x] Design Size On AndroidManifest: 

### Bug Description:

我使用dialogfragment 绘制位于界面的底部的弹窗，在android 模拟器上运行未发现界面异常，但是在华为手机上发现，继承于dialogfragment的弹出距离底部有一些透明间距。
![image](https://user-images.githubusercontent.com/18083634/48047793-3ac36380-e1d4-11e8-8a1a-b1e18aacb7d7.png)
但是我对当前弹窗implements CancelAdapt 也没有改变。

### Related Code:
```java
  

```

### Others:
这是我的dialogfragment 的相关设置：
 getDialog().requestWindowFeature(Window.FEATURE_NO_TITLE);//取消标题栏
        getDialog().getWindow().setBackgroundDrawable(new ColorDrawable(Color.TRANSPARENT));//设置背景色为透明哦。
        this.setCancelable(Cancelable());//点击空白区域不取消。
 //设置为全屏
        DisplayMetrics dm = new DisplayMetrics();
        getActivity().getWindowManager().getDefaultDisplay().getMetrics( dm );
        getDialog().getWindow().setLayout( dm.widthPixels, getDialog().getWindow().getAttributes().height );

**Comment by JessYanCoding** [comment]
CancelAdapt 后，说明框架没又对这个页面进行任何操作，这个问题不一定是框架的问题

**Comment by xiaowifi** [comment]
> CancelAdapt后，说明框架没有对这个页面进行任何操作，这个问题不一定是框架的问题

可是，如果我当前activity 放弃适配的话就没有那个magin 了。[笑哭}

**Comment by xiaowifi** [comment]
> CancelAdapt后，说明框架没有对这个页面进行任何操作，这个问题不一定是框架的问题

哦哦，刚刚那个说法有误，现在的状态是，当我把适配代码删除后才没有那个magin ,在activity和dailogfragment中实现了CancelAdapt感觉没有效果，dialogfragment距离底部还是有magin.

**Comment by xiaowifi** [comment]
> 建议你 me.jessyan.autosize.AutoSizeConfig#stop 看还有 margin 吗

虽然没有太懂您的意思，因为是老项目，如果不使用适配的话是没有margin的哦。

**Comment by JessYanCoding** [comment]
框架其实只是修改了 density，只会影响 dp 转换 px 的过程，并没有对任何 View 做了修改，所以理论上除非是你自己的布局或者某种设置导致了此问题，框架是不会有这个问题的，让你使用 AutoSizeConfig#stop 停止适配，只是想看看是否是框架的问题

这个问题在你的项目你的设备上产生，只有你自己找出问题的原因了，如果找不出问题，你就只有取消适配了，试试手动适配了 AutoSize#autoConvertDensityOfGlobal

**Comment by JessYanCoding** [comment]
如果你有使用到沉浸式状态栏，也有可能是状态栏的问题，可以参考这个https://github.com/JessYanCoding/AndroidAutoSize/issues/64
