### ISSUE TITLE
在DialogFragment中没有适配成功（在tv和手机上），项目固定为横屏

### ISSUE THREAD

**Issue by huanyuan** [JessYanCoding/AndroidAutoSize#83]
public class BackDialogFragment extends DialogFragment implements CustomAdapt {
    @BindView(R.id.quit_iv) ImageView quitIv;
    @BindView(R.id.quit_msg_tv) TextView quitMsgTv;
    @BindView(R.id.quit_yes)
    Button quitYes;
    @BindView(R.id.quit_no) Button quitNo;

    @Override
    public boolean isBaseOnWidth() {
        return true;
    }

    @Override
    public float getSizeInDp() {
        return 1920;
    }

    class OkListener implements OnClickListener {
        OkListener() {
        }
        @Override
        public void onClick(View view) {
            dismiss();
            getActivity().finish();
        }
    }

    class CancelListener implements OnClickListener {
        CancelListener() {
        }
        @Override
        public void onClick(View view) {
            dismiss();
        }
    }

    public static BackDialogFragment getBackDialogFragment() {
            Bundle bundle = new Bundle();
            BackDialogFragment  mbackDialogFragment = new BackDialogFragment();
            mbackDialogFragment.setArguments(bundle);
        return mbackDialogFragment;
    }

    @Override
    public View onCreateView(LayoutInflater layoutInflater, ViewGroup viewGroup, Bundle bundle) {
        View inflate = layoutInflater.inflate(R.layout.dialog_fragment_quit, viewGroup);
        ButterKnife.bind(this,inflate);
        initListener();
//        AutoSize.autoConvertDensity(getActivity(), 1920, true);
        AutoSizeConfig.getInstance().setCustomFragment(true);
        return inflate;
    }

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
    }

    private void initListener() {
        quitYes.setOnClickListener(new OkListener());
        quitNo.setOnClickListener(new CancelListener());
        quitNo.requestFocus();
    }

    @Override
    public void onDestroy() {
        super.onDestroy();
    }

}

布局用的是dp

**Comment by huanyuan** [comment]
![qq 20181108102945](https://user-images.githubusercontent.com/12406954/48174114-9101e500-e341-11e8-96cc-28178b995b6c.jpg)
![screenshot](https://user-images.githubusercontent.com/12406954/48174122-995a2000-e341-11e8-9233-600e789be425.png)

**Comment by huanyuan** [comment]
![qq 20181108103416](https://user-images.githubusercontent.com/12406954/48174185-e0e0ac00-e341-11e8-9cec-20faa4b799bc.jpg)

**Comment by JessYanCoding** [comment]
https://github.com/JessYanCoding/AndroidAutoSize/issues/13

**Comment by mxdlsm** [comment]
> public class BackDialogFragment extends DialogFragment implements CustomAdapt { @BindView(R.id.quit_iv) ImageView quitIv; @BindView(R.id.quit_msg_tv) TextView quitMsgTv; @BindView(R.id.quit_yes) Button quitYes; @BindView(R.id.quit_no) Button quitNo;
> 
> ```
> @Override
> public boolean isBaseOnWidth() {
>     return true;
> }
> 
> @Override
> public float getSizeInDp() {
>     return 1920;
> }
> 
> class OkListener implements OnClickListener {
>     OkListener() {
>     }
>     @Override
>     public void onClick(View view) {
>         dismiss();
>         getActivity().finish();
>     }
> }
> 
> class CancelListener implements OnClickListener {
>     CancelListener() {
>     }
>     @Override
>     public void onClick(View view) {
>         dismiss();
>     }
> }
> 
> public static BackDialogFragment getBackDialogFragment() {
>         Bundle bundle = new Bundle();
>         BackDialogFragment  mbackDialogFragment = new BackDialogFragment();
>         mbackDialogFragment.setArguments(bundle);
>     return mbackDialogFragment;
> }
> 
> @Override
> public View onCreateView(LayoutInflater layoutInflater, ViewGroup viewGroup, Bundle bundle) {
>     View inflate = layoutInflater.inflate(R.layout.dialog_fragment_quit, viewGroup);
>     ButterKnife.bind(this,inflate);
>     initListener();
> ```
> 
> // AutoSize.autoConvertDensity(getActivity(), 1920, true); AutoSizeConfig.getInstance().setCustomFragment(true); return inflate; }
> 
> ```
> @Override
> public void onCreate(Bundle savedInstanceState) {
>     super.onCreate(savedInstanceState);
> }
> 
> 
> private void initListener() {
>     quitYes.setOnClickListener(new OkListener());
>     quitNo.setOnClickListener(new CancelListener());
>     quitNo.requestFocus();
> }
> 
> @Override
> public void onDestroy() {
>     super.onDestroy();
> }
> ```
> 
> }
> 
> 布局用的是dp

大佬您怎么解决的呀？
