### ISSUE TITLE
分屏状态，自由窗口状态怎么适配？

### ISSUE THREAD

**Issue by xjunz** [JessYanCoding/AndroidAutoSize#84]
### Environment
- [x] Autosize Version: 
- [x] Target Android Version: 
- [x] Device Model: 
- [x] Device Resolution: 
- [x] Design Size On AndroidManifest: 

### Log:

```log


```

### Related Code:
```java
  

```

**Comment by JessYanCoding** [comment]
https://github.com/JessYanCoding/AndroidAutoSize/issues/66
