### ISSUE TITLE
软键盘当前是弹出状态，此时点击按钮跳转到其他界面，当前界面会出现异常，截断现象。

### ISSUE THREAD

**Issue by xiangxm** [JessYanCoding/AndroidAutoSize#87]
Autosize Version: 1.0.1
  Target Android Version: 27
  Device Model: Pixel XL api28
  Device Resolution:1080px * 1920px
  Design Size On AndroidManifest: 360dp * 640dp

### Bug Description:

软键盘当前是弹出状态，此时点击按钮跳转到其他界面，当前界面会出现异常，截断现象。

### Log:

```log


```

### Screenshot

图片已发到邮箱

### Related Code:
```java
```

**Comment by JessYanCoding** [comment]
https://github.com/JessYanCoding/AndroidAutoSize/issues/74

**Comment by xiangxm** [comment]
@JessYanCoding 用这个方法在#74 也无法解决呢，提这个issue的目的是想进一步确认下是不是和框架内部有关系。 现在的处理方式是延迟200毫秒，等软键盘收回到再跳转。

**Comment by JessYanCoding** [comment]
@xiangxm 要想确认是不是框架问题，App 初始化时，调用 AutoSizeConfig#stop 停止框架的运行，在这个 Activity#onCreate 中调用 AutoSize#autoConvertDensity 看是否有同样问题，有同样问题，说明是今日头条方案都会存在的问题

**Comment by xiangxm** [comment]
@JessYanCoding  还有一个问题，弹出dialog或者toast之后，就是使用ContextCompat动态获取drawable显示到imageView上面，获取到的图会很大，直接导致OOM。 去掉框架后就不会出现这个现象。

**Comment by JessYanCoding** [comment]
暂不清楚，修改 Density 会导致影响图片的获取，可以同样依照上面的方式 App 初始化时，调用  AutoSizeConfig#stop 停止框架的运行，看是否还有这个问题，确定是框架封装的问题还是今日头条方案的问题
