### ISSUE TITLE
通过改变scaledDensity来设置全局字体大小，与框架冲突问题

### ISSUE THREAD

**Issue by ZhouXiang2018** [JessYanCoding/AndroidAutoSize#88]
//重写字体缩放比例 api<25
    @Override
    public Resources getResources() {
        Resources res = super.getResources();
        if (Build.VERSION.SDK_INT <= Build.VERSION_CODES.N) {
            Configuration config = res.getConfiguration();
            config.fontScale = getFontScale();//1 设置正常字体大小的倍数
            LUtils.e("api25:"+getFontScale());
            res.updateConfiguration(config, res.getDisplayMetrics());
        }
        return res;
    }

    //重写字体缩放比例  api>25
    @Override
    protected void attachBaseContext(Context newBase) {
        if (Build.VERSION.SDK_INT > Build.VERSION_CODES.N) {
            final Resources res = newBase.getResources();
            final Configuration config = res.getConfiguration();
            config.fontScale = getFontScale();//1 设置正常字体大小的倍数
            LUtils.e("api26:"+getFontScale());
            final Context newContext = newBase.createConfigurationContext(config);
            super.attachBaseContext(newContext);
        } else {
            super.attachBaseContext(newBase);
        }
    }

BaseActivity中添加上面这段代码通过改变scaledDensity的方式设置应用程序字体大小，与框架冲突，有没有好的解决方法，已尝试将框架中的设置SP系数的部分注释掉但未解决问题，谢谢

**Comment by JessYanCoding** [comment]
没什么方法，冲突就是冲突，框架和你下面的代码都需要修改同一个地方，这时就需要你自己修改代码加一个逻辑，判断不同的情况进行不同的修改，这就需要你对这方面的知识非常精通，否则你就三个选择，要不就不用框架，要不你不用下面这个方法，要不你不使用 sp，而我不会对这个业务逻辑给予任何支持，这个和事件冲突同理，你的业务逻辑只有你自己清楚，所以你自己处理

**Comment by houyongqi** [comment]
这个应该不是冲突的问题,只是对于scaledDensity的赋值少了参数
![image](https://user-images.githubusercontent.com/10208651/56636403-36fc9e00-669b-11e9-9626-5dfa3e4bee8f.png)
AndroidAutoSize对于scaledDensity的赋值只有了系统设置的系数,对于默认的fontScale直接为1
```
 float scale = AutoSizeConfig.getInstance().isExcludeFontScale() ? 1 : AutoSizeConfig.getInstance().
                    getInitScaledDensity() * 1.0f / AutoSizeConfig.getInstance().getInitDensity();
            targetScaledDensity = targetDensity * scale;
```

**Comment by zombiu** [comment]
> 这个应该不是冲突的问题,只是对于scaledDensity的赋值少了参数
> ![image](https://user-images.githubusercontent.com/10208651/56636403-36fc9e00-669b-11e9-9626-5dfa3e4bee8f.png)
> AndroidAutoSize对于scaledDensity的赋值只有了系统设置的系数,对于默认的fontScale直接为1
> 
> ```
>  float scale = AutoSizeConfig.getInstance().isExcludeFontScale() ? 1 : AutoSizeConfig.getInstance().
>                     getInitScaledDensity() * 1.0f / AutoSizeConfig.getInstance().getInitDensity();
>             targetScaledDensity = targetDensity * scale;
> ```

大佬 只是对于scaledDensity的赋值少了参数  这里说的是少了什么参数啊  我不是很明白

**Comment by zombiu** [comment]
> //重写字体缩放比例 api<25
> @override
> public Resources getResources() {
> Resources res = super.getResources();
> if (Build.VERSION.SDK_INT <= Build.VERSION_CODES.N) {
> Configuration config = res.getConfiguration();
> config.fontScale = getFontScale();//1 设置正常字体大小的倍数
> LUtils.e("api25:"+getFontScale());
> res.updateConfiguration(config, res.getDisplayMetrics());
> }
> return res;
> }
> 
> ```
> //重写字体缩放比例  api>25
> @Override
> protected void attachBaseContext(Context newBase) {
>     if (Build.VERSION.SDK_INT > Build.VERSION_CODES.N) {
>         final Resources res = newBase.getResources();
>         final Configuration config = res.getConfiguration();
>         config.fontScale = getFontScale();//1 设置正常字体大小的倍数
>         LUtils.e("api26:"+getFontScale());
>         final Context newContext = newBase.createConfigurationContext(config);
>         super.attachBaseContext(newContext);
>     } else {
>         super.attachBaseContext(newBase);
>     }
> }
> ```
> 
> BaseActivity中添加上面这段代码通过改变scaledDensity的方式设置应用程序字体大小，与框架冲突，有没有好的解决方法，已尝试将框架中的设置SP系数的部分注释掉但未解决问题，谢谢

大佬，你是怎么解决的，我这边在app内自己维护字体大小，调用resources.updateConfiguration(configuration, displayMetrics);会覆盖autesize的适配效果

**Comment by JessYanCoding** [comment]
https://github.com/JessYanCoding/AndroidAutoSize/blob/master/demo/src/main/java/me/jessyan/autosize/demo/BaseApplication.java#L70

这个问题不是去年就解决了吗，一行代码就搞定了，都不看 Demo 的吗？
