### ISSUE TITLE
华为手机界面被缩放显示了

### ISSUE THREAD

**Issue by muyetomato** [JessYanCoding/AndroidAutoSize#93]
![_20181127181416](https://user-images.githubusercontent.com/20183225/49075039-f5dd9a80-f270-11e8-84fb-6d93aac40e9d.jpg)

dependencies中 compile 'me.jessyan:autosize:1.1.0'

Application中 
 AutoSizeConfig.getInstance().setCustomFragment(true);
 AutoSizeConfig.getInstance().getUnitsManager()
                .setSupportDP(true)
                .setSupportSP(true) ; 

<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="fill_parent"
     >

    <RelativeLayout
        android:id="@+id/rl_touch"
        android:layout_width="1280dp"
        android:layout_height="752dp"
        android:background="@color/color_00BA9D"
        android:layout_centerInParent="true"
        >

        <RelativeLayout
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_alignParentRight="true"
            android:layout_marginTop="@dimen/padding12"
            android:orientation="horizontal" >

            <Button
                android:id="@+id/btn_back"
                android:layout_width="72dp"
                android:layout_height="57dp"
                android:background="@drawable/s_btn_back"
                android:onClick="back" />

            <Button
                android:id="@+id/btn_shezhi"
                android:layout_toRightOf="@id/btn_back"
                android:layout_marginLeft="@dimen/padding12"
                android:layout_marginRight="@dimen/padding12"
                android:layout_width="72dp"
                android:layout_height="57dp"
                android:background="@drawable/s_btn_shezhi"
                android:onClick="shezhi" />

        </RelativeLayout>

        <ImageView
            android:layout_width="453dp"
            android:layout_height="491dp"
            android:src="@drawable/shang"
            android:layout_centerHorizontal="true"/>

        <RelativeLayout
            android:layout_width="1280dp"
            android:layout_height="253dp"
            android:background="@drawable/xia"
            android:layout_alignParentBottom="true"
            android:layout_centerHorizontal="true"
            >

            <EditText
                android:id="@+id/et_name"
                android:layout_width="200dp"
                android:layout_height="39dp"
                android:singleLine="true"
                android:maxEms="4"
                android:layout_centerHorizontal="true"
                android:paddingLeft="40dp"
                android:background="@color/touming"
                android:hint="@string/login_name"
                android:gravity="center_vertical"
                android:textColor="@color/login_name"
                android:textSize="@dimen/login_name" />

            <Button
                android:id="@+id/btn_login"
                android:layout_width="61dp"
                android:layout_height="61dp"
                android:background="@drawable/s_dl_btn_login"
                android:layout_below="@+id/et_name"
                android:layout_centerHorizontal="true"
                android:layout_marginTop="@dimen/padding24"
                android:onClick="login" />

            <TextView
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_below="@+id/btn_login"
                android:layout_centerHorizontal="true"
                android:layout_marginTop="55dp"
                android:text="@string/company_name"
                android:textSize="@dimen/text_size17"
                android:textColor="@color/color_97BD2C"
                />
        </RelativeLayout>

    </RelativeLayout>

</RelativeLayout>
  

```


### Others:

**Comment by JessYanCoding** [comment]
详细描述发生问题，你的期望，
