### ISSUE TITLE
启动页适配问题

### ISSUE THREAD

**Issue by lchang70163** [JessYanCoding/AndroidAutoSize#95]
### Environment
- [x] Autosize Version: 
- [x] Target Android Version: 
- [x] Device Model: 
- [x] Device Resolution: 
- [x] Design Size On AndroidManifest: 

### Bug Description:

简单看了看，新手一枚，有些问题请教下，我在小米mix2s中测试，启动页是720*1280，设置了360和640，但是出现缩放问题，
![qq 20181129114239](https://user-images.githubusercontent.com/10189683/49197950-f0489780-f3cb-11e8-9486-8a5e2319f5f8.png) ，屏幕比18:9  请问我要怎么做。。

### Log:

```log


```
![qq 20181129113722](https://user-images.githubusercontent.com/10189683/49197956-f6d70f00-f3cb-11e8-8b99-a9739286d862.png)

### Related Code:
```java
  

```

**Comment by JessYanCoding** [comment]
你打个马赛克我怎么看得出哪里有缩放

**Comment by lchang70163** [comment]
![qq 20181129115128](https://user-images.githubusercontent.com/10189683/49198239-23d7f180-f3cd-11e8-95fd-c5c82e55e89e.png)我是写了个theme在启动页。。上下会显示间隔

**Comment by JessYanCoding** [comment]
match_parent，框架本身在以宽为基准时，高度就不会覆盖屏幕，https://github.com/JessYanCoding/AndroidAutoSize/issues/8
