### ISSUE TITLE
熄屏状态下启动程序有缩放现象

### ISSUE THREAD

**Issue by m-maohuawei** [JessYanCoding/AndroidAutoSize#98]
> 缩放的大小

![](https://i.imgur.com/Z7XqUIU.jpg)

> 正常的大小

![](https://i.imgur.com/CPDe26k.png)

**Comment by JessYanCoding** [comment]
https://github.com/JessYanCoding/AndroidAutoSize/issues/13#11

**Comment by JessYanCoding** [comment]
另外这什么游戏，斗战神？

**Comment by m-maohuawei** [comment]
开发的是游戏SDK

**Comment by m-maohuawei** [comment]
图片上的名字是齐天战神，但是现在这个并不是真正的游戏，只有测试SDK的游戏载体Demo,一张背景图片

**Comment by JessYanCoding** [comment]
好吧，问题解决没
